.circleci/config.yml
Using the `runInBand` option prevents jest from parallelizing tests, using more memory.
The `ci` option just causes the tests to fail when there are outdated snapshots, which doesn't affect us much now but it may in the future.
=> ci: Fix jest memory usage in CircleCI

.circleci/config.yml
Attempting to simplify the CI publishing workflow to just use `lerna publish`.
Our current config has been fragile over the years as lerna has updated, and is now pretty overcomplicated.
=> ci: simplify publishing config

packages/gamut/src/Form/RadioGroup.tsx
The prop is passed to the children, which are expected to be input elements (from Radios). The typings were wrong.
Related to https://github.com/codecademy-engineering/Codecademy/pull/15076, where there's an unfortunate `as any` on an `e.target`...
=> Corrected onChange prop for RadioGroup

packages/eslint-config/index.js, packages/eslint-config/package.json, packages/gamut/src/ButtonBase/index.tsx, packages/gamut/src/DeprecatedTabs/index.tsx, yarn.lock
I tested out the new version on the monolith in https://github.com/codecademy-engineering/Codecademy/pull/15093. You were right @jakemhiller, there were a few rules we like and used to have from the airbnb presets that we no longer do. They're mostly esoteric ones from the React rulesets that aren't enabled by default in their recommended config. I manually added them here.
This also bumps the typescript-eslint packages to 2.7.0 to get us that sweet performance improvement in https://github.com/typescript-eslint/typescript-eslint/pull/1179. It brings our monolith's prospective new lint time down from _10 minutes_ (!!) to _2_. Phew!
=> Bumped typescript-eslint to 2.7; added missing airbnb rules

packages/eslint-config/index.js, packages/gamut/package.json, packages/gamut/src/Button/index.tsx, packages/gamut/src/ButtonBase/index.tsx, packages/gamut/src/FlexGrid/Col.tsx, packages/gamut/src/FlexGrid/Grid.tsx, packages/gamut/src/FlexGrid/Row.tsx, workspaces/gamut-storybook/package.json
I was in the area and remembered that we still use them... but the only reasons are to get prop key lists to omit. Begone!
Annoyingly, `yarn.lock` didn't update after a `yarn`, because we depend on packages that depend on them... ah well.
=> Removed prop-types from gamut once and for all

packages/gamut/src/Form/styles/FormGroupDescription.scss, packages/gamut/src/Toggle/index.tsx, workspaces/gamut-storybook/stories/Toggle.stories.js
- increased contrast for FormGroupDescription
- added aria-label for Toggle (so the toggle is not missing a label)
(note: need these changes for accessibility test for Codecademy account/mail_settings page codecademy-engineering/Codecademy#15338)
---
=> fix FormGroupDescription and Toggle accessibility

packages/webpack-config/src/config/common.js
Because the output file contains the id, this change wasn't really necessary.
As it's the more standard webpack setup, let's just stick with it until Webpack 5 and reassess.
=> revert removal of id from default hashes

packages/gamut/src/Markdown/__tests__/Markdown-test.tsx, packages/gamut/src/Markdown/index.tsx
The fancy table addition isn't always desirable. On our /policy page, for example, we just want a regular non-sticky table. See https://github.com/codecademy-engineering/Codecademy/pull/15335.
=> Allowed skipping tag processing in Markdown

packages/gamut/src/Toggle/styles/index.module.scss
Per Sarah's request to fix the accessibility issue.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
https://codecademy.atlassian.net/browse/A11Y-208
=> Used gray-500 for toggle unchecked state

packages/gamut-icons/icon-template.js, packages/gamut-icons/svgr.config.js
Sets a default size instead of using `1em` to match the text size. We never used that sizing before so replacing the icons on the site with `gamut-icons` will be more difficult if we do that.
Also adds `currentColor` to the attribute overrides, a few icons authored with `currentColor` were not getting the color prop applied.
=> gamut-icons adjustments

packages/gamut-templates/package.json, packages/gamut/src/Markdown/__tests__/Markdown-test.tsx, packages/gamut/src/Markdown/libs/overrides/index.tsx
Because we were using string replacement to pull out the language of code blocks, introducing a new class name broke syntax highlighting.
in this case because we derive the language from the class name, and the class name was `code language-js`, we passed the language down to the code block override as `code js`, instead of `js`.
=> fix: use safer method to pull out markdown language prop

packages/gamut/src/Form/Radio.tsx
They're spread onto the input node, so this was an overly limited props type before.
=> Added HTMLInputElement types to Radio props

packages/gamut/src/FlexGrid/Col.tsx, packages/gamut/src/FlexGrid/Row.tsx
Updates to make Row proptypes be similar to Col proptypes.
Also, both component's optional props are now optional and not required
=> fix: tx updates for Row and Col

packages/gamut/src/Form/Select.tsx
This is more correct. For https://github.com/codecademy-engineering/Codecademy/pull/15761, I want `onChange` events to have a `target.value`. They don't prior to this change.
=> Used FormHTMLAttributes for Select props

packages/gamut/src/NotificationList/NotificationItem.tsx, packages/gamut/src/NotificationList/__tests__/NotificationItem-test.tsx, packages/gamut/src/NotificationList/styles/Notification.module.scss
We can't have `<div>`s because the notification list needs to contain at least one focusable item. If the only notification is for a streak, it needs to be a `<button>`.
Simulating most of the properties of a notification _(looks like I missed the main text, heh)_ to verify the styles don't look all weird and button-y:
=> Allowed all notification items to be focusable

.circleci/config.yml, codecov.yml
I've been noticing that the graph on the codecov comment usually doesn't reflect the actual coverage status, so I'm removing it from the comment.
=> Clean up the codecov PR comment

packages/gamut/src/Markdown/styles/_mixins.scss
https://codecademy.atlassian.net/browse/LX-3565
where LaTeX is showing up as dark text in quiz answers
=> fix: markdown styling: do not override code color

packages/gamut/src/Markdown/styles/_mixins.scss, packages/styleguide/stories/Markdown/Markdown.stories.js
Previously these just looked like normal paragraphs.
=> fix: Add missing blockquote styles to markdown

packages/gamut/src/NotificationList/styles/Notification.module.scss
My change to make those notifications focusable by making them `<button>`s centered the text. Oy.
Before:
After:
=> Left aligned notification button text

packages/brand-components/CHANGELOG.md, packages/brand-components/README.md, packages/brand-components/babel.config.js, packages/brand-components/package.json, packages/brand-components/src/Avatar/__tests__/avatar-test.tsx, packages/brand-components/src/Avatar/index.tsx, packages/brand-components/src/Avatar/styles.module.scss, packages/brand-components/src/index.ts, packages/brand-components/src/typings/css.d.ts, packages/brand-components/src/typings/svg.d.ts, packages/brand-components/tsconfig.json, packages/styleguide/stories/Avatar.stories.js
[The Brand Components package will be used for components that are more tied to brand representation and/or marketing purposes. These are components that might be more frequently subject to style updates do their nature, but are not just solely used in the main Codecademy monolith app. (e.g., a brand component might also be used in a Gatsby hosted campaign page)](https://github.com/Codecademy/client-modules/blob/86671ea7005ae43cf0fa528e8bd7775b9694fe14/packages/brand-components/README.md#component-guidelines)
Also includes the first component in the package:
#631
---
=> initialize Brand Component package with Avatar component

packages/brand-components/src/Testimonial/__tests__/Testimonial-test.tsx, packages/brand-components/src/Testimonial/index.tsx, packages/brand-components/src/Testimonial/styles.module.scss
**Prior**: The background shape image was absolutely positioned on the card itself, and had used `z-index` to display correctly.
This meant that if the parent of the element had a background color, the pattern would _disappear_ D:
**Change**: 
I wanted to ensure that card and shape were self-contained within a parent component that would wrap it all together. (And not use z-index)
The implementation here was to use two wrapping divs.
The highest div in the hierarchy would be used to display the shape using pseudo selectors.
The second highest div would wrap the testimonial card in a `grid` display and use `grid-template` to specify that the first child (the card) should sized according to itself (`max-content` : The intrinsic preferred width.)
Then the second value for `grid-template`, …
=> fix: testimonial component background pattern

packages/webpack-config/package.json, yarn.lock
BREAKING CHANGE: Now there'll only be one version of `autoprefixer` and, well, two of `browserslist`. Hopefully that'll stop unnecessary CSS rules such as `-webkit-flex` from getting included in our CSS?
=> chore: updated and consolidated autoprefixer to ^9.7.4

.circleci/config.yml, .eslintrc.js, codecov.yml, packages/styleguide/.eslintrc.js, packages/styleguide/stories/Avatar.stories.js, packages/styleguide/stories/Quote.stories.js, packages/styleguide/stories/Testimonial.stories.js
This adds linting rules to restrict imports from the `./stories` folder to `@codecademy` modules and `../../gamut/dist` & co.
The reason for this is that when these imports exist, the styleguide is referencing code that might not exist if you didn't run `yarn build-all`. It also means we're referencing compiled code in storybook, which is meant to use the source code directly.
---
=> ci: restrict imports from stories to the module src folders

packages/gamut/src/Icon/iconMap.tsx, packages/gamut/src/Icon/index.tsx
That's the new location, right?
=> chore: mentioned gamut-icons in deprecation messages for icons

packages/brand-components/src/Testimonial/__tests__/Testimonial-test.tsx, packages/brand-components/src/Testimonial/index.tsx, packages/styleguide/stories/Testimonial.stories.js
Update testimonial component so that it takes in a `testimonial` prop that is an object, rather than several individual props.
```
export type Testimonial = {
firstName: string;
lastName: string;
occupation: string;
quote: string;
company?: string;
imageUrl?: string;
};
```
We want to have both a `firstName` and `lastName` field, as well as `company` so that the Byline container can be updated to show `lastName`/`company` depending on the size of the component.
See:
---
=> feat: add `testimonial` object prop to Testimonial component

packages/brand-components/src/Testimonial/styles.module.scss
The Byline row for Small and Medium sizes had a fix row right height of 76px, (to account when no picture is present and avoid bouncing). What's a better thing is to use `minmax` on that property for flexibility.
See: https://github.com/codecademy-engineering/static-sites/pull/25#pullrequestreview-385087061 which is causing the styling to look off.
---
=> fix: update `grid-template-row` on small and medium testimonials

packages/gamut/src/Layout/Column.tsx, packages/gamut/src/Layout/__tests__/utilities-test.ts, packages/gamut/src/Layout/styles/shared.scss, packages/gamut/src/Layout/types.ts, packages/gamut/src/Layout/utilities.ts, packages/styleguide/stories/Layout.stories.js
- Adds an XS config to layout grid for sizes smaller that 768.  Still not ideal but it will give us more flexibility in the meantime.
- Also makes all props optional on offset so we don't have to add xs, but without type complexity.  If they leave it blank it just does nothing.
- Makes the docs a bit nicer and the code samples more transparent.
I might propose we remap the sizes to something like this if we have continued mobile woes with the possibility of adding XL at ~1200:
`xs > 0 | sm > 480 | md > 768 | lg > 1024`
=> feat(LayoutGrid): Adds XS size to layout grid responsive components

packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap, packages/gamut/src/ProgressBar/__tests__/ProgressBar-test.tsx, packages/gamut/src/ProgressBar/index.tsx, packages/gamut/src/ProgressBar/styles.module.scss, packages/gamut/src/index.tsx, packages/styleguide/stories/ProgressBar-story.scss, packages/styleguide/stories/ProgressBar.stories.js
ProgressBars are to be used when you'd like to indicate a known or somewhat-known amount of progress along a fixed course. For example, you might show one on a quiz page indicated how many questions have been completed.
Styles for the background, bar, and font colors are configurable.
WEB-779
=> feat: created ProgressBar primitive for Gamut

packages/brand-components/src/index.ts, packages/gamut-templates/src/index.ts
Might as well, right? It doesn't fix the `yarn start` issues with gamut-templates, but I think it at least helps with exporting props?
=> chore: also export all as in non-Gamut packages

packages/gamut-icons/icon-template.js, packages/gamut-icons/index-template.js, packages/gamut-icons/package.json
Ran into a weird parsing error on the default index template:
```
127 | export { default as ViewIcon } from './ViewIcon'
128 | export { default as YoutubeIcon } from './YoutubeIcon'
> 129 | export { default as ZoomIcon } from './ZoomIcon'try {
|                                                 ^
130 |     // @ts-ignore
131 |     ForwardRefExoticComponent.displayName = "ForwardRefExoticComponent";
132 |     // @ts-ignore
```
Changes:
- Bumped SVGR version
- Added index template and changed export syntax to match other packages
- All icons now are named exports and defaults.
=> feat(Icons): Add named export to gamut icons and update SVGR

packages/gamut/src/ProgressBar/__tests__/ProgressBar-test.tsx, packages/gamut/src/ProgressBar/index.tsx
Splitting off from #695, this is a more technically correct name for the prop.
=> feat(Gamut)!: switched ProgressBar's displayLabel prop name to be large

packages/gamut/src/GridForm/index.tsx, packages/styleguide/stories/Organisms/GridForm.stories.tsx
We'll need to allow responsive layouts for our forms. This allows consumers of `GridForm` to specify their gaps.
=> feat(GridForm): added columnGap and rowGap as props to GridForm

packages/gamut/src/Form/Select.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/index.tsx, packages/gamut/src/GridForm/GridFormSubmit/index.tsx, packages/gamut/src/GridForm/types.ts, packages/styleguide/stories/Organisms/GridForm.stories.tsx
- Allows a checkbox to be required. Example: check to agree to the TOC.
- Allows a select input to be required. Example: many sets of select options include a blank first option. Requiring means making sure they choose a non-blank option.
- Includes a story to illustrate this.
**Additional changes**
- ~feature: allow `GridForm` submit button to have a disabled state~ Update: not doing this today
- fix: removed a pesky react warning about `error` attribute passed to an html div tag
=> feat: GridForm checkbox and select required validation

packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/__tests__/GridFormInputGroup-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/index.tsx, packages/gamut/src/GridForm/index.tsx, packages/gamut/src/GridForm/types.ts, packages/styleguide/stories/Organisms/GridForm.stories.tsx
Some forms, such as the checkout flows that use Recurly, need to define their own inputs. This adds a `'custom'` field type to `GridForm` with a [render prop](https://reactjs.org/docs/render-props.html) to allow such a thing.
Most notably, that render prop receives both a `react-hook-form`-style `register` and a traditional React-style `setValue`, which it can use either of to hook up its state.
=> feat(Gamut): added 'custom' field type to GridForm

packages/gamut/src/GridForm/GridFormSubmit/index.tsx, packages/gamut/src/GridForm/GridFormSubmit/styles.module.scss, packages/styleguide/stories/Organisms/GridForm.stories.tsx
- allow positioning of button to be left, right, or center
- allow button theme selection
We wrote this PR in order to make GridForm a better fit for CheckoutV3. These changes will allow us to use it for the [Membership Step](https://app.abstract.com/projects/746e0c79-eaf0-45b4-a413-bd470026837d/branches/c5e9bd98-2b7f-456e-933f-04c825facdc2/commits/33e86423f7efb02aae30e469db3e198912d3605f/files/2d17f083-174b-4794-b03d-45d5ff463f43/layers/4E6CBFE1-24CC-476B-A856-99FDEC37EE82?collectionId=d87a4292-ae3f-4118-b248-1edbab34341e&collectionLayerId=1f9501f1-bce7-422a-aed4-b41ba619bb3c).
See [Checkout V3 design PR ](https://github.com/codecademy-engineering/Codecademy/pull/16835) for context
@JoshuaKGoldberg - we initially did positioning via offset, this however did not fully solve the use-case …
=> feat(gamut): Add GridForm Submit Button functionality

packages/gamut/src/AccordionButton/styles.module.scss
* Removed the yellow theme's left and right borders (since the LE doesn't have them)
* Made the arrow rotate into position instead of flip - and a little more quickly
Mike Kenny indicated a lack of preference for which animation is used, and I like the rotate-y one more.
=> feat(Gamut): tweaked AccordionButton to look more like the nice LE yellow ones

packages/gamut-styles/utils/variables/_colors.scss, packages/gamut-styles/utils/variables/index.js, packages/styleguide/stories/Foundations/Colors/Colors.stories.tsx, packages/styleguide/stories/Foundations/Colors/styles.module.scss, packages/styleguide/stories/Templating/StoryTemplate/index.tsx
The previous `basic-` and `code-` swatches are unused in the monolith and LE colors are generally hardcoded. This PR will let us `import { editorColors }` to reference them in JS.
Existing locations that match exactly:
* CodeMirror: [`theme.scss`](https://github.com/codecademy-engineering/Codecademy/blob/4e807c71b01debdcec2153b87ad4cafd26bbedbc/webpack/assets/components/CodeMirror/styles/theme.scss#L7)
* Monaco: [`colors-dark.tsx`](https://github.com/codecademy-engineering/Codecademy/blob/c284f875790ae877dcc5fcf5122f8141bcee6439/webpack/assets/components/MonacoEditor/themes/colors-dark.tsx#L3)
=> feat(gamut-styles): formalized Editor colors in gamut-styles

packages/styleguide/stories/Atoms/ProgressBar/ProgressBar.stories.tsx
It was switched to `large` around the same time as I redid stories. Oops.
=> feat(styleguide): corrected displayLabel/large prop name for ProgressBar story

package.json, packages/eslint-config/package.json, yarn.lock
This'll unblock us from using it on the monolith.
=> feat(eslint-config): typescript-eslint version for TS 3.8

packages/gamut/src/ProgressBar/__tests__/ProgressBar-test.tsx, packages/gamut/src/ProgressBar/index.tsx, packages/gamut/src/ProgressBar/styles.module.scss, packages/styleguide/stories/Atoms/ProgressBar/ProgressBar.stories.tsx
* `minimumPercent` addresses the existing logic in our small blue bars that always show at least ~5% progress.
* `theme` replaces the more convoluted `style` prop and restricts us to just the approved `blue` and `yellow` themes.
As with other ProgressBar PRs, since it's not used anywhere, I'm not going to bother marking this PR as a breaking change.
=> feat(Gamut): added ProgressBar minimumPercent and theme props

packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap, packages/gamut/src/Alert/index.tsx
This was not exported before and needed to be pulled in from `/dist`
=> fix(Alert): Export BannerType enum to be used from root

packages/gamut/src/ProgressBar/__tests__/ProgressBar-test.tsx, packages/gamut/src/ProgressBar/index.tsx, packages/gamut/src/ProgressBar/styles.module.scss, packages/styleguide/stories/Atoms/ProgressBar/ProgressBar.stories.tsx
Per discussions with @hmafzal, our preference (#749) is to keep atoms open to custom themes while we flesh out their usage. `ProgressBar` is still pretty new so we're going to want to keep it theme-happy.
=> feat(Gamut): switched ProgressBar back to taking in a 'style' prop

packages/gamut/src/GridForm/index.tsx
In our static Gatsby site's `GridForm`, `register` is getting called twice per input element... once in the React logic `ref={register(field.validation)}`, then a second time in the GridForm's `useEffect` that does `register({ name: field.name })`. That means react-hook-form's understanding of the field gets overridden to that second, dumb object, which doesn't know anything.
On the monolith, we rerender in React a bunch of times unnecessarily, so the component's ref overrides the dumb object (so, 3 or more registrations), and this bug gets fixed by accident.
=> fix(Gamut): Removed unnecessary useEffect registers in GridForm

packages/gamut-styles/utils/variables/_colors.scss, packages/gamut-styles/utils/variables/index.js, packages/gamut/src/Button/styles/variables.scss, packages/styleguide/stories/Atoms/Button.stories.tsx
* `darkblue`: the "Start" button on the soon-to-be-deprecated course page. [Monolith PR: swap to `brand-blue`](https://github.com/codecademy-engineering/Codecademy/pull/17326)
* `midnightblue`: the cancel button on deleting drafts. [Author PR: swap to `brand-dark-blue`](https://github.com/codecademy-engineering/author/pull/1193)
=> chore(Gamut): Removed unused deprecated button themes

packages/gamut/src/Form/RadioGroup.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/__tests__/GridFormInputGroup-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/index.tsx, packages/gamut/src/GridForm/__tests__/stubs.ts, packages/gamut/src/GridForm/types.ts, packages/styleguide/stories/Organisms/GridForm.stories.tsx
It's a pretty typical input form, except that there isn't a single input element to `ref` with -- so it uses a manual `setValue` call.
=> feat(Gamut): added RadioGroup inputs for GridForm

packages/gamut/src/GridForm/types.ts
- `GridFormCheckboxInput` currently only accepts `string` as `label` type. This limits customization and does not parallel the existing `Checkbox` functionality. So in this PR, we extend `GridFormCheckboxInput` to accept ReactNode as its `label` type.
- JIRA: https://codecademy.atlassian.net/browse/GM-7
=> feat(Gamut): Allow GridFormCheckboxInput to take in a ReactNode as its label

packages/gamut/src/GridForm/index.tsx
For fields that are just a single submit button, such as the account deletion field, we don't need to pass in fields. It's still a nice thing to use GridForm for them because we'll get standardized loading behavior.
=> feat(Gamut): Allowed GridForm to not take in any fields

packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/index.tsx, packages/gamut/src/GridForm/types.ts
No plans on using it in prod, but it uses the built-in browser date things now and is useful on our internal admin pages.
=> feat(Gamut): Allowed GridForm text fields to be of type 'date'

packages/gamut/src/Form/Checkbox.tsx, packages/gamut/src/Form/styles/Checkbox.module.scss, packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx, packages/gamut/src/GridForm/types.ts, packages/styleguide/stories/Atoms/FormInputs/FormInputs.stories.tsx
- top-align checkbox
- center align label
- add multiline prop to add margin-top to checkbox making it look better aligned with a long label
We collaborated with @JoshuaKGoldberg and Tamar on this. We are currently using static values to address the multiline use-case. This mostly aligns the checkbox and the label text for font-sizes between 12 and 16px. For other sizes it will not look as good.
Please advise if we want to make this more flexible through the passing of a className for the checkbox or some other means.
--- …
=> feat(Gamut): Checkbox default style changes and add multiline prop

packages/gamut/src/Form/Radio.tsx, packages/gamut/src/Form/__tests__/RadioGroup-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx, packages/styleguide/stories/Organisms/GridForm.stories.tsx
Per [GM-10](https://codecademy.atlassian.net/browse/GM-10), we want to add a registration for the individual `Radio` elements. That's the good stuff. 
Added a validation to the `GridForm` story to show it off.
Steps to repro:
1. View a GridForm that includes a radio group input with a validation (such as being required)
2. Submit the form in a way that fails that validation → you should see complaint text on the radio group
3. Update the radio group to pass the validation → the complaint text does not go away  
4. Submit the form → the complaint text now does go away
=> fix(Gamut): Correctly hooked up GridForm's radio-group inputs for validation updates

.vscode/extensions.json
Adds recommendation for highlighting for styled component template strings.
Storybook native components use this so might as well start.
=> chore: Add recommendation for styled-components highlighting extension

packages/styleguide/stories/Core/Molecules/Tabs/Examples.tsx, packages/styleguide/stories/Core/Molecules/Tabs/Tabs.stories.mdx
Didn't include this in the initial wave because Tabs relies on checking component instance type to work.  Rendering directly using MDX's JSX renderer causes this to break due to wrapping each element in `MDXCreateElement` and forwarding the props. 
The work around here is either register the stories in a separate file and adding a markup block for a source example.  Potentially we could embed the stories from a separate page and have general source extraction, but for now this seems simple enough.
Before:
After:
=> chore(Styleguide): Update tabs stories to MDX

packages/gamut/src/GridForm/GridFormInputGroup/index.tsx, packages/gamut/src/GridForm/types.ts
I have a need for `password`. @jakemhiller mentioned recently that we could just use a `default` case for these input types. Works for me!
=> feat(Gamut): Allowed general text inputs for GridForm

packages/gamut/src/Card/CardShell.tsx
Some of our tests were failing because using `forwardRef` removes the automatic `displayName` from the component. Need to add it back manually.
---
=> fix: preserve display name on card shell

README.md, packages/gamut/package.json, packages/gamut/src/GridForm/types.ts, yarn.lock
Add docs and a watcher for working with Gamut locally using symlinks. Update `GridFormField` type to accept ReactNodes.
- Allowing a node prop for a GridFormField labels allows for more flexible use.
- One gotcha I couldn't figure out: Running Jest tests in the monolith with this set-up. In the current state, Jest throws an error saying
```
babel-jest: Babel ignores ../client-modules/packages/gamut/dist/index.js - 
make sure to include the file in Jest's transformIgnorePatterns as well.
```
---
**IMPORTANT:** If your PR contains …
=> feat(Gamut): Add docs/command for working with Gamut pre-publish

packages/gamut/src/Overlay/__tests__/Overlay-test.tsx, packages/gamut/src/Overlay/index.tsx
I made a change towards the end of the previous modal updates that broke clicking outside of an overlay.
The overlay container is the "outside" element you click on, and I moved it inside of the focus-trap.
This wasn't caught by tests because in the test i clicked on the `body` element.
This also fixes the test.
---
=> fix: Overlay click-outside functionality was still not working after previous update

package.json, packages/gamut/CHANGELOG.md
This wasn't happening at the right time, so the updated changelogs weren't being committed.
After digging through lerna, there isn't a great place to put this in the lifecycle without needing to manually add/commit the files, so this seemed to be the easiest way.
=> ci: move changelog generation to commit hook

packages/gamut-labs/src/brand/Testimonial/index.tsx
According to https://www.w3.org/WAI/tutorials/images/decorative/, images adjacent to text that has the same information (in this case the name of the person is next to the avatar) should be considered decorative and therefore not have alt tags. This came up in a test.io bug recently. (Linked in the JIRA ticket).
=> fix: remove alt text on Testimonial avatars

packages/gamut/src/Form/Checkbox.tsx, packages/gamut/src/Form/Input.tsx, packages/gamut/src/Form/Radio.tsx, packages/gamut/src/Form/Select.tsx, packages/gamut/src/Form/TextArea.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/__tests__/GridFormCheckboxInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/__tests__/GridFormFileInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/__tests__/GridFormRadioGroupInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/__tests__/GridFormSelectInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/__tests__/GridFormTextArea-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/__tests__/GridFormTextInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/__tests__/GridFormInputGroup-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
This PR adds the ability to add an optional Id prop to GridFormInputGroups, in order to resolve accessibility issues that arise with pages with multiple grid forms. 
This initially surfaced on the Business Landing Page where there are two forms, each of which contains an "email" field. This causes the accessibility tests to break, since the ID of both these forms was created from the required name prop. Both of the forms on this page submit to HubSpot, which requires the name be related to the field name, thus locking us in this situation of duplicate ids.
=> feat: add Id props for GridFormInputGroups

packages/gamut/src/GridForm/__tests__/GridForm-test.tsx, packages/gamut/src/GridForm/index.tsx, packages/gamut/src/GridForm/types.ts
This PR allows unique IDs to be passed down using the GridFormFields. Earlier we only allowed GridFormInput to pass down unique IDs, and this change will allow for users to solve accessibility issues directly from the top-level api.
=> feat: add ID prop to BaseFormField and test that GridForm renders them

packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx
Related to https://codecademy.atlassian.net/browse/GROW-1628
We need more control in the consumer over how refs get built for GridForm custom inputs. This change makes it so that the consumer of gamut will have to set up a ref on the html element within the field's render method.
=> feat(Gamut)!: :fire: removed register from custom input useEffect

packages/gamut/src/Alert/__tests__/Alert-test.tsx, packages/gamut/src/Alert/index.tsx, packages/styleguide/stories/Core/Molecules/Alert.stories.mdx
I'd like to use one on the /forum_requestions/ Rails-to-React port for the permanent 'go away' message on the top of the page.
=> feat(Gamut): Allowed Alerts to not be passed an onClose callback

packages/gamut/src/GridForm/GridFormInputGroup/styles.module.scss
Signed-off-by: Aaron Foster Breilyn <afbreilyn@codecademy.com>
This PR fixes the issue where an invisible text or checkbox label did not appear to a11y tests.
=> fix: change FormGroupLabel styles for accessibility

packages/gamut/src/Video/index.tsx, packages/styleguide/stories/Core/Molecules/Video.stories.mdx
videos that are in the VideoModal component don't let you tab into them unless you manually set the iframe's tabindex to 0
this PR adds an optional onReady prop where for VideoModals the Video can pass in a function like this `document.getElementsByTagName('iframe')[0].tabIndex = 0;` to fix the accessibility issue
---
=> fix(Video): add onReady prop

packages/gamut/src/Video/index.tsx
fix Video component - it is trying to call onReady(player) when there is no onReady prop which causes an error
---
=> fix(Video): check if onReady exists

packages/gamut/src/Form/FormError.tsx, packages/gamut/src/Form/styles/FormError.module.scss
The Stride team had to do an override to get the form errors in checkout-v3 to be red. Design was on board to default all form errors to red. This pr does that. (and now we can remove the overrides from the monolith)
=> style: set default red color for form errors

packages/styleguide/stories/Core/Foundations/Colors/Colors.stories.mdx
I think I screwed up the SCSS variable prefix when I reworked these, this fixes that.
JIRA: GM-50
=> chore(Styleguide): Fixes bad prefix on brand colors [GM-50]

packages/gamut/src/Form/styles/FormError.module.scss, packages/gamut/src/Form/styles/Select.module.scss, packages/gamut/src/Form/styles/TextArea.module.scss, packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/__tests__/GridFormCheckboxInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/__tests__/GridFormFileInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/__tests__/GridFormRadioGroupInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/__tests__/GridFormSelectInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/__tests__/GridFormTextArea-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/__tests__/GridFormTextInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/TestHelper.tsx
Darkens red error colour to be accessible on a white background. Passes the 'required' html attribute to input elements, so they can be rendered as such.
=> fix: accessibility changes

.circleci/config.yml, package.json
1. removes changelog generation from `lerna publish`
2. adds a separate changelog generation task after publish in CircleCI
---
=> ci: make changelog generation more explicit [WEB-939]

packages/gamut/src/Accordion/__tests__/Accordion-test.tsx, packages/gamut/src/Accordion/index.tsx, packages/gamut/src/AccordionButton/index.tsx, packages/gamut/src/AccordionButton/styles.module.scss, packages/styleguide/stories/Core/Molecules/Accordion.stories.mdx
A few scattered additions / improvements to `<Accordion>`:
* We don't use the `"plain"` theme yet anywhere in the monolith, but its primary consumer in [/about/careers](https://codecademy.com/about/careers) doesn't set `outline`. Removed it here.
* Added font size adjustments to match what's in the careers page too...
* Added a `size` prop that defaults to `"normal"` but can be set to `"large"` to make the thing increase font and icon size.
* Large accordions use the heading font with different line-height than body - hence the `padding-top`...
* Marked `onChange` as optional, since it is.
=> feat(Accordion): Accordion alignment: 'large' size; no outline in plain

packages/gamut/src/Accordion/__tests__/Accordion-test.tsx, packages/gamut/src/AccordionButton/index.tsx
Unlike the fancy new gamut-icons package, it doesn't add an aria-labelledby with an automatic titleId -- so it won't violate aXe checks with multiple identicle IDs when used in multiple places on a page.
Sorry @codecaaron 😄  -- revert of just the one change from #870.
=> fix: Used old ChevronDownIcon in AccordionButton

packages/gamut/src/Button/index.tsx
Buttons with `fitText` are broken on this version.  I thought I had this as a noop but apparently I didn't delete some code.
=> fix(Button): Add back fitText classname mapping

package.json, packages/gamut-icons/babel.config.js, packages/gamut-labs/babel.config.js, packages/gamut/babel.config.js, packages/gamut/package.json, packages/gamut/src/Card/CardShell.tsx, yarn.lock
Added a babel plugin that will automatically change the code for anonymous function components so they get display names.
Plugin link: https://github.com/patrykkopycinski/babel-plugin-react-anonymous-display-name#readme
Example:
```js
const MyComponent = React.memo((props) => {
return (
<div>{props.children}</div>
)
})
// becomes:
const MyComponent = React.memo(function MyComponent(props) {
return (
<div>{props.children}</div>
)
})
```
=> fix: Automatically add display names to anonymous function components

packages/gamut/src/Button/styles/index.module.scss
When buttons are given a custom `height`, they should still center text.
codecademy.explore/try has a weird big button right now. 😢
=> fix(Button): Added align-items: center to Button styles

packages/gamut/src/Tabs/Tab/index.tsx, packages/gamut/src/Tabs/Tab/styles.module.scss, packages/gamut/src/Tabs/TabList/styles.module.scss
- ~[ ] Related to Abstract designs:~ _(informal conversation with Yassine)_
`ButtonBase` removes the default `outline` from active/focused buttons, which is not a behavior we want here. The only button style I can tell was being used from it was the white background.
=> fix(Tab): Used default outline for active and focused Tabs

packages/gamut-styles/utils/mixins/_responsive.scss
While participating in the hackathon, we realized that there is a syntax error in _responsive.scss that makes some webpack loaders fail. We've resolved this locally for the sake of the hackathon, but wanted to start a real fix as well.
AFAICT this is a straightforward syntax error, but there may be some downstream clients that relied on this behavior; are there known areas to test for this change?
=> fix: add in missing equals sign

packages/gamut/src/Toggle/index.tsx, packages/gamut/src/Toggle/styles/index.module.scss
This PR cleans up the rem sizing for the track and thumb (some of the decimals go out 2+ places). Converting rem to the px-rem() function as per Aaron's suggestion in [PR 885](https://github.com/Codecademy/client-modules/pull/885)
=> fix(Toggle): Convert rem to px-rem()

packages/gamut/src/Markdown/__tests__/Markdown-test.tsx, packages/gamut/src/Markdown/libs/overrides/MarkdownAnchor/__tests__/MarkdownAnchor-test.tsx, packages/gamut/src/Markdown/libs/overrides/MarkdownAnchor/index.tsx
This came from a cleanup I'd done post-checking in #883.
=> fix: MarkdownAnchor should still render children

.circleci/config.yml
Switches to a canary release on next which should produce a `x.x.x.next.0` version also removes the github release option.
=> chore(Config): Switch to canary release on next branch

packages/gamut-icons/src/svg/check-icon.svg
Per @JoshuaKGoldberg 
> Unrelated to any current discussion, I’m getting some a11y failures in a branch 
> that uses the newest check-icon from gamut-icons… example page failing aXe: https://pr-18690.monolith.dev.codecademy.com/business
> ...
> The issue is that the ID for all of them is the same, generated from clip0
=> fix(CheckIcon): Remove erroneous clip-path

packages/styleguide/stories/Core/Molecules/Accordion.stories.mdx, packages/styleguide/stories/Deprecated/Atoms/IconDeprecated.stories.mdx
Fixes https://app.circleci.com/pipelines/github/Codecademy/client-modules/6375/workflows/1746b445-515b-4fdc-9284-a5a9d89d06f2/jobs/37030/parallel-runs/0/steps/0-108:
```
WARN Module build failed (from ./node_modules/babel-loader/lib/index.js):
WARN SyntaxError: /home/circleci/repo/packages/styleguide/stories/Core/Molecules/Accordion.stories.mdx: Identifier 'accordion' has already been declared (86:13)
WARN 
WARN   84 | accordion.parameters = { storySource: { source: '<Accordion expanded={expanded} size={select(\'Size\', [\'normal\', \'large\'], undefined)} theme={select(\'Theme\', [\'blue\', \'plain\', \'yellow\'], undefined)} top=\"Click me!\">\n      Hidden treasure!\n    </Accordion>' } };
WARN   85 | 
WARN > 86 | export const accordion = (() => {
WARN      |              ^
WARN   87 | …
```
=> fix: AccordionArea typo in docs

packages/enzyme-helpers/rollup.config.js, packages/enzyme-helpers/test/TestComponent.js, packages/enzyme-helpers/test/main-test.js, packages/eslint-config/index.js, packages/gamut/src/Accordion/index.tsx, packages/gamut/src/AccordionArea/__tests__/AccordionArea-test.tsx, packages/gamut/src/AccordionArea/index.tsx
Adds [`import/no-default-export`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-default-export.md) per our [RFC](https://www.notion.so/codecademy/Migration-Default-to-Named-Exports-529170b17a3d41a4add35ced6b5ed181).
Adds `import/no-default-export` as an error, and fixes the last `export default` I'd sneakily left in the codebase to check that it runs.
See https://app.circleci.com/pipelines/github/Codecademy/client-modules/6423/workflows/28081b01-ea3f-4ab3-9621-9b7e6a2771d5/jobs/37300 for a workflow showing the rule does, indeed, produce errors when it should.
=> feat!: Added import/no-default-export to ESLint config

packages/gamut/src/RadialProgress/index.tsx
Introduced by me in #943. ~The inner circle shouldn't have `r=45`, just the outer.~ No, that wasn't the solution; it just moved the inner circle counterclockwise. Switching to assuming an empty offset of 280 and full offset of 0 seems to have done the trick...
=> fix: RadialProgress inner circle shouldn't show at value 0

packages/gamut-labs/src/brand/Byline/index.tsx
There's an a11y bug with the Byline (used within the Testimonial) discovered during a Test.IO A11y test that was run on the Back to School Campaign Page.
> **Steps**
> 
> 1. Open https://codecademy.com/student-center
> 2. Tab to Tyler V. quote
> - Expected result: I expect to hear the "Tyler V. Student.... "
> - Actual result:  I hear "First name Last name Occupation..."
> The screen reader read the aria-label in this
> `<span aria-label="First Name">Tyler</span>`
> 
**Video of Bug:** https://uploads.test.io/uploads/bug_attachment/file/3732204/cc1cde2f-eabf-40b6-a610-0bb5db697286.mp4
Remove aria-labels all-together.
~Append the value of `firstName`, `lastName`, `occupation`, and `company` to their respective `aria-labels`.~
=> fix: Byline aria-label a11y bug

packages/gamut/src/ButtonBase/__tests__/Button-test.tsx, packages/gamut/src/ButtonBase/index.tsx
Just a failsafe for when a Button component has an `href` and `target="_blank"` but no `rel` prop. Noticed we were doing this in Markdown but not here.
=> fix(Button): Add rel by default if none is set when target=_blank

.github/pull_request_template.md
We don't use Abstract as much anymore. Lots of Figma.
=> docs: remove 'Abstract' mention from PR template

packages/gamut-system/src/core/system/__tests__/system-test.ts, packages/gamut-system/src/core/system/index.ts, packages/gamut-system/src/props/colors.ts, packages/gamut-system/src/styleTemplates/createStandardStyleTemplate/__tests__/createStandardStyleTemplate-test.ts, packages/gamut-system/src/styleTemplates/createStandardStyleTemplate/index.ts, packages/gamut-system/src/types/config.ts, packages/gamut-system/src/types/properties.ts
`color` as a propname can conflict with some HTML / Intrinsic attributes.  This changes the propName at the API level to be more declarative as `textColor` while still using the correct css property.
Added:
- An extra field to config object to specify the correct property and type. 
- Updated standard config to use the property if available and default to propName if not configured.
- Test to ensure that this forwarding works.
=> fix(system): Fix color property WEB-1112

packages/gamut/src/GridForm/index.tsx
`GridForm`'s `Values` is the vague description of what could possible exist as the submit value for a form: an object whose keys are strings and values are `boolean`, `string`, `undefined`, or (in the case of a file input), `FileList`. The description before was missing that `FileList` input type.
=> fix: corrected GridForm Values to allow FileList

packages/gamut/src/Button/styles/variables.scss, packages/styleguide/stories/Core/Atoms/Button/Button.stories.mdx, packages/styleguide/stories/Core/Atoms/Button/helpers.tsx
Small change to prevent any weird workarounds with buttons and `styled` decorations due to `theme` being a reserved prop.
Note: this only adds the colors and no other style changes until all are finalized.
=> feat(Button): Add stop gap theme keys for common new button colors  WEB-1126

packages/gamut-styles/src/variables/colors.ts, packages/gamut-styles/utils/variables/_colors.scss
We mentioned this in our Gamut biweekly. These are the proper colors now.
=> feat: tweaked red and green theme colors per design updates

packages/gamut-system/README.md, packages/gamut-system/docs/customization.md, packages/gamut-system/docs/getting-started.md, packages/gamut-system/docs/responsive.md, packages/gamut-system/docs/variants.md, packages/gamut-system/src/core/system/__tests__/emotion-components-test.tsx, packages/gamut-system/src/core/system/__tests__/system-test.ts, packages/gamut-system/src/core/system/index.ts
Like we talked about on Slack: adjusts the top-level API a bit to be fluent, so we don't have to `as` cast with a `ThemedSystem`.
=> feat: used withTheme and create APIs for system

packages/gamut-labs/src/brand/ProLogoAlt/__tests__/ProLogoAlt-test.tsx, packages/gamut-labs/src/brand/ProLogoAlt/index.tsx, packages/gamut-labs/src/brand/index.ts, packages/styleguide/helpers/selectableColors.ts, packages/styleguide/stories/Labs/Brand/Atoms/ProLogo.stories.mdx, packages/styleguide/stories/Labs/Brand/Atoms/ProLogoAlt.stories.mdx
This creates a new version of our Pro Alt Logo that allows dev to choose the inner text color. 
Previously this effect had been achieved by loading in an image (as it is [here](https://www.codecademy.com/learn/paths/computer-science)). This logo also should improve the load time of page.
=> feat: ProAltLogo

packages/tracking/package.json, yarn.lock
Defining runtime dependency for @codecademy/tracking
Saw error in consumer build system:
```
'@babel/runtime/regenerator' is imported by node_modules/@codecademy/tracking/dist/user.js, but could not be resolved – treating it as an external dependency
No name was provided for external module '@babel/runtime/regenerator' in output.globals – guessing '_regeneratorRuntime'
```
=> fix: Add a runtime dependency

packages/gamut-labs/src/experimental/Popover/index.tsx, packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap, packages/gamut/src/index.tsx
It was brought to my attention that the import for BodyPortal was causing an error:
Error: Can't resolve '../../../../gamut/src/BodyPortal' in '/Users/cassiespain/Desktop/cc/Codecademy/node_modules/@codecademy/gamut-labs/dist/experimental/Popover'
I've updated to import BodyPortal from '@codecademy/gamut' and exported in the gamut/src/index file for it to work.
=> fix: updated export/import bodyportal

packages/gamut-labs/src/brand/LandingPageSection/CTA.tsx, packages/gamut-labs/src/brand/LandingPageSection/Description.tsx, packages/gamut-labs/src/brand/LandingPageSection/Title.tsx, packages/gamut-labs/src/brand/LandingPageSection/index.ts, packages/gamut-labs/src/brand/index.ts, packages/styleguide/stories/Labs/Brand/Organisms/LandingPageSectionCTA.stories.mdx, packages/styleguide/stories/Labs/Brand/Organisms/LandingPageSectionDescription.stories.mdx, packages/styleguide/stories/Labs/Brand/Organisms/LandingPageSectionTitle.stories.mdx
These are just some of the smaller entities that be used in a number of Landing Page Section organisms.
=> [REACH-344] feat: Start on the Landing Page Section area in Gamut

packages/gamut-icons/src/svg/arrow-chevron-down-filled-icon.svg
remove fill and stroke color from ArrowChevronDownFilledIcon svg so that it can change color based on css color property
needed for Codecademy-engineering/Codecademy#19905
=> fix: remove fill color from ArrowChevronDownFilledIcon

packages/webpack-config/package.json, yarn.lock
Danger zone: 
https://github.com/Codecademy/client-modules/commit/f1a68de07fea75de02ab7f57a05108df01191397#diff-aa216219785e041bae3a683a8048929e68931dbbe3249ee17fb35f56c91197a5
=> fix(Webpack): Revert terser and loader dependency bumps

packages/styleguide/stories/Core/Foundations/Utilities/Utilities.stories.mdx
Noticed a small typo in the imports while looking at `Utilities` in gamut so this PR fixes the minor typo.
Change: `@codecadem/gamut-styles` > `@codecademy/gamut-styles`
=> docs: Fixing import typo in utils docs

packages/styleguide/stories/Core/Atoms/Markdown/Markdown.stories.mdx
Recently I was working on a ticket to override some tags from the Markdown gamut component. Upon accessing the storybook, I was confused because the 'Show Code' part looked like this:
(note the `function noRefCheck()`). To complete my task, I had to dig into the `Markdown` source code & look at over places where overrides were used.
This PR fixes the `Show Code` panel & also adds a few more examples to make it clearer how to override things in the Markdown component. 
The formatting is a bit funky, but it now looks like:
When you are ready to merge to main and publish your changes, use the "squash and merge" button in GitHub, and follow the [PR Title Guide](https://github.com/Codecademy/client-modules#pr-title-guide) to format your PR title and write your PR merge description. …
=> feat(markdown): update overrides storybook for clarity

packages/eslint-config/index.js, packages/gamut-labs/src/experimental/Text/index.tsx, packages/gamut-styles/src/index.ts, packages/gamut-styles/src/theme.tsx, packages/gamut-system/src/types/config.ts
This resolves a significant performance issue with the theme shape being recreated every time it was referenced.  By changing these to interfaces the reference to the interface is preserved instead of copied resulting in a massive reduction in size both in memory and outputted file.
`system.d.ts`:  257556 => 41061 | 84% reduction
`Text.d.ts`:  53751 => 4924 | 91% reduction
=> fix(System): Typescript memory performance fixes

packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap, packages/gamut/src/Button/index.ts
@saghdaey is seeing _`Cannot find 'ButtonProps'`_ errors locally in a `yarn link`ed gamut's `Button/index.js`. How unfortunate. I'm guessing this is some Babel/TypeScript quirk of accidentally printing the import to a JS file even though it's, in practice, only a type system import. It should go away with a `type` only import to tell Babel/TypeScript to not print out the export in JS land.
=> fix: used type-only export for ButtonProps

packages/gamut-styles/src/system.ts, packages/gamut-styles/src/theme.tsx, packages/gamut-styles/src/utilities.ts, packages/gamut-styles/src/variables.ts, packages/gamut-styles/src/variables/colors.ts, packages/gamut-styles/src/variables/index.ts, packages/gamut-styles/src/variables/shadows.ts, packages/styleguide/stories/Core/Foundations/Colors/Colors.stories.mdx
- Flattened color swatch values to be accessible by a single key on the color object: `${color}-${weight}`
- Add our 5 box shadows to the theme.
- Adds spacing scale to grid-gap system functions for future use.
- Clean up relic files.
=> chore(Styles): Assorted theme / variable additions

packages/gamut-system/src/types/config.ts
System `ThematicProps` failed when the theme key was a constructed const for some reason.
```tsx
const flatSwatches = {} as const;
const trueColors = {} as const;
export const colors = {
...flatSwatches,
...trueColors,
} as const;
```
Narrowed `AbstractTheme` keys to `readonly` and it somehow fixed it?  Not sure the TS reason why, behavior with interfaces is something I'm not super familiar with, rules seem much different.
=> fix(system): Fix theme type inference for some keys

packages/gamut-labs/src/experimental/Popover/__tests__/Popover-test.tsx, packages/gamut-labs/src/experimental/Popover/index.tsx
This adds in a little bit of the work we'd worked on in #846: specifically the usage of the focus trap. I've been trying to get the Reach UI components because they're quite a bit more accessible, but won't have them ready in time for the engagement team being able to launch this week.
There are two parallel investigations I tried out today:
* [Popover](https://github.com/reach/reach-ui/tree/develop/packages/popover) (#1151): the popover inside Reach UI is actually exactly what we want [Slack link](https://codecademy.slack.com/archives/CQ98K8PT6/p1605312553042200) _but_:
* It doesn't expose a reasonable API for styling the insides differently based on the computed position style
* It's not meant for public use: https://github.com/reach/reach-ui/issues/506
* [Menu …
=> feat: added focus trap to Popover

packages/eslint-config/index.js
Disable deprecated "jsx-a11y/accessible-emoji" lint rule.
For more context: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/627
=> style: disable jsx-a11y/accessible-emoji rule

packages/gamut-labs/src/brand/LandingPageSection/LandingPageHero.tsx, packages/gamut-labs/src/brand/LandingPageSection/Title.tsx, packages/gamut-labs/src/brand/LandingPageSection/__tests__/LandingPageHero-test.tsx, packages/styleguide/stories/Labs/Brand/Organisms/LandingPageHero.stories.mdx
applying posthumous feedback from https://github.com/Codecademy/client-modules/pull/1161, along with some other small tweaks
- default `imgAlt` to `""`
- accept `isPageHeading` prop and apply it to `LandingPageTitle`
- use markdown in story instead of html
- format tsdoc comments more goodly
- switch to RTL for tests, make them less bad
=> fix: default img alt to "", accept isPageHeading, update tests

packages/gamut-labs/src/brand/LandingPageSection/LandingPageFeature.tsx
Add `flex: 1` to feature items so they all appear the same size.
=> fix: update flex items to grow and shrink evenly in landing page features section

packages/gamut/src/ProgressBar/index.tsx
testio came back to say that the Progress Bar should not say "Progress: 100%, group" on voiceover
this PR changes it to say "Progress: 100%, figure" instead, because it is a more apt description
the testio tester suggested using role="text" so that the voiceover would just say "Progress: 100%" but there is no standard way to do this effectively on all browsers, so instead we'll just have the role be more descriptive (i.e. "figure" instead of "group")
~~previously the VoiceOver would say "Progress: 100%, group" on the progress bar, but this PR changes it to say "Progress: 100%" (without the "group")~~
~~it also needs the eslint-ignore because "text" is not officially an allowed aria role type -- even though it was proposed it was not accepted, but people use it for this workaround~~
~~see …
=> fix: prevent VO from saying "group" for ProgressBar

packages/tracking/src/__tests__/track.spec.ts, packages/tracking/src/__tests__/user.spec.ts, packages/tracking/src/track.ts
static_sites has logic to add the query params to the tracking call.  When I was porting this, I originally assumed this was irrelevant, as all necessary data would be based in as FormData props.  This was an incorrect assumption.  There is a weird quirk how the monolith uses an after hook to detect utm params and add them to the users session.  However, if someone hits a third party site first, then because rails didn't process the request the UTM params never get tracked.  This seems to be overcome in static-sites by adding the original pages query params to all tracking calls, that way the tracking call itself allows rails to detect UTM params.
Note, the little hack will not scale if we move tracking to its own library.  We should probably have some standardized session store for …
=> fix: Add query params to tracking calls

packages/gamut-styles/src/cache.ts, packages/gamut-styles/src/cache/index.ts, packages/gamut-styles/src/cache/stylisPlugins/focusVisible.ts, packages/gamut-styles/src/cache/stylisPlugins/index.ts
Emotion focus-visible support 🚀 
Authors: @dreamwasp @JoshuaKGoldberg @codecaaron 
* Adds simple plugin to translate all `:focus-visible` pseudo selectors to the appropriate polyfill data-attribute on emotion components.
Using emotions processor https://stylis.js.org/
A few fun things:
- All elements are mutable so we must overwrite the values.
- It's unclear why the API is "prop", but we're still investigating.
=> feat(focus-visible): Add stylis plugin for focus-visible support WEB-1148

packages/gamut-system/src/core/createHandler/index.ts, packages/styleguide/.storybook/addons/system/enhancers.ts, packages/styleguide/.storybook/components/PropsTable/index.tsx
Found a better native way to do this with props tables.
* Utilizes Storybook ArgsTable categories for system props.  Adding the correct groups through the addon enhancer.
* Ensures `theme` and `as` are categorized under a specific area.
=> fix(Styleguide): Add sectioning in a nice way

packages/gamut-labs/src/brand/Logo/index.tsx
Changed `Logo`'s `defaultProps` to work with `styled(Logo)` in consumers.
Without this change, using `styled(Logo)` with Emotion gives:
```
Argument of type 'typeof Logo' is not assignable to parameter of type 'ComponentClass<LogoProps, any>'.
```
=> fix: Logo's defaultProps need to be of type LogoProps

packages/gamut-styles/src/variables/colors.ts, packages/gamut/src/Button/FillButton.tsx, packages/gamut/src/Button/shared.ts, packages/styleguide/stories/Core/Atoms/Button/Button.stories.mdx
Correct `FillButton`'s hover color in dark mode to be a duller yellow instead of a hyper.
Also adds a link to the Figma doc in Storybook.
=> fix(FillButton): corrected hover styles on FillButton in dark mode

packages/gamut/src/Markdown/__tests__/Markdown-test.tsx, packages/gamut/src/Markdown/index.tsx
Adds an `onAnchorClick` prop to the Markdown component for passing down to `<a/>` tags.
=> feat(Markdown): Add onAnchorClick prop

packages/gamut-labs/src/landingPage/Description.tsx, packages/gamut-labs/src/landingPage/Feature.tsx, packages/gamut-labs/src/landingPage/PageFeatures.tsx, packages/gamut-labs/src/landingPage/PageHero.tsx, packages/gamut-labs/src/landingPage/PagePrefooter.tsx, packages/gamut-labs/src/landingPage/__tests__/Hero-test.tsx, packages/gamut-labs/src/landingPage/types.tsx, packages/styleguide/stories/Labs/LandingPage/Organisms/PageHero.stories.mdx
Adds `onAnchorClick` to the `BaseProps` and for the `Feature` component to allow passing an `onAnchorClick` callback for descriptions rendered with Markdown.
1. https://5fd7bb7be9996200bdccaefe--gamut-preview.netlify.app/storybook/?path=/docs/labs-landingpage-organisms-pagehero--with-cta
2. Open Console
3. Click on `Rob Thomas of Matchbox Twenty `
4. See message output
=> feat(Landing Page Components): Allow passing callback for link clicks inside Markdown

packages/gamut-labs/src/landingPage/PagePrefooter.tsx
data-testid is helpful for e2e smoketesting, and we're already passing the prop in the dynamic renderer (it just isn't being applied lol woops)
=> fix: actually use testId prop in prefooter

packages/gamut-illustrations/src/index.ts
Also export the gamut-illustrations types file (so, `IllustrationProps`) so consumers can import it.
One last thing; I noticed it'd be easier for me to set up the confirm page illustrations...
=> feat: also export types from gamut-illustrations

packages/gamut-illustrations/package.json
Bumped gamut-system dependency in gamut-illustrations to the latest, 0.2.1.
Pretty sure this is some kind of odd timing issue, where the automation didn't bump the system version as needed.
=> fix: corrected gamut-system dependency in gamut-illustrations

packages/gamut/src/Button/ButtonInner.tsx, packages/gamut/src/Button/FillButton.tsx, packages/gamut/src/Button/IconButton.tsx, packages/gamut/src/Button/StrokeButton.tsx, packages/gamut/src/Button/TextButton.tsx, packages/gamut/src/Button/shared.ts, packages/styleguide/stories/Core/Atoms/Button/Button.stories.mdx, yarn.lock
Added a `size` prop for buttons that defaults to `"normal"` but can also be `"small"`.
smol:
=> feat: added size prop for buttons

packages/gamut/src/AccordionButton/styles.module.scss, packages/gamut/src/Alert/styles.module.scss, packages/gamut/src/Banner/styles.module.scss, packages/gamut/src/Button/ButtonOutline.tsx
Used `:focus-visible` instead of `:focus` in what feels like the remainder of relevant buttons that should have it.
That's:
* The new buttons (amusing that they're getting it after the old SCSS ones)
* Accordion buttons
* Alert buttons
* Banner buttons
=> feat: added focus-visible to newer buttons and similar

packages/gamut-labs/src/landingPage/PagePrefooter.tsx, packages/gamut/src/FlexBox/Container.tsx
This reverts the change to add an explicit `testId` prop to `Container`, since it actually already supports `data-testid`.
=> fix: revert "feat: add testId prop to Container (#1242)"

packages/gamut-labs/src/experimental/Popover/__tests__/Popover-test.tsx, packages/gamut-labs/src/experimental/Popover/index.tsx
- Replaced offset prop on Popover component with verticalOffset and horizontalOffset 
- These two new props will allow clients to shift the Popover vertically and horizontally from the source
=> feat: add vertical and horizontal offsets to the popover component

packages/gamut-icons/src/svg/arrow-chevron-down-filled-icon.svg
This icon had a perma white background, which was probably some export artifact.  This removes it and adds some fill color forwarding.
* removes erroneous white rectangle from caret icon.
=> fix(icons): remove rectangle from filled caret icon

packages/gamut/src/Toggle/index.tsx
Adds support for a `className` prop in the `<Toggle>` component.
Adds support for a className prop to the Toggle component.
=> feat(Toggle): adds a className prop to the Toggle component

packages/gamut/src/Markdown/index.tsx
This default prop wasn't necessary because `undefined` in an onClick prop is equivalent to not setting the prop at all (as far as i know, it might not be 100% equivalent).
Fixes unnecessary re-renders caused by a default function prop being applied to markdown anchors.
=> fix(Markdown): prevent re-renders caused by default prop

packages/gamut/src/Button/IconButton.tsx
Found a bug in IconButton while pairing with @codecaaron. 
- updated children prop to be optional
=> fix(IconButton): make children prop optional

packages/gamut/src/Button/ButtonInner.tsx
Added font-smoothing CSS to buttons for a lighter text appearance.
=> fix: added fontSmoothing to buttons

packages/styleguide/.storybook/components/Page/index.tsx
A tiny change to appease my visual OCD.
* Swaps color to storybook native.
=> fix(Storybook): Update meta links to storybooks standard color

packages/gamut-labs/src/landingPage/Description.tsx, packages/gamut-labs/src/landingPage/Feature.tsx
Adjust margin-top of descriptions in 2 places within landing page components, per design feedback.
=> fix: landing page descriptions margin-top adjustments

packages/gamut-styles/core/_reboot.scss
Our new buttons were getting an extra outline.
* Ensure the outline only shows up for `focus-visible`
=> fix(styles): Default button focus styles to focus-visible

packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/SharedStyles.tsx, packages/gamut-labs/src/experimental/AppHeader/index.tsx, packages/gamut-labs/src/experimental/index.ts, packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
Changes GlobalHeader components focus outline to navy and add GlobalHeader to gamut-labs exports.
=> fix(GlobalHeader): Change focus outline color and add export

packages/gamut-labs/src/landingPage/Feature.tsx, packages/gamut-labs/src/landingPage/PageFeatures.tsx, packages/gamut-labs/src/landingPage/__tests__/Feature-test.tsx, packages/gamut-labs/src/landingPage/__tests__/FeaturesSection-test.tsx, packages/styleguide/stories/Brand/Organisms/PageFeatures.stories.mdx
Allow the PageFeatures component to render in a grid.
=> feat(PageFeatures): Allow the PageFeatures component to render in a grid

packages/gamut/src/Overlay/index.tsx
Guards the overflow effect in `Overlay` with a `typeof document !== "undefined"`.
We're soon not going to have access to a JSDOM document in SSR on the monolith.
=> fix: guard against undefined body in Overlay

packages/gamut/src/ButtonDeprecated/styles/index.module.scss
I noticed some errors for this property in our new Next.js app, not really a bug or anything, just a noisy warning we'll likely start seeing more if we upgrade Sass.
=> fix: remove deprecated elseif scss syntax

packages/gamut-tests/.npmignore, packages/gamut-tests/package.json
The `.npmignore` is missing so the published package doesn't have a `dist/`.
I don't know that the `module` is necessary but figured we might as well.
=> fix: added npmignore and module field for gamut-tests

packages/tracking/src/types.ts
We decided against adding tracking to the FE since it would create difficulties avoiding double-tracking, so this is now tech-debt.
=> feat(tracking): Add a fullstory boolean to TrackingOptions type --REVERT

packages/gamut/src/AccordionButton/styles.module.scss
We pretty much exhausted all other fixes for this, likely should have just been doing this for all style overrides of other gamut components.
Bumped specificity for `AccordionButton` component styles to always override `ButtonDeprecatedBase` styles.
=> fix(AccordionButton): bump specificity of accordion button styles

packages/gamut-labs/src/landingPage/Feature.tsx, packages/gamut-labs/src/landingPage/Title.tsx
Updates `Text` font sizes within landing page components to start at `base` instead of `xs`.
Previously, the font sizes specified only got applied at `xs` and larger so on mobile size screens, the font was super large or small and wonky. This change applies to the `Title` component used as the main title in the `PageHero`, `PageFeatures`, `PagePrefooter`, and `PageVideoGallery` components, and the subtitle and stats text within the `PageFeatures` component.
Before:
After:
=> fix: update font sizes within LP components at smaller than xs

packages/gamut-labs/src/landingPage/PageFeatures.tsx, packages/gamut-labs/src/landingPage/PageHero.tsx
Reduces column gaps on mobile within the `PageHero` and `PageFeatures` landing page components so they don't overflow.
Previously if you went to https://staging.codecademy.com/about/careers-v2 on mobile, you are able to scroll to the right and can see the value props overflowing. Using dev tools you can see that the grid is the cause and reducing the grid gaps on mobile will resolve this.
=> fix: reduce column gaps on mobile for LP components

packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
We had missed adding "newTab: true" to a few of the app header items that should open in new tabs
all external links should open in a new tab 
ex. forums, chapters, blog, chat
=> fix(GlobalHeaderItems): add new tab true to external links

.github/reviewers.yml, .github/workflows/auto-request-review.yml
Adds github action that will auto assign reviewers to non-draft PRs based on who recently changed the code
=> ci: add auto assign reviewers config

packages/gamut/src/Video/index.tsx
This way the consumer (monolith) won't need to import from react-videoplayer (& we wont need that package in the monolith at all)
https://github.com/codecademy-engineering/Codecademy/blob/develop/webpack/assets/components/VideoModal/index.tsx#L53
Result of debugging with @JoshuaKGoldberg 
- I updated gamut package numbers
- yarn compile in monolith failing bc version of react-videoplayer was different than in gamut
- interim fix was to upgrade monolith version to match what was in gamut https://github.com/codecademy-engineering/Codecademy/pull/22305/commits/5f47b4e379e00a5602242f9e7dcb4cc1bd65e330
-
=> fix(video): include wrapper in type

packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx, packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/types.tsx, packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx, packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx, packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx, packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx, packages/gamut-labs/src/experimental/GlobalHeader/types.tsx
As I'm working on EGG-536 Migrate Monolith to Use the Global Header, I have come across a few small updates needed in client modules. 
I'll mark them here as I go. My plan is to use the alpha build from this PR in the[ monolith branch](https://github.com/codecademy-engineering/Codecademy/pull/22024) to confirm these updates fix the problems I'm seeing there.  I will make sure to keep this branch up to date with main!
- Key on items in the Main Mobile Menu wasn't on the highest element in the list. I made the change to move it up from the app header item to the Flexbox container.  The key issue caused an AnonymousAppHeader unit [test](https://app.circleci.com/pipelines/github/codecademy-engineering/Codecademy/74019/workflows/138d5895-6e87-49e8-8795-9b8bfc6ecbfe/jobs/1155052/tests#failed-tes …
=> fix(global header): for monolith migration work

packages/gamut-labs/src/experimental/index.ts
Addressing [feedback](https://github.com/codecademy-engineering/Codecademy/pull/22024#discussion_r585939943) on my monolith PR to import the AnonHeaderVariant from GlobalHeader instead of declaring a new type "Variant" in the monolith's App Header
In the [PR i just merged](https://github.com/Codecademy/client-modules/pull/1451), I forgot to export the GlobalHeader/types file so came across an error when trying to use the new type in my monolith feature branch
=> fix(global header): export global header types 

packages/gamut-system/package.json
I changed 
```json
"lodash": "^>=4.0.0"
```
`=>`
```json
"lodash": "^4.0.0"
```
Kept seeing these warnings in static sites and monolith yarn install logs despite [`"lodash": "^4.17.19",`] in the monolith's package.json (https://github.com/codecademy-engineering/Codecademy/blob/develop/package.json#L64)
```bash
warning " > @codecademy/gamut-system@0.5.0" has incorrect peer dependency "lodash@^>=4.0.0".
```
Sets `^4.0.0` as the version for peer dependency `lodash`.
=> build: Set ^4.0.0 for version of lodash peer dependency

packages/gamut-labs/src/lib/breakpointHooks/index.ts
Marks `useBreakpoint` and similar helpers as deprecated.
This is a feature because I want them to die :hocho: and am excited we're at the point where we can make it happen.
=> feat: deprecated useBreakpoint and friends

packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
Time for some magic.
* Uses headerHeight variable.
=> style(GlobalHeader): Use theme variable for header height

packages/gamut/src/Button/TextButton.tsx, packages/gamut/src/NotificationListNew/NotificationItemNew.tsx, packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
add style for dismiss icon hover
To test: visit [NotificationListNew story ](https://6052261a3b0a95aa51169e73--gamut-preview.netlify.app/storybook/?path=/docs/molecules-notificationlistnew--notification-list-new)in the preview environment; hover over the dismiss icon on the Notification w/ a link. Confirm that you see the clickable area for the dismiss icon on hover. 
*Note: looks faint to me! but I used the styles @codecaaron suggested! Please let me know if I should modify
=> fix(NotificationItemNew): dismiss icon hover

packages/gamut-icons/babel.config.js, packages/gamut-labs/babel.config.js, packages/gamut/babel.config.js, packages/markdown-overrides/babel.config.js, packages/styleguide/.storybook/babel.config.js
Removed redundant react-anonymous-display-name in Babel configs now that it's in the Codecademy preset.
=> chore: remove redundant react-anonymous-display-name in Babel configs

packages/variance/src/__tests__/component-test.tsx, packages/variance/src/__tests__/variance-test.ts, packages/variance/src/core.ts, packages/variance/src/types/props.ts, packages/variance/src/utils/responsive.ts
Change variance's responsive object syntax unscoped key `base`  to `_` to match other frameworks as underscore denotes a behavior that is unrelated to the rest of the keys and saves 3 characters to probable prop bloat.
```tsx
// before
<Box p={{ base: 4, md: 8 }} />
// after
<Box p={{ _: 4, md: 8 }} />
```
=> feat(Variance): base => _ for un scoped style [WEB-1381]

packages/gamut/src/ToolTip/index.tsx, packages/styleguide/stories/Atoms/ToolTip.stories.mdx
Keyboard-only users were not able to activate the tooltip. Screenreader users did not have the tooltip narrated to them.
Change `focus` to  `focus-within` & adds `aria-live: polite` for ToolTip contents.
Removes storybook comment on non-clickable elements allowed within.
1. Turn on VoiceOver on Mac (or ChromeVox extension for Chrome/any alternative)
2. https://606dbfd55f00601ac8e7c74b--gamut-preview.netlify.app/storybook/?path=/docs/atoms-tooltip--tool-tip
3. Keyboard nav to over the tooltips
=> fix(ToolTip): A11y Update

packages/gamut/src/ToolTip/index.tsx, packages/styleguide/stories/Atoms/ToolTip.stories.mdx
This was my mistake in moving too fast, but I would love your input on the changes I just merged as part of
https://github.com/Codecademy/client-modules/pull/1604.
This PR reverts Codecademy/client-modules#1604
=> fix(ToolTip): Revert A11y Update

packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CompanyLinks.tsx, packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/SocialMediaLinks.tsx
Fixes a misplaced `key` prop in `SocialMediaLinks` and correctly wraps its `ul` with an `li` inside the parent `ul`.
Followup to https://github.com/Codecademy/client-modules/pull/1598 from https://app.circleci.com/pipelines/github/codecademy-engineering/Codecademy/81248/workflows/ee4c9bb0-bc7d-4731-aa5d-cb628eb927f2/jobs/1269958 CI failures (I'd made changes late in the PR that broke the monolith).
=> fix: accessibility and key violations in GlobalFooter

package.json, packages/gamut-kit/package.json, packages/gamut-styles/package.json, yarn.lock
Bumps `component-test-setup` to 0.2.4 in all packages.
Brings in https://github.com/Codecademy/component-test-setup/pull/12 so I can use it in the monolith.
=> chore: bump component-test-setup to 0.2.4

packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/index.tsx
Fixes the smallest size resolution for the GlobalFooter being responsive.
The bug only reproes on small mobile devices like Pixels. It doesn't repro if you just shrink the browser viewport, it actually has to emulate mobile device. 😫 
Shoutout to Amy from finance for forwarding a report to us! 🙌
=> fix: used _, not xs, for lowest size in GlobalFooter

packages/gamut-labs/src/PageSection/index.tsx
This just adds a `marginTop={16}` to the footer of the `PageSection` component so it's not right up against the content of the section.
This is to support the following design for the Profiles page, but should be applicable to every usecase:
=> fix(PageSection): Adding margin-top to footer of PageSection

package.json, packages/gamut-kit/package.json, packages/gamut-styles/package.json, yarn.lock
Bumps `component-test-setup` to 0.2.5 in all packages.
Brings in https://github.com/Codecademy/component-test-setup/pull/15 so I can use it in the monolith.
=> chore: bump component-test-setup to 0.2.5

packages/tracking/package.json
`@codecademy/tracking` was compiling with the 2.X line. We're up to 4.X.
The current version of the package emits `import` statements for Babel runtime helpers that include the root path the build task is running from, including `/circleci/` and such. Oy vey.
=> fix: bump tracking package babel-preset-codecademy to latest

packages/tracking/src/events/track.ts
I'd switched `verbose` to an optional _string_ instead of _boolean_. Sigh.
=> fix: switch tracking 'verbose' type back to boolean

package.json, packages/gamut-kit/package.json, packages/gamut-styles/package.json, yarn.lock
Bumps `component-test-setup` to its latest version, which includes couple of bugfixes.
=> chore: bump component-test-setup to v0.3.1

packages/gamut-labs/src/ListSection/__tests__/ListSection-test.tsx, packages/gamut-labs/src/ListSection/index.tsx
There's a need to track metrics for when the user clicks the Show All / Show Less button in the ListSection component. I'm adding a callback function as a prop that gets called in this situation so we can hook into that functionality.
=> feat(ListSection): Updating ListSection to have a ShowAll/ShowLess click handler prop

packages/eslint-config/index.js, packages/gamut-labs/src/ErrorContents/__tests__/ErrorContents-test.tsx, packages/gamut-labs/src/ErrorContents/index.tsx, packages/gamut-labs/src/index.ts, packages/styleguide/stories/Molecules/ErrorContents.stories.mdx
Disables an annoying rule that conflicts with Prettier.
=> fix: disable react/jsx-one-expression-per-line rule

packages/eslint-config/index.js
Disables the `consistent-return` rule in our ESLint configuration because it's annoying with exhaustive switch statements.
TypeScript already validates strict function return types for us with `strictNullChecks`.
=> feat: disabled consistent-return ESLint rule

packages/gamut-labs/src/DropdownButton/index.tsx
Adds a `shouldForwardProp` to `DropdownButton` so React doesn't forward `isOpen`.
=> fix: add shouldForwardProp to DropdownButton

packages/gamut/src/Dialog/__tests__/Dialog-test.tsx, packages/gamut/src/Dialog/index.tsx
Sets `<Dialog />` body to be `<div/>` instead of `<p/>`.
=> feat: Make Dialog body a <div>

packages/gamut/src/GridForm/GridFormInputGroup/GridFormSweetContainerInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/index.tsx, packages/gamut/src/GridForm/types.ts
The sweet container/honeypot was not applying the label, so accessibility was getting axed.  This fixes that.
=> fix: GridForm Sweet Container - add missing label

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
Paired with Josh to run a performance audit on portal app. One of the findings was missing in the lighthouse report was, missing `rel="noopener"`/`rel="noreferrer"` in the footer links for Google and App store links.
This PR aims to add `rel="noopener"` to the affected components.
=> fix: Google and App store 

packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/__tests__/GridFormRadioGroupInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx, packages/gamut/src/GridForm/types.ts
Currently the label for the GridFormRadioGroupInput has to be a string. We want to let it also be a ReactNode for more flexible labels. However, the label does double duty an aria-label right now so we also need a way to provide the aria-label in this new world of ReactNode labels.
=> feat(GridFormRadioGroupInput): Can use a ReactNode for labels

packages/gamut-labs/src/AvatarChooser/__tests__/AvatarChooser-test.tsx, packages/gamut-labs/src/AvatarChooser/index.tsx
Was incorrectly using `aria-labelledby` instead of `alt` for the `Avatar` component.
=> fix(AvatarChooser): Add alt text to Avatar image

packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/__tests__/GridFormTextInput-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/__fixtures__/renderers.tsx, packages/gamut/src/GridForm/GridFormInputGroup/__tests__/GridFormInputGroup-test.tsx, packages/gamut/src/GridForm/GridFormInputGroup/index.tsx, packages/gamut/src/GridForm/__tests__/GridForm-test.tsx, packages/gamut/src/GridForm/index.tsx, packages/gamut/src/GridForm/types.ts
Reverts Codecademy/client-modules#1815 -- this was breaking Login on the monolith PR envs + locally (never went to prod, thankfully). behavior still live on [penguin](https://penguin.codecademy.com/login)
haven't dug into exactly why but think it's safer to revert this for now so we can ship tomorrow
=> fix: revert "fix: clear errors on input change in GridForm"

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CatalogLinks.tsx
Change the href of the "Beta Content" link in the `GlobalFooter` to point at `/catalog/subject/beta` instead of `/learn/beta-content`
=> feat(GlobalFooter): Update href of 'Beta Content' link to point at hub page

packages/gamut-labs/src/Flyout/index.tsx
Moves the close icon in `Flyout` in by 8px on the top and right to align with Codecademy logo in `LayoutMenu` and fix issue where the x-button sometimes overlaps with the scroll bar
=> fix(Flyout): Move Close Icon Placement

packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
The cc docs designs have the LayoutMenu breakpoint at `md` instead of `lg` screen sizes, so I figured it would be nice to have this be configurable
=> feat(LayoutMenu): add breakpoint prop for configurable layout switching

packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx, packages/gamut/src/GridForm/GridFormInputGroup/__fixtures__/renderers.tsx, packages/gamut/src/GridForm/GridFormInputGroup/index.tsx, packages/gamut/src/GridForm/index.tsx, packages/styleguide/stories/Organisms/GridForm.stories.mdx
GridForm Checkbox input was being re-registered (both in the Controller + in the Checkbox itself), causing some inconsistent behavior on untouched checkbox fields. Adding the field validation to rules fixes that
=> fix: (Checkbox) remove ref  + fix default value

packages/gamut/src/ProgressBar/__tests__/ProgressBar-test.tsx, packages/gamut/src/ProgressBar/index.tsx, packages/gamut/src/RadialProgress/index.tsx, packages/gamut/src/Typography/variants.ts
Fixes a few screen reader bugs in the ProgressBar and RadialProgress
- Progress Bar now reads on a screen reader as `Progress: xx%` with no other noise 
- RadialProgress now reads on a screen reader as `xx% progress` with no other noise 
- The Progress Bar w/percentage readout was reading both the wrapper label (`Progress: xx%`) and then the internal span (`xx%`).  - Fixed by setting aria-hidden on visual percentage readout to true
- Progress Bar component was reading as `empty figure` - fixed by using an internal label element and removing 'aria-label' from the wrapping div
- Radial Progress label was reading as `[x%, xx%] progress` when an array was used
- Radial Progress component was also reading as `empty group`, changed to figure element, with a screen reader only figcaption.
=> fix(a11y): fixes screen reader readout for progress components

packages/gamut/src/Markdown/__tests__/Markdown-test.tsx, packages/gamut/src/Markdown/index.tsx, packages/gamut/src/Markdown/libs/overrides/Table/index.tsx, packages/gamut/src/Markdown/libs/overrides/Table/styles.module.scss
Removes 'tight' max-height of 150px and sets the max-height to 500px by default for Markdown tables. Also adjusts overflow to be `auto`, not always `scroll`.
before:
after:
=> feat(Markdown): remove max-height of tables

packages/gamut-styles/src/ColorMode.tsx, packages/gamut/src/Card/index.tsx
* Switch Cards to use `Background` to ensure components within cards behave correctly.
* Changes hover behavior to only use borderColor and without an outline for future proofing.
=> fix: Cards now correctly set color mode for their contents GM-308

packages/tracking/src/integrations/__tests__/mapDestinations-test.ts, packages/tracking/src/integrations/mapDestinations.ts
Add more Segment categories to our OneTrust consent mapping
We are also removing the hardcoded logic for FullStory.  It was broken, as FullStory was enabled in the list of destinations, and was thus always overriding this.  Seeing as we didn't go over our recording budget, we decided to just continue to open this up to all people.
There is a known but in the Pricing page (Next.js Portal App) which is causing the Segment Scripts to not be initialized.  we will be tackling that in a separate branch next sprint.
=> chore(tracking): Update segment destination mappings

packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
Adds `aria-expanded` to the `Anchor` we are now using instead of the `AccordionButton` within the `LayoutMenu` to fix an accessibility bug.
=> fix(LayoutMenu): add aria-expanded

packages/gamut/src/ToolTip/__tests__/ToolTip-test.tsx, packages/gamut/src/ToolTip/index.tsx
change ToolTip aria-labelledby to aria-describedby to pass cypress-axe tests in portal-app
related PR in portal-app: https://github.com/codecademy-engineering/portal-app/pull/440
this was the axe error: 
```
Description:  Ensures ARIA attributes are allowed for an element's role
Elements must only use allowed ARIA attributes
https://dequeuniversity.com/rules/axe/4.2/aria-allowed-attr?application=axeAPI
"Fix all of the following:
ARIA attribute cannot be used: aria-labelledby"
```
=> fix: add role to ToolTip for axe

packages/gamut/src/ToolTip/index.tsx
ToolTip role button fixed accessibility things for everything but focusable children of tooltips (found from failures happening [here](https://github.com/codecademy-engineering/Codecademy/pull/26460)). This fixes that in a way that should be a no-op
=> fix(ToolTip): role button conditional on focusable prop

packages/gamut/src/Form/FormGroupLabel.tsx, packages/gamut/src/ToolTip/__tests__/ToolTip-test.tsx, packages/gamut/src/ToolTip/index.tsx
Makes `role=button` conditional (in the right way) based on the focusable prop.
draft monolith PR here : https://github.com/codecademy-engineering/Codecademy/pull/26542
=> fix(ToolTip): fix ternary for focusable

packages/styleguide/.storybook/components/Docs/DocsPage.tsx
* These were too short and looked weird.
=> fix(styleguide): Set Figma blocks aspect ratio to 16:9 GM-336

packages/gamut/src/Form/Checkbox.tsx
On Firefox and Safari the screen reader is picking up the SVG as an unlabeled image.
=> fix: Hiding checkbox svg from accessibility api

packages/gamut/src/Form/Checkbox.tsx, packages/styleguide/stories/Atoms/FormInputs/Checkbox.stories.mdx
Fixes an issue where Checkboxes weren't being properly labelled on Safari + Firefox. Please check out the [Checkbox](https://612ff33f7b1bb40b3b04f8fb--gamut-preview.netlify.app/storybook/) story and the [Portal App PR](https://github.com/codecademy-engineering/portal-app/pull/542) to test the behavior.
=> fix(Checkbox): safari and ff labelling

packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx, packages/gamut-labs/src/lib/resourcesList/index.ts
Reverts Codecademy/client-modules#2022
=> fix: add docs back to header and footer

packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx, packages/gamut-labs/src/lib/resourcesList/index.ts
Reverts Codecademy/client-modules#2024
JK We're nixing Docs from the header and footer again. lolol
(Docs errors came back to bite in THE INCIDENT TAKE 2, so we're nixing Docs for the weekend until we can root cause it effectively next Tues)
=> fix: Revert "fix: add docs back to header and footer"

packages/gamut/src/Card/index.tsx
* Cards without a variant  didn't set text color (`Background` does this automatically, but is not used for these).  This appropriately sets them.
=> fix: Set `Card` non variant text color to ensure no inheritance GM-347

packages/gamut-labs/src/AppHeader/index.tsx, packages/gamut-labs/src/AppHeaderMobile/index.tsx
* Adds logic for small button usage on the mobile menu
* Ensures that only 1 button is visible when under our smallest breakpoint to prevent blowout.
=> fix(GlobalHeader): Limit buttons on mobile header < XS to 1 and use small size GM-345

packages/gamut-labs/src/Notifications/NotificationsContents.tsx, packages/gamut-labs/src/Notifications/NotificationsPopover.tsx
Corrects 360px width for header notifications to only apply in the desktop popover.
=> fix(GlobalHeader): corrected 360px for notifications

.circleci/config.yml
Removes `storybook` from the beginning of styleguide deploy URIs by deploying what's inside that folder instead of its parent.
- ~[] This PR includes unit tests for the code change~
=> chore(styleguide): remove 'storybook' prefix from deploy URIs

packages/gamut-labs/src/Avatar/__tests__/avatar-test.tsx, packages/gamut-labs/src/Avatar/index.tsx
Changed the <Avatar /> component to using numbers directly over the string enum to give greater flexibility with size extensions
=> feat(Avatar)!: convert avatar sizes to using numbers over string enum

packages/gamut-labs/src/LandingPage/CTA.tsx, packages/gamut-labs/src/LandingPage/PageFeatures.tsx, packages/gamut-labs/src/LandingPage/PageHero.tsx, packages/gamut-labs/src/LandingPage/PagePrefooter.tsx, packages/gamut-labs/src/LandingPage/PageVideoGallery.tsx, packages/gamut-labs/src/LandingPage/types.tsx, packages/styleguide/stories/Brand/Organisms/PageFeatures.stories.mdx, packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx, packages/styleguide/stories/Brand/Organisms/PagePrefooter.stories.mdx, packages/styleguide/stories/Brand/Organisms/PageVideoGallery.stories.mdx
Updates `CTA` to take a `buttonType` prop to determine whether to show a `CTAButton` (default) or a regular `FillButton`. Also refactors `PagePrefooter` to use newer gamut components.
=> feat: update landing page `CTA` to show fill button or cta button

packages/gamut-labs/src/LandingPage/PageHero.tsx, packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx
Previously, the image was always hidden on mobile. This adds the ability to choose whether to show the image on mobile or not with an optional boolean prop, the default being the previous standard to hide on mobile.
This is a successor (update on the latest main) to [PR2079](https://github.com/Codecademy/client-modules/pull/2079)
=> feat(PageHero): add option to show image on mobile

packages/gamut-labs/src/Drawer/index.tsx
Adds 100% height to the intermediate `Box` within `Drawer`.
I'd missed this in https://github.com/Codecademy/client-modules/pull/2083, it needs to be there so tall content can have a vertical scrollbar.
=> fix(Drawer): add 100% height to inner Box

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
As part of a wider security initiative we are restricting Business access to a new `business_admin` role. This PR is using this role for controlling visibility of the `Business Account Management` dropdown menu item.
=> fix: changing logic of Business Account Management profile item to use `isBusinessAdmin`

packages/gamut-labs/src/Drawer/index.tsx
Adds a `max-width: 100%` to the `Box` inside `Drawer`s so contents don't overflow horizontally.
=> fix(Drawer): add missing max-width: 100%

packages/gamut-labs/src/GlobalPage/index.tsx
Changes `GlobalPage`'s `backgroundColor` prop to be only one of the ones we know we want.
I keep accidentally giving it `"blue-0"` instead of `"paleBlue"`...
=> chore(GlobalPage): restricted allowed background colors

packages/gamut-illustrations/src/Bee.tsx, packages/gamut-illustrations/src/Bell.tsx, packages/gamut-illustrations/src/BinaryBlocks.tsx, packages/gamut-illustrations/src/Browser.tsx, packages/gamut-illustrations/src/BrowserLock.tsx, packages/gamut-illustrations/src/BrowserPuzzle.tsx, packages/gamut-illustrations/src/ChatBox.tsx, packages/gamut-illustrations/src/Confetti.tsx, packages/gamut-illustrations/src/EmailAt.tsx, packages/gamut-illustrations/src/Envelope.tsx, packages/gamut-illustrations/src/Heart.tsx, packages/gamut-illustrations/src/Hills.tsx, packages/gamut-illustrations/src/HomeOffice.tsx, packages/gamut-illustrations/src/Keyhole.tsx, packages/gamut-illustrations/src/Maze.tsx, packages/gamut-illustrations/src/Megaphone.tsx, packages/gamut-illustrations/src/New.tsx, packages/gamut-illustrations/src/NumberBlocks.tsx, packages/gamut-illustrations/src/Onboarding.tsx, packages/gamut-illustrations/src/Plant.tsx, packages/gamut-illustrations/src/Python.tsx, packages/gamut-illustrations/src/Sun.tsx, packages/gamut-illustrations/src/Target.tsx, packages/gamut-illustrations/src/types.ts, packages/styleguide/stories/Atoms/Illustrations.stories.mdx
adds aria-hidden prop to illustrations since many of them are descriptive and should be ignored by voice readers
thank you to the accessibility pro @katiezutter for putting together this solution! 
integration pr: https://github.com/codecademy-engineering/portal-app/pull/970
=> fix: add aria-hidden prop to illustrations

packages/gamut/src/Tabs/TabPanel.tsx, packages/gamut/src/Tabs/Tabs.tsx, packages/styleguide/stories/Molecules/Tabs/Tabs.examples.tsx, packages/styleguide/stories/Molecules/Tabs/index.stories.mdx
Fixes an issue where the `index` prop, which controls whether a `Tabs` component is controlled or uncontrolled, was not being forwarded correctly.
=> fix: fix index prop forwarding for Tabs component

packages/gamut/src/Tabs/TabButton.tsx
Fixes vertical centering text on `<TabButton/>` component
=> chore: fix top padding on tab buttons

packages/gamut-labs/src/AvatarChooser/index.tsx, packages/gamut/src/GridForm/GridFormSections/GridFormSectionBreak.tsx
Add `role="separator"` to  GridFormSectionBreak component (part of GridForm organism)
Add `aria-live="polite"` to AvatarChooser container, and `role="alert"` to the FormError so the error msg is announced to a screen reader; 
I also tried  changing Choose Photo button of AvatarChooser to be an HTML `<button>` instead of a `<span role="button">` but that led to other errors I wasn't sure I wanted to look into now... 
To test, please see the sister PR in portal app
https://github.com/codecademy-engineering/portal-app/pull/1324
and the related preview environment:
https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1324
=> fix(SectionBreak, AvatarChooser): accessibility improvements, use roles & aria-live

packages/gamut/src/Form/Radio.tsx
Makes it so users can select form radio labels and the like.
Noted by @marielfrank to be rather inconvenient in the new `GridForm` workspace slug chooser form.
=> fix(Form): remove noSelect from form radios

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx, packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx, packages/gamut-labs/src/AppHeader/index.tsx, packages/gamut-labs/src/AppHeader/shared.tsx, packages/gamut-labs/src/AppHeaderMobile/index.tsx
- match overlay display media query to mobile header media query
- fix issue where app header dropdown wasn't always displaying (i.e. had a height of 0) by updating the layout hook dependencies to include isOpen. When isOpen is true that means animation complete + height is no longer 0
Visit production story book:
https://gamut.codecademy.com/?path=/story/organisms-globalheader--free-user-pro-upgrade
open "canvas" view
select "MD" screen size
click on hamburger menu button
see that the header disappears
Now run my branch locally
Visit http://localhost:6006/?path=/story/organisms-globalheader--free-user-pro-upgrade
open "canvas" view
select "MD" screen size
click on hamburger menu button
see that the header does not disappear
screen size selection is done with the squares icon:
=> fix(GlobalHeader): fix mobile menu for screen sizes btwn 1024-1200px

packages/gamut/src/List/elements.tsx, packages/gamut/src/List/types.ts
* Allows `plain` to be set as List variant, which was originally only used internally within Gamut. Allows ListRows to be more configurable and flexible. 
* Adds focus-within to our ListRow stylings (so when an Anchor is within a ListRow, it will apply the correct styles)
alpha package [here](https://github.com/codecademy-engineering/Codecademy/pull/29608)
=> feat(List): allow access to `plain` variant + extend focus styles to focus-within

packages/gamut-labs/src/AvatarChooser/index.tsx
Refactors AvataChooser's props to updated react-hook-form v7 syntax and correct fallback props for if register is undefined.
monolith: [here](https://github.com/codecademy-engineering/Codecademy/pull/29757)
portal: [here](https://github.com/codecademy-engineering/portal-app/pull/1545)
=> fix(AvatarChooser): update to proper rhf v7 syntax

packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx, packages/gamut-labs/src/GlobalHeader/index.tsx
We need to pass `user` to `anonDefaultHeaderItems` and `anonSignupHeaderItems`. We also need to pass `user` to all `anon` `getAppHeaderItems` cases. This is so we can grab the `useNewCatalogDropdown` value for the anon `GlobalHeader` states.
=> fix(GlobalHeader): Pass user to all anon header items

packages/gamut-labs/src/HorizontalScrollMenu/index.tsx
fixes an accessibility issue where `aria-hidden` elements can't have focusable elements within them. By creating this psuedo selector on attribute we make sure that focus won't go in.
=> fix(HorizontalScrollMenu): fixed axe issue with hidden elements receiving focus

packages/gamut/src/Tabs/TabNavLink.tsx
Semantically labeling TabNavLink as a tab to fix a A11y  bug
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31091)  | [Monolith Env](https://pr-31091-monolith.dev-eks.codecademy.com) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2101)  | [Portal Env]( https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2101)   |
| BAM| [Another Link](https://github.com/codecademy-engineering/business-account-management/pull/651) | [Another …
=> fix: TabNavLink not semantically a tab

packages/gamut-labs/src/PausableImage/BaseImage/index.tsx, packages/gamut-labs/src/PausableImage/index.tsx, packages/styleguide/stories/Brand Labs/Molecules/PausableImage.stories.mdx
Fixing a A11y bug that appeared if a user using voiceover toggle the image using the ``space bar`` or the ``enter`` key.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31093)  | [Monolith Env](https://pr-31093-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2102)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2102)   |
=> fix: update PasuableImage button to announce it's label change

packages/gamut/src/List/ListRow.tsx
This came up while researching this ticket: https://codecademy.atlassian.net/browse/PX-5789 where duplicate track calls were being fired when a ListRow was clicked.
After digging into the gamut code, it looks like we're using `onClick` twice - this removes it on the outer wrapper and instead only uses it if there exists a `renderExpanded` prop. 
To see the behavior before, go to: codecademy.com/courses/introduction-to-javascript/lessons/introduction-to-javascript/exercises/intro and open the Get Unstuck menu. In the Network/Other tab, note that when you click to expand a section, there are duplicate track events.
To see the fix in action, visit [the preview app](https://pr-31188-monolith.dev-eks.codecademy.com/courses/introduction-to-javascript/lessons/introduction-to-javascript/exercises/ …
=> fix(ListRow): remove double onClick call

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderResourcesDropdown/index.tsx, packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx, packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx, packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx, packages/gamut-labs/src/GlobalHeader/types.tsx, packages/styleguide/stories/Brand Labs/Organisms/GlobalHeader.stories.mdx
[DISC-731](https://codecademy.atlassian.net/browse/DISC-731?atlOrigin=eyJpIjoiNTdiNDE2MTkzMDhhNDNiNTk2N2M0NGM0ZGU0ZTdhMjciLCJwIjoiaiJ9): Cannot keydown into Inspiration section on Resources dropdown desktop
[DISC-732](https://codecademy.atlassian.net/browse/DISC-732?atlOrigin=eyJpIjoiYTk5YjY5YzNmYTMzNDY0OWJiZTc5Y2ZmY2U0MDQ0M2YiLCJwIjoiaiJ9): Change tracking target for Catalog (to expose dropdown)
[DISC-734](https://codecademy.atlassian.net/browse/DISC-734?atlOrigin=eyJpIjoiODlmYjE1MTRlYzQ3NDMxMTg0ZWEzYjJmYzM4OTU3MzQiLCJwIjoiaiJ9): Catalog and Resources dropdown menus should line up with logo for pro users *we will no longer be using the pro logo - see annotation for details
1. With VO on, you should now be able to keydown into Inspiration section of Resources menu
2. Catalog dropdown …
=> fix(GlobalHeader): Catalog and Resources dropdown fast follows 

packages/gamut-illustrations/src/Coffee.tsx, packages/gamut-illustrations/src/index.ts
=> feat(Illustration): add coffee illlustration

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
i accidentally forgot to update the handler for subject links in the dropdown to close the dropdown on click
more context for handler change in https://github.com/Codecademy/gamut/pull/2459
=> fix(AppHeaderCatalogDropdown): add click handler for subject links

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
Change external links (such as the help center + forums) in the footer to open in a tab
Links to Test:
- forum
- blog
- chapters
- shop
- help center
- discord
In the storybook preview environment: https://62fd5b0ba7cca90f14fc4f95--gamut-preview.netlify.app/ visit the global footer and click on each of the Links to Test and ensure they open in a new window.
In the monolith + portal app preview environments, scroll down the footer and click on each of the Links to Test
Ensure the links open in a new tab …
=> fix(GlobalFooter): open external links in new tab

packages/gamut-illustrations/src/TinyBlocks.tsx, packages/gamut-illustrations/src/index.ts
Add TinyBlocks illustration 
Go into storybook preview env, navigate to Illustrations and see TinyBlocks in all its glory. 
https://6307c21e93d11a00950fd4a7--gamut-preview.netlify.app/?path=/docs/atoms-illustrations--editable-illustration#illustrations
[DISC-785]: https://codecademy.atlassian.net/browse/DISC-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Illustration): add TinyBlocks

packages/gamut/src/Form/SelectDropdown/SelectDropdown.tsx, packages/gamut/src/Form/SelectDropdown/elements.tsx, packages/gamut/src/Form/SelectDropdown/styles.ts, packages/gamut/src/Tag/elements.tsx, packages/gamut/src/Tag/index.tsx
Updates the `SelectDropdown` multi value options to look like our new `Tag` component! `SelectDropdown` uses react select so we are doing this by overriding the styles for multivalue, multivalue label, and multi value remove by passing in styles that are shared with `Tag`. Multivalue select dropdowns do not appear to be currently used anywhere (looked in monolith, portal app, BAM, author) so this change can be easily made across the board.
1. Visit https://63486a28d5f8d9006abcae64--gamut-preview.netlify.app/?path=/docs/atoms-forminputs-selectdropdown--select-dropdown
2. Change the "multiple" prop to true in the prop table
3. Select multiple options in the dropdown and see the new beautiful colors
| Repository   | PR Link                                                  | PR Env …
=> feat(SelectDropdown): make multi value look like tag

packages/gamut/src/Toaster/index.tsx
This removes the hard-coded light mode from the `Toaster` in order to show dark mode notifications in Author.
[On Slack](https://codecademy.slack.com/archives/CTVEHH2PP/p1668784079583599), we talked about potentially passing an `inverse` prop or introducing a separate higher-order component for cases where we want the `Toaster` to override the user's selected color mode (e.g. the LE?), but these approaches would have required changes to the LE in order to preserve the current light mode notifications.
Instead, I opted to pass an optional `colorMode` prop with a default value of `light`. This lets us pass the user's selected color mode in Author, without affecting the appearance of notifications elsewhere in the codebase.
Visit the Author PR env linked below and make some changes to a …
=> feat(Toaster): Use current color mode in `Toaster`

packages/gamut-labs/src/RatingsBar/index.tsx
Conditional box shadow (hide if 0%)
1. Go to local gamut and yarn start.
2. Visit [http://localhost:6006/?path=/docs/brand-labs-atoms-ratingsbar--ratings-bar](http://localhost:6006/?path=/docs/brand-labs-atoms-ratingsbar--ratings-ba)r
3. Confirm the bar still has box shadow if percent is greater than zero
4. Set the `minimumPercent` and `percent` to zero. Confirm you see an empty bar (without a boxshadow line to the right of the beginning edge)
[REACH-2324]: https://codecademy.atlassian.net/browse/REACH-2324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(RatingsBar): Conditional box shadow (hide if 0%)

packages/gamut/src/Tabs/TabButton.tsx, packages/gamut/src/Tabs/props.tsx
Fixes focus outline that was missing from Tabs when using keyboard navigation
https://user-images.githubusercontent.com/29311886/224438891-c851cc6f-26e7-43ab-9888-4b549437cde2.mov
1. Visit https://640bb0101c16eb0c81e322e1--gamut-preview.netlify.app/?path=/docs/molecules-tabs--tabs
2. Using `tab` key, navigate to the Tabs example.
3. Using the arrow keys to navigate between tabs. Confirm that the focus outline appears around the tabs.
4. Enter the `tab` key. Confirm that the tab panel has the focus outline. …
=> fix(TabButton): fixes focus outline on tabs

packages/gamut/src/Popover/Popover.tsx
Move popover position with target when in a scroll container
We currently handle repositioning the popover so that it moves with the target when a user scrolls at the window level. However, we were not handling scrolling if the popover was within a container that scrolls while the window scroll is stationary (e.g. for narrative content on the LE). This PR introduces behavior to find the parent/ancestor element that is scrollable and ensure that the popover position is updated each time a scroll event is fired on that parent element.
- Open `packages/styleguide/stories/Molecules/Popover/Popover.examples.tsx`
- Edit the `PopoverExample` so that it returns something in a scroll container, e.g.
```
return (
<div style={{overflow: 'auto', maxHeight: '200px' }}>
{'abcde'.split('').map(x => …
```
=> fix(Popover): move position with target when in scroll container

packages/gamut-styles/src/cache/stylisPlugins/focusVisible.ts
In [this commit](https://github.com/Codecademy/gamut/commit/ccfd943be6dd1a73aff2a4e021fbaf4e15d75c7a), Aaron Robb fixed an issue so that instead of replacing `:focus-visible` with `[data-focus-visible-added]` (used for polyfills) we use both. However, this fix was only enabled when `process.env.NODE_ENV === 'dev'`. This was exposed when we found the the LE was missing some `:focus-visible` gamut styles because it did not use said polyfill. (the outline on links did not match the hyper blue color)  We should always enable this fix so that we can continue using the polyfill but not be dependent on it.
As a bonus, this will make it easier to debug `:focus-visible` styles in chrome dev tools, since it will allow the `:hov -> :focus-visible` toggle to work properly. (the current behavior is …
=> fix(focusVisible): enable always for both native and polyfill

packages/gamut/src/Form/Input.tsx
This PR adds back the ability to manually control an `Input`'s activated style by referring to the activated prop when it's passed in.
This change came about while I was working on an accessibility ticket around the recurly fields. While separating out the fields from 1 field to separate fields so that we could focus them individually on error, I noticed that the recurly inputs were starting in an activated state. For whatever reason Recurly is firing onChange events before the user interacts with the field. This makes `Input` think the field has been activated when it hasn't been interacted with yet. I noticed this prop existed but I think the functionality associated with the prop was removed. I'm not sure if that was intentional (it was a long time ago now) so I'm proposing to add it …
=> fix(Input): use activatedStyle from props when value is provided

.vscode/settings.json, packages/gamut/src/Menu/Menu.tsx, packages/gamut/src/Menu/MenuContext.tsx, packages/gamut/src/Menu/MenuItem.tsx, packages/gamut/src/Menu/__tests__/Menu.test.tsx, packages/styleguide/stories/Molecules/Menu/Menu.examples.tsx, packages/styleguide/stories/Molecules/Menu/index.stories.mdx
Add role as an optional prop to Menu + clarifying documentation on when the `menu` role should be used. 
* Navigate to the Menu storybooks
* Look at all the nice new documentation
* Inspect the default Menus - see they do not have the menu role and their children do not have the menuitem role.
* Inspect the popover menu - it should have the menu role and it's childrn should have the menuitem role.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/36971)  | [Monolith …
=> feat(Menu): add optional menu role

packages/gamut/src/ToolTip/FloatingToolTip.tsx
Reverts Codecademy/gamut#2840 -- breaks click handlers on tooltips
=> chore(ToolTip): Revert "fix: maintain open state when hovering over 'floating' tooltip content"

packages/styleguide/stories/Molecules/Popover/Popover.examples.tsx, packages/styleguide/stories/Molecules/Popover/index.stories.mdx
- updating popover stories to include `position` prop
1) check out the new position section in popover stories: https://65fc7a5c38fbe95a637a67ea--gamut-preview.netlify.app/?path=/docs/molecules-popover--popover#position
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ …
=> fix(popover): add position to popover stories

packages/gamut/src/Modals/ImageContainer.tsx, packages/gamut/src/Modals/elements.tsx, packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx
- adds `large` size option to Modal component
1. Check modal page: http://localhost:6006/?path=/docs/molecules-modals-modal--large
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- | 
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/6521)  | [Portal Env](https://tengu.codecademy.com/learn?PR_ENV=portal-app-pr-6521)   |
=> feat(Modal): add large size option to Modal

packages/gamut/src/Markdown/styles/_mixins.scss
Use child instead of descendant selector for li in markdown
When a chatbot responds with bulleted lists inside of numbered categories, we were displaying the bullets as numbers also.
|before|after|
|-|-|
|<img src="https://github.com/Codecademy/gamut/assets/6615558/c1c74817-b5c8-4db2-82b2-8b659bb4546d" width="300">|<img width="300" alt="Screenshot 2024-06-17 at 11 12 40 AM" src="https://github.com/Codecademy/gamut/assets/6615558/e6688aab-79a8-429a-9aed-d3bd7efd4993">|
```html
<ol>
<li> - ordered list styles should apply here
<ul>
<li> - but not here
```
[Mono PR](https://github.com/codecademy-engineering/mono/pull/6671)
[LE Preview](https://tayra.codecademy.com/workspaces/new?PR_ENV=le-pr-6671)
[Portal App Preview](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-6671)
=> fix: Use child selector for li in markdown

packages/styleguide/stories/Atoms/Card.stories.mdx, packages/styleguide/stories/Atoms/Drawer.stories.mdx, packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx, packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx, packages/styleguide/stories/Atoms/InputStepper.stories.mdx, packages/styleguide/stories/Atoms/ProgressBar/index.stories.mdx, packages/styleguide/stories/Layouts/Box/index.stories.mdx, packages/styleguide/stories/Layouts/LayoutGrid.stories.mdx, packages/styleguide/stories/Molecules/Breadcrumbs.stories.mdx, packages/styleguide/stories/Molecules/Coachmark/index.stories.mdx, packages/styleguide/stories/Molecules/Flyout.stories.mdx, packages/styleguide/stories/Molecules/Modals/Dialog.stories.mdx, packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx, packages/styleguide/stories/Molecules/Popover/index.stories.mdx, packages/styleguide/stories/Molecules/Tip/InfoTip.stories.mdx, packages/styleguide/stories/Molecules/Tip/ToolTip.stories.mdx, packages/styleguide/stories/Molecules/Toast.stories.mdx, packages/styleguide/stories/Organisms/ConnectedForm/ConnectedForm.stories.mdx, packages/styleguide/stories/Organisms/ConnectedForm/SubmitButton.stories.mdx, packages/styleguide/stories/Organisms/GridForm.stories.mdx, packages/styleguide/stories/Typography/Text.stories.mdx
1. Look over the JIRA ticket
2. Go to the respective pages
3. Check that the statuses match
4. ...
5. Profit!
[GM-754]: https://codecademy.atlassian.net/browse/GM-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(misc): updating component statuses in SB

packages/gamut/src/Alert/variants.tsx, packages/gamut/src/Button/IconButton.tsx
Two Issues:
1. The Alert's alignments were off (not centered and stretched out):
The alignment Alert wasn't rendering properly because the alert was stretched vertically.
Upon investigation, it was the X button that had a large height, despite the button seemingly set to "small"
Looking into IconButton, seems like the size prop wasn't used, adding this prop back in seemed to fix the issue.
--- 
2. The border radius of both inline and general alerts should be 3px. 
1. Go to `/docs/molecules-alert--usage-guidelines#alert-types` 
2. Check that the height alignment matches [figma](https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=30186-40358&m=dev)
| Repository   | PR Link                                                  | PR Env …
=> fix(Alert): height and alignment

packages/gamut/src/Tip/InfoTip/elements.tsx, packages/gamut/src/Tip/InfoTip/index.tsx
Fixes misaligned Infotips - this happened because the screenreader text was a sibling to the Tip container, it is now a child of the Tip container
* Go to GridForm story
* See the InfoTips properly aligned
* Turn on VO
* Hear them properly announced
* Double check the InfoTip story for floating and regular InfoTip, include cmd + opt text nav
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/38101)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal …
=> fix(GridForm): properly align gridform infotips

packages/gamut-icons/src/props.ts
Icon's size prop was missing documentation.
added details for Icon's size prop
1. Go to `?path=/docs/atoms-icons-mini--mini-icon`
2. Go down to proptable and see that the size row is now populated
3. Check that the info is correct.
4. ...
5. Profit!
[GM-639]: https://skillsoftdev.atlassian.net/browse/GM-639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(Icon): added details for Icon's size prop

packages/gamut/src/Drawer/index.tsx, packages/gamut/src/Flyout/index.tsx, packages/gamut/src/Popover/Popover.tsx, packages/styleguide/stories/Atoms/Drawer.stories.mdx
This PR fixes a layout issue where flyout content had been rendering slightly shifted to the left in certain cases. This is a complex issue having to do with the fact that overflow="hidden" in the Drawer component causes reflow during the animation, specifically when it occurs within the fixed Flyout component.
The Drawer component currently animates the width of a parent wrapper, while holding content in a child wrapper. The main fix is to use `overflow="clip"` (which does not cause reflow) rather than `overflow="hidden"` on the parent wrapper, and to move `overflowY` scrolling to the child wrapper.
Example of how this fixes the unintended layout shift in mobile catalog menus:
|before|after|
|-|-|
|<img width="410" alt="Screenshot 2024-07-24 at 11 03 41 AM" …
=> fix(Drawer,Flyout): alignment

packages/styleguide/stories/Atoms/Button/index.stories.mdx
Adding a guidance note for TextButton
1. Go to the preview's `?path=/docs/atoms-button--text-button` section
2. Check that the text is there (proofread as well?) 
3. ... 
4. Profit!
=> docs(Button): Adding guidance note for TextButton

packages/gamut/src/Disclosure/DisclosureButton/index.tsx
aria-label on disclosure was wiping out button text, this fixes that
1. head to disclosure story
2. turn on VO
3. hear the button announced when navigating with tab
4. ...Profit!
=> fix(Disclosure): remove aria-label

packages/styleguide/stories/Atoms/FormElements/FormGroup.stories.mdx
Updates the `FormGroup` examples to accurately mark form inputs as required to match their label
1. Visit the storybook preview
2. Under FormGroup states see that the inputs are marked as required with an asterisks (which matches the label text)
[GM-850]: https://skillsoftdev.atlassian.net/browse/GM-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(FormGroup): Use correct required prop in FormGroup storybook examples

packages/gamut/src/Tip/shared/FloatingTip.tsx, packages/gamut/src/Tip/shared/utils.tsx
Fixes FloatingTips weirdness - basically cancels the open call for Tooltips if the user doesn't hover or focus for the delay timeout 
* head to the Floating header of the ToolTip story ([link](https://66fed2f6f914aaf1d572ebf7--gamut-preview.netlify.app/?path=/docs/molecules-tip-tooltip--tool-tip#floating-placement))
* SUPER QUICKLY mouse over Tooltip
* You should not see the ToolTip open
* SUPER QUICKLY tab/tab away from the button
* You should not see the ToolTip open
* ToolTip should otherwise  work the same as now
| …
=> fix(FloatingTip): fixes delay timeouts for hover + mouseover

packages/gamut/src/Markdown/__tests__/Markdown.test.tsx, packages/gamut/src/Tip/InfoTip/styles.tsx
Realized while auditing the FloatingTip issue that InfoTip was missing its hover background
* Head to the InfoTip stories
* InfoTip will now have a background color on hover
tbd
=> fix(InfoTip): background hover

packages/gamut/package.json, packages/gamut/src/ConnectedForm/ConnectedFormGroup.tsx, packages/gamut/src/ConnectedForm/ConnectedInputs/ConnectedInput.tsx, packages/gamut/src/ConnectedForm/ConnectedInputs/ConnectedRadio.tsx, packages/gamut/src/ConnectedForm/ConnectedInputs/ConnectedSelect.tsx, packages/gamut/src/ConnectedForm/ConnectedInputs/ConnectedTextArea.tsx, packages/gamut/src/ConnectedForm/SubmitButton.tsx, packages/gamut/src/ConnectedForm/__tests__/ConnectedForm.test.tsx, packages/gamut/src/ConnectedForm/index.ts, packages/gamut/src/ConnectedForm/types.ts, packages/gamut/src/ConnectedForm/utils.tsx, packages/gamut/src/GridForm/GridForm.tsx, packages/gamut/src/GridForm/GridFormSections/GridFormContent.tsx, yarn.lock
Makes a couple changes to ConnectedForm - I think some of the pakacge bumps require stricter type safety 
All tests + builds are now passing locally, the remaining test failures are due to the other act errors. See *all* tests passing in the [monorepo PR ](https://github.com/codecademy-engineering/mono/pull/8329)
=> Cass sb 8 fix connectformtypes

packages/gamut-styles/src/remoteAssets/fonts.ts
Request fonts on same origin so that font-face can use result from preload request.
[See related RPW changes](https://github.com/codecademy-engineering/mono/pull/8632)
- Open the [Portal Preview Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-8638)
- Open the network tab
- Search for "apercu"
- Note that fonts are loaded from `www`
[Portal PR](https://github.com/codecademy-engineering/mono/pull/8638)
[Portal Preview Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-8638)
=> fix(Font): Load from same origin

package.json, packages/styleguide/package.json, packages/styleguide/src/lib/Meta/Installation.mdx
Re-adds installation story to Storybook and fixes the prod deploy command
=> docs: re-add installation story + fix deply CI command

packages/styleguide/.storybook/components/Scales/ColorScale.tsx
After updating Card, the `grid` display and column layout wasn't being recognized. 
Changing the ColorScale's Card to Box fixed the issue. 
1. Go to the [ColorMode](https://67eeac08b323d69b1744b0e8--gamut-preview.netlify.app/?path=/docs/foundations-colormode--docs) check that the tables render correctly
2. Go to [Theme related pages](https://67eeac08b323d69b1744b0e8--gamut-preview.netlify.app/?path=/docs/foundations-theme-about--docs) and check over the tables there too 
3. ... 
4. Profit!
N/A affects only the Gamut repo.
=> fix(colorscale): grid display fixed for color swatches 

packages/styleguide/src/lib/Foundations/shared/adminElements.tsx, packages/styleguide/src/lib/Foundations/shared/applyCorrectNotation.ts, packages/styleguide/src/lib/Foundations/shared/elements.tsx, packages/styleguide/src/lib/Foundations/shared/lxStudioElements.tsx, packages/styleguide/src/lib/Foundations/shared/platformElements.tsx
Colors that have hyphens in name should use bracket notation.
Currently such colors are rendered like: `theme.colors.for-example` but should be `theme.colors['for-example']` 
1. Go to [ColorMode](https://67eea96eb6033ec3927eeb75--gamut-preview.netlify.app/?path=/docs/foundations-colormode--docs), check that the colors that have hyphens in their name use bracket notation
2. Go to the [Theme pages](https://67eea96eb6033ec3927eeb75--gamut-preview.netlify.app/?path=/docs/foundations-theme-about--docs), check that the colors in the ColorTable also use the appropriate notation
3. ...
4. Profit!
N/A this PR affects Gamut only.
=> fix(ColorScale): updated notations for colors that have hyphen in their names 

packages/gamut/src/ConnectedForm/ConnectedFormGroup.tsx
Link the error to the form input via `aria-describedby`
1. Go to `Organisms` > `ConnectedForm` -> `ConnectedForm` > `Docs`
2. Go to the `Playground`
3. Submit the form. This should cause errors to appear on the inputs.
4. Use VoiceOver to navigate through the form
5. When you navigate to the input field, listen for it to read the error.
5. If it successfully reads the error, do a celebratory dance.
If you prefer to test within the portal-app preview env, the same test can be done using `First name` and `Last name` fields on the logged in checkout page. Login first, then navigate to https://tengu.codecademy.com/checkout?plan_type=directpurchase&PR_ENV=portal-app-pr-10427 …
=> fix(ConnectedFormGroup): Have screen reader read form input error

packages/gamut-icons/src/svg/regular/resizable-handle-icon.svg
1. Go to storybook Icon ?path=/docs/atoms-icons-regular--docs
2. Search for ResizableHandleIcon
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')
| Mono       | [Mono PR](http://www.google.fr/ 'Named link title')
=> feat(Icon): added new resizable-handle-icon

packages/styleguide/src/lib/Molecules/Menu/Menu.mdx, packages/styleguide/src/lib/Molecules/Menu/Menu.stories.tsx
Updates the icon-only menu example to mostly have right-center alignment. 
Minor updates to the story text for clarity 
- <del> [ ] This PR includes unit tests for the code change </del> 
- <del> [ ] This PR includes testing instructions tests for the code change </del> 
- <del> [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories </del> 
1. Go to the `Menu` story and scroll down to the "Icon-Only Menus + ToolTips" section
2. Read over the text and check that they make sense
3. Hover over the MenuItem options to see the alignment on all the options EXCEPT for the 1st one
4. ...
5. Finish and do a celebratory dance
N/A documentation change only 
[GM-1180]: …
=> docs(Menu): updated icon-only menu alignment
