packages/gamut/src/Button/styles/variables.scss
packages/gamut/src/Form/Checkbox.tsx
packages/gamut/src/Form/Radio.tsx
packages/gamut/src/Form/styles/Checkbox.scss
packages/gamut/src/Form/styles/Radio.scss
packages/gamut/src/Toggle/styles/index.scss
workspaces/gamut-storybook/stories/Button.stories.js

- Change green to blue for checkbox, radio button, and toggle components
- Remove border from checkbox/radio button and remove gray background from their selected states
- Add disabled states for checkbox and radio button => gray text and grayed out radio/checkbox
For updated email settings page https://codecademy.atlassian.net/browse/LX-3254
when radio buttons are disabled:
when checkboxes are disabled:
---

update checkbox/radio/toggle styles

---

packages/gamut/src/Banner/index.tsx

Added missing aria-label to Banner's dismiss icon

---

.circleci/config.yml
codecov.yml

They recently updated the script to run even on failure, which hopefully will fix the partial coverage issues

ci: update codecov orb

---

packages/gamut-styles/utils/variables/_colors.scss
packages/gamut-styles/utils/variables/index.js
packages/gamut/src/Button/styles/variables.scss
workspaces/gamut-storybook/stories/Button.stories.js

Added brand-orange to colors, button variables, and storybook

---

packages/gamut/babel.config.js
packages/gamut/package.json
yarn.lock

Compile using babel instead of just `tsc`

compile gamut using babel

---

.circleci/config.yml
codecov.yml

This is a little heavy-handed, I couldn't really find something that did what I wanted but I didn't have time to write something. Might come back and write a small open-source tool to handle this commenting stuff.
In the meantime this works :)

ci: Add a PR comment w/ the published alpha versions

---

packages/brand-components/README.md
packages/brand-components/src/Avatar/__tests__/avatar-test.tsx
packages/brand-components/src/Avatar/index.tsx
packages/brand-components/src/Avatar/styles.module.scss
packages/brand-components/src/index.ts
packages/brand-components/src/typings/css.d.ts
packages/brand-components/src/typings/svg.d.ts
packages/gamut-templates/CHANGELOG.md
packages/gamut-templates/package.json
packages/gamut/CHANGELOG.md
packages/gamut/package.json
packages/gamut/src/Form/Radio.tsx
packages/styleguide/stories/Avatar.stories.js

Create Avatar brand-component

---

packages/gamut/src/Layout/Column.tsx
packages/gamut/src/Layout/Grid.tsx
packages/gamut/src/Layout/styles/Column.module.scss
packages/gamut/src/Layout/styles/shared.scss
packages/styleguide/stories/Layout.stories.js

Allows you to specify the column to start on a LayoutGrid row via props.

feat: add column offsets to layoutgrid

---

.circleci/config.yml

chore: space after :rocket: in deploy preview message

---

packages/brand-components/src/Testimonial/styles.module.scss

- Fixed height on Avatar/Byline rows so height doesn't alter with/without Avatar
- Same with column widths
---

fix: height and width fixes on testimonial grid

---

packages/brand-components/src/Byline/__tests__/Byline-test.tsx
packages/brand-components/src/Byline/index.tsx
packages/brand-components/src/Byline/styles.module.scss
packages/brand-components/src/Testimonial/index.tsx
packages/brand-components/src/Testimonial/styles.module.scss
packages/styleguide/stories/Byline.stories.js
packages/styleguide/stories/Testimonial.stories.js

Full name is shown when the total character length is less than the limit set by design, otherwise first name is only shown.
Company name is included in another `span` in the Byline component. Is hidden below a certain breakpoint.
---

feat: add company and full name info to Testimonial

---

packages/brand-components/src/Testimonial/styles.module.scss

Design wants this behavior before launch on Monolith.
---

feat: transform Testimonial content container on hover

---

packages/gamut/src/Layout/Column.tsx
packages/gamut/src/Layout/styles/shared.scss
packages/gamut/src/Layout/types.ts
packages/styleguide/stories/Layout.stories.js

Changes offset props to allow for 0 width offset.

feat(Column): allows 0 width column size for column offset

---

packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
packages/gamut/src/ContentContainer/__tests__/ContentContainer-test.tsx
packages/gamut/src/ContentContainer/index.tsx
packages/gamut/src/ContentContainer/styles.module.scss
packages/gamut/src/index.tsx
packages/styleguide/stories/ContentContainer.stories.js

To be enable use cross-repo.
---

feat: create contentContainer component

---

.circleci/config.yml
.github/pull_request_template.md
README.md
lerna.json
package.json
yarn.lock

allows us to use the new `feat!: message` syntax for breaking changes
---

ci: use conventionalcommits instead of angular

---

packages/gamut-icons/icon-template.js
packages/gamut-icons/svgr.config.js
yarn.lock

Forgot to add these files when I rebased.

fix(Build): Update lockfile and config file to include new template

---

packages/gamut/src/ProgressBar/styles.module.scss

The old one had it and the new one doesn't. For shame...

feat: added half second transition to ProgressBar

---

packages/gamut-templates/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx
packages/gamut-templates/src/GridForm/GridFormInputGroup/__tests__/GridFormInputGroup-test.tsx
packages/gamut-templates/src/GridForm/GridFormInputGroup/index.tsx
packages/gamut-templates/src/GridForm/__tests__/stubs.ts
packages/gamut-templates/src/GridForm/index.tsx
packages/gamut-templates/src/GridForm/types.ts
packages/gamut/src/Form/Checkbox.tsx
packages/styleguide/stories/GridForm-story.scss
packages/styleguide/stories/GridForm.stories.js

I'll need this to Reactify the /admin/maintenance page.

feat: allowed for checkbox inputs in GridForm

---

packages/styleguide/stories/Brand/Avatar/Avatar.stories.tsx
packages/styleguide/stories/Brand/Byline/Byline.stories.tsx
packages/styleguide/stories/Brand/Quote.stories.tsx
packages/styleguide/stories/Brand/Testimonial.stories.tsx

Marketing was looking to take screenshots of custom values, so this'll help them out a little.

chore(brand-components): filled out knobs for other Brand stories

---

packages/styleguide/stories/Templating/DecoratedStory.ts

Forgot to push before merging #721. I am a professional...

chore(styleguide): fixed decoratedStory name param

---

jest.config.js
packages/gamut/src/index.tsx

Exports responsive types from the root.

fix: Exports Responsive Definitions Files

---

packages/styleguide/stories/Meta/About.stories.mdx
packages/styleguide/stories/Meta/FAQs.stories.mdx

We had a meeting and discussed what we've seen as the most common questions or point of disagreements. This seems like an ok summary of our consolidated opinions?

feat(styleguide): added inclusion guidelines to FAQs

---

packages/styleguide/stories/Organisms/About.stories.mdx

I can't believe I was allowed to make this mistake.

fix(styleguide): corrected emoji on Organisms About page

---

packages/styleguide/stories/About.stories.mdx
packages/styleguide/stories/Meta/Writing Stories.stories.mdx
packages/styleguide/stories/Meta/Writing a Story.stories.mdx

The recommendations are maybe 2/3 of what I'd like to fill out with them, but I'm ok with using these as an exploratory start.

feat(styleguide): added docs for writing stories

---

packages/brand-components/README.md
packages/styleguide/stories/About.stories.mdx
packages/styleguide/stories/Brand/About.stories.mdx

Per Slack discussions, aligned to how we're phrasing them in our internal talks.

feat(Styleguide): updated About examples and Brand description

---

packages/styleguide/stories/Foundations/Colors/Colors.stories.tsx

fix(styleguide): Corrected terrible couple/few typo in Platform colors

---

packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx

fix(Gamut): Fixed prettier issue on master

---

packages/gamut/src/Alert/index.tsx
packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx

I need to be able to position it using CSS.

feat(Gamut): Allowed Alert to receive a class name

---

packages/gamut/src/GridForm/types.ts

This gives component consumers more flexibility in styling their labels.
Separated from #807 
---

feat(GridForm): Update GridFormField label type to accept ReactNodes

---

jest.config.js
package.json
packages/gamut/src/Modal/__tests__/Modal-test.tsx
packages/gamut/src/Overlay/__tests__/Overlay-test.tsx
script/jest/rtl-setup.ts
yarn.lock

Broke out these tests from #806 because of the addition of react-testing-library
---

chore: Add RTL tests for modal and overlay

---

.github/pull_request_template.md

We [talked about it in Slack](https://codecademy.slack.com/archives/CQ98K8PT6/p1589559583180200) - Title is confusing; Overview is meaningful.
Not using the template on this one because it's Friday and I'm a rebel.

chore: Replaced 'Title' with 'Overview' in PR template

---

packages/gamut-labs/src/brand/Testimonial/styles.module.scss

fix styling of large full width testimonial card

style(Testimonial): fix full width styling

---

.circleci/config.yml

Just something i saw in the circle caching docs, might speed up builds a bit.
---

ci: run git gc before saving cache

---

.circleci/config.yml

ci: fix cache key so it falls back to master

---

packages/gamut/src/Form/styles/Checkbox.module.scss

feat(Gamut): Add focus state to Checkbox [GM-28]

---

package.json
packages/enzyme-helpers/CHANGELOG.md
packages/eslint-config/CHANGELOG.md
packages/gamut-icons/CHANGELOG.md
packages/gamut-labs/CHANGELOG.md
packages/gamut-styles/CHANGELOG.md
packages/gamut/CHANGELOG.md
packages/prettier-config/CHANGELOG.md
packages/styleguide/CHANGELOG.md
packages/webpack-config/CHANGELOG.md

Changelogs weren't being updated b/c husky doesn't install by default in CI

ci: run git hooks in CI

---

packages/gamut/src/GridForm/types.ts

Needed type change for https://github.com/codecademy-engineering/Codecademy/pull/18098

fix(CheckboxField): allow react nodes for checkbox description

---

packages/gamut/src/Video/index.tsx

add onPlay to video player so we can track when the user presses play on a video
---

fix(Video): add onPlay prop to Video for tracking purposes

---

packages/gamut-icons/.svgo.yml
packages/gamut-icons/package.json

chore(gamut-icons): update svgo config & fix format script

---

packages/gamut/src/Video/styles/index.module.scss

make video styling more flexible so you don't need custom styles when using the Video component in most places
see discussion here: https://github.com/codecademy-engineering/Codecademy/pull/17993#discussion_r446303509
---

fix(Video): make video styles more flexible

---

packages/styleguide/stories/Core/Foundations/Layouts/Elements/index.tsx
packages/styleguide/stories/Core/Foundations/Layouts/FlexContainer.stories.mdx

[Rebased from old PR](https://github.com/Codecademy/client-modules/pull/858)
Changelog weirdness

chore(Styleguide): Adds FlexBox story and configurable example [WEB-647]

---

packages/gamut/src/Alert/index.tsx

No aria label makes for no fun.

fix(Alert): Close alert button accessibility

---

packages/styleguide/stories/Core/Atoms/ToolTip.stories.mdx

fix: Fixed happy little syntax accident on tooltip story

---

packages/gamut/src/Alert/index.tsx

make the Alert component able to be tabbed into for the voiceover so the user knows that the close button and the message are contained within an alert box
added aria-label="message box" to give the user context on the stuff that is inside of it
also added the aria role="status" because it is a status box

fix(Alert): make alert tabbable for voiceover

---

script/update-changelog.js

Hey dawg, I heard you like changelogs...
Removing these noisy commits from the changelogs

chore: remove changelog updates from changelogs

---

README.md

It reads nicer and correctly numbers the steps 💅

docs(Readme): Fix "Working with pre-published changes" format

---

packages/webpack-config/package.json
yarn.lock

Bump `webpack-terser-plugin` to ^4 in webpack-config
Bump terser-webpack-plugin several major versions. There are some breaking changes in their [changelog](https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/CHANGELOG.md), but I don't think this affects the monolith or Author, as we were already explicitly setting the config changes that they changed defaults on.
I have run Author & the monolith against the alpha version of `webpack-config`.

build(webpack-config): [security] bump webpack-terser-plugin

---

packages/gamut-styles/src/variables/colors.ts
packages/styleguide/.storybook/Blocks/Swatches.tsx
packages/styleguide/stories/Core/Foundations/Colors/Colors.stories.mdx

This was overriding some of the old color names

fix(gamut-styles): move new colors to a namespace 

---

packages/gamut-labs/src/experimental/Box/constants.ts
packages/gamut-labs/src/experimental/Box/index.tsx
packages/gamut-labs/src/lib/breakpointHooks/index.ts

fix(Box): Fix imports and the variant

---

packages/gamut/src/Form/styles/Checkbox.module.scss
packages/gamut/src/Form/styles/Radio.module.scss
packages/gamut/src/Toggle/styles/index.module.scss

This was annoying.  Sorry for keeping it in so long.

fix(mixins): Fix deprecation warning for sr-only

---

packages/gamut/src/Typography/styles/_variables.scss

fix(typography): 18 => 16 px

---

README.md

Formalizing notes taken down in a brief pairing with @ianmunrobot earlier today.

docs: added docs for creating a new package

---

packages/markdown-overrides/package.json
packages/markdown-overrides/src/MathBlock/__tests__/MathBlock-test.tsx
packages/markdown-overrides/src/MathBlock/index.tsx
packages/markdown-overrides/src/MathBlock/styles.module.scss
packages/markdown-overrides/src/index.ts
yarn.lock

Add Katex/LaTex rendering `MathBlock` component.

feat(markdown-overrides): Add MathBlock component

---

packages/gamut-icons/src/svg/growth-icon.svg

- Getting no resolution on 3.8.1, need a patch bump.

fix(Icons): Trigger Republish

---

packages/gamut-styles/src/variables/spacing.ts

Still looking for a non existant 7.0.1

fix(Styles): Force republish on gamut-styles and downstream deps

---

packages/gamut-labs/src/brand/LogoProCutout/index.tsx
packages/gamut-labs/src/brand/ProLogo/index.tsx
packages/gamut/src/Layout/Column.tsx
packages/gamut/src/Layout/styles/Column.module.scss
packages/gamut/src/Layout/styles/_variables.scss
packages/styleguide/stories/Core/Layouts/LayoutGrid.stories.mdx

Result of pairing - thanks @codecaaron!
Adds rowspan logic to LayoutGrid. Also includes a small fix for colors in the ProLogo.

feat(LayoutGrid): Add rowspan to LayoutGrid

---

packages/gamut-labs/src/experimental/Box/index.tsx
packages/gamut-labs/src/experimental/Box/types.ts
packages/gamut-labs/src/experimental/Box/utils.ts

feat(Box): make ShadowOffset customizable

---

packages/gamut-icons/README.md

3.9.1 failed to publish to npm and excess newlines irk me.

chore: trim gamut-icons readme endlines

---

README.md

Noticed it when I wanted to check a publish job on CircleCI's site, and it 404d me...

docs: fix last RyzacInc reference in a README.md

---

packages/gamut-labs/src/experimental/Text/index.tsx
packages/gamut-labs/src/experimental/index.ts
packages/gamut-styles/package.json
packages/gamut-styles/src/index.ts
packages/gamut-styles/src/styled.ts
packages/gamut-styles/src/system.ts
packages/gamut-styles/src/theme.ts
packages/gamut-styles/src/theme.tsx
packages/gamut-styles/src/variables/typography.ts
packages/gamut-styles/tsconfig.json
packages/gamut-system/src/core/system/__tests__/system-test.ts
packages/gamut-system/src/core/system/index.ts
packages/gamut/src/Badge/index.tsx
packages/styleguide/.storybook/Blocks/Scale.tsx
packages/styleguide/.storybook/Blocks/TextExample.tsx
packages/styleguide/.storybook/decorators/theme.tsx
packages/styleguide/.storybook/preview.ts
packages/styleguide/stories/Core/Foundations/Typography/Typography.stories.mdx
packages/styleguide/stories/Core/Typography/Heading.stories.mdx
packages/styleguide/stories/Core/Typography/Text.stories.mdx
packages/styleguide/stories/Core/Typography/TextLabs.stories.mdx
yarn.lock

- Creates a basic theme and theme provider 
- Creates initial style functions
- Creates a basic text component
- Renames typography scale to singular scale.

feat(System): Labs Alpha

---

packages/styleguide/stories/Labs/Experimental/Atoms/Popover/Popover.examples.tsx

fix: corrected (Fill)Button import in Popover story

---

.gitignore

Vim users are people too, by some definition.
Not sure if this is a chore or a fix! Not sure if this requires a ticket! I'm new here!

chore: add vim temp files to .gitignore

---

packages/gamut-system/babel.config.js
packages/gamut-system/package.json
packages/gamut-system/src/core/system/index.ts
packages/gamut-system/src/transforms/parseSize/index.ts

Operator?  Can you help me place this call?  
Fix for gatsby upgrade https://github.com/codecademy-engineering/static-sites/pull/397/files

fix(system): Bad operator

---

packages/gamut-system/src/types/properties.ts

Forces republish and better immutable type reference.  No op.

fix(system): Use interface on property type

---

.github/workflows/automerge.yml
.github/workflows/pr-title.yml

limit pr actions to main branch, add filter to only run merge-disabled on labeled actions

ci: fix failed github actions on main branch

---

packages/gamut-styles/src/cache.ts

* Updates our cache key to something more unique to avoid other instances attempting to hydrate.

fix(emotion): change emotion style prefix to gamut

---

packages/gamut-labs/src/brand/ProLogoAlt/__tests__/ProLogoAlt-test.tsx

Previous import style was breaking `yarn build-all` for me for some reason? This fixes that issue and the tests still pass with relative imports so this should at least be more consistent with other tests now.

fix: use relative import for ProLogoAlt test

---

.circleci/config.yml

Fixes glob for test files in CircleCI

ci: fix test parallelism

---

packages/gamut-labs/src/landingPage/Description.tsx
packages/gamut-labs/src/landingPage/PageFeatures.tsx
packages/gamut-labs/src/landingPage/PageHero.tsx
packages/gamut-labs/src/landingPage/PagePrefooter.tsx
packages/gamut-labs/src/landingPage/Title.tsx

per feedback from Dev (and slack discussion last week), this PR includes the following:
* remove component margins + paddings
* make hero always render h1
* give Title and Description a default max width

fix: refine landing page ui

---

.circleci/config.yml

ci: build all packages before deploy to fix storybook type generation

---

packages/tracking/src/types.ts

Adding `module_slug` to UserClickData type as per [dashboard tracking spec](https://docs.google.com/spreadsheets/d/1a0TuL5lS7xadWA8fyO4jWMt3Q7JYy31kipTTcc89J7E/edit#gid=0)
I tested in the monolith with the alphabuild & checked in segment that the new user click data property shows. it works as desired!

feat(module_slug property type): add a new property to type UserClickData

---

packages/gamut/src/FlexBox/Container.tsx

as seen in [LayoutGrid](https://github.com/Codecademy/client-modules/blob/main/packages/gamut/src/Layout/LayoutGrid.tsx#L18). Not sure if most people care either way about this but it would make e2e testing the landing page builder a lil easier!

feat: add testId prop to Container

---

packages/gamut-illustrations/.npmignore

Added missing `.npmignore` to gamut-illustrations so it publishes the `dist/` folder, not `src/`.

fix: added missing .npmignore to gamut-illustrations

---

packages/styleguide/stories/Core/Typography/Anchor.stories.mdx

Improved documentation and references around accessible links in the `Anchor` docs.

docs: fleshed out Anchor (link) guidelines

---

packages/gamut/src/Toggle/index.tsx

Fixes a small typo, arial-label -> aria-label

fix(toggle): aria-label typo

---

packages/tracking/src/types.ts

Adding a new event with a category of page and a name of career_path_visited.

feat(tracking): Add a new page_career_path_visited event

---

packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLogo/__tests__/AppHeaderLogo-test.tsx
packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLogo/__tests__/AppHeaderLogoElement-test.tsx
packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLogo/index.tsx
packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/SharedStyles.tsx
packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/types.tsx
packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderLogo.stories.mdx

@katiezutter and I are breaking down our [mega AppHeader PR](https://github.com/Codecademy/client-modules/pull/1265) into smaller PR's containing the new components we added. This PR tackles the AppHeaderLogoItem and its related types + tests. 
As this is the first of these type of Pull Requests, 
Does the directory structure make sense? 
Do I need to add a storybook story for this?

feat(AppHeaderLogo): logo button AppHeaderElement

---

.gitignore

Sometimes there are random `report*.json` files that get automatically added to the diff and gets pushed up in commits. So this PR adds that to the `.gitignore` so we don't mistakenly add those to our commits by accident.

feat(tool): Adding a report*.json to .gitignore

---

packages/gamut/src/Markdown/index.tsx
packages/gamut/src/Markdown/libs/overrides/index.tsx

Wrapping the `MarkdownAnchor` in an anonymous functional component in the `Markdown` component's default 'a' tag override causes react to crash when certain plugins (like google translate) modify the dom and react tries to reconcile the changes.
Removing the wrapper fixes the issue, though I'm still not certain why this distinction matters. Welcome any thoughts about why this might be the case and if a different fix would be appropriate.
See the JIRA ticket for additional context
To test:
1. Install the alpha `gamut` package in a local copy of the monolith
2. Visit localhost:3000/courses/introduction-to-javascript/lessons/introduction-to-javascript/exercises/built-in-methods or any other lesson with an 'a' tag in the narrative content
3. Use google translate to change the page to a …

fix(Markdown): Don't wrap MarkdownAnchor component in tag overrides

---

.vscode/settings.json
.vscode/stories.code-snippets

Adding a few unopinionated story snippets to make creating stories simple.
* Adds vscode snippets for common storybook use cases.
* Ensures vscode file associations.
- `component-story`:  A basic story template with all of the imports and tab targets for standard information
- `toc-story`: Creates a basic index story with no component and a table of contents.
- `canvas-block`: Adds a canvas and story element that renders from args with a tab target for the story name and component.
1. In any MDX file start typing the prefix and you should see the autocomplete. 
2. Select the snippet
3. Fill out the tab indexes (in some of these you will fill out multiple things being filled out at the same time).

feat(Styleguide): Adds VScode snippets for new stories GM-137

---

packages/gamut/src/Form/Checkbox.tsx

Looks like we missed something in a recent change where we would override passed test ids accidentally.  This fixes that.
* Allow users to define `data-testid` without it being overwritten

fix(Checkbox): Remove overwritten data-testids on checkboxes

---

packages/styleguide/stories/Molecules/Interstitial.stories.mdx

docs: typo in focus copy

---

.eslintrc.js
packages/eslint-config/index.js
packages/styleguide/stories/Atoms/ButtonDeprecated/index.stories.mdx
packages/styleguide/stories/Atoms/Overlay.stories.mdx
packages/styleguide/stories/Foundations/Typography.stories.mdx
packages/styleguide/stories/Molecules/Accordion.stories.mdx
packages/styleguide/stories/Molecules/Modal.stories.mdx
packages/styleguide/stories/Molecules/SplitInterstitial/index.stories.mdx
packages/styleguide/stories/Organisms/GridForm.stories.mdx

A few little buggers.
* Re-enables no undef for *.mdx

fix(styleguide): Enable no jsx-no-undef on mdx

---

packages/gamut-labs/src/experimental/AppHeader/index.tsx

FillButton and TextButton were incorrectly imported, causing a compile error when trying to update Gamut in the monolith.

fix(import): Incorrect import in AppHeader

---

packages/gamut/src/Form/Checkbox.tsx
packages/styleguide/stories/Atoms/FormInputs.stories.mdx

Checkbox had a funky state with Checked + Disabled.  This fixes it and adds some stories to ensure that we can catch it.
* Ensures we have the correct disabled state for checkbox elements
Made a separate [PR](https://github.com/Codecademy/client-modules/pull/1317) to ensure we have all end states have some story level visual example to help is with the refactoring effort.

fix(Checkbox): Fixes :checked + :disabled styles

---

packages/gamut/src/AccordionArea/index.tsx
packages/gamut/src/AccordionArea/styles.module.scss
packages/styleguide/stories/Molecules/Accordion.stories.mdx

Re-adds the animation to accordions opening & closing

fix: re-add accordion animation

---

packages/styleguide/stories/Brand/Atoms/Avatar.stories.mdx

fix: scr => src

---

packages/gamut/src/Alert/__tests__/Alert-test.tsx
packages/gamut/src/Alert/index.tsx
packages/styleguide/stories/Molecules/Alert.stories.mdx

* Removes initialization lines and let Truncation escape out if not configured.

fix(Alert): Prevent JS test loop for line defaults

---

packages/gamut/src/AccordionArea/index.tsx
packages/gamut/src/Overlay/index.tsx

Uses `useIsomorphicLayoutEffect` instead of `useLayoutEffect` so React will stop complaining in SSR.
https://codecademy.slack.com/archives/CQ98K8PT6/p1611861223085600

fix: used useIsomorphicLayoutEffect instead of useLayoutEffect

---

packages/gamut/src/Pattern/defs.tsx
packages/gamut/src/Pattern/index.tsx
packages/styleguide/stories/Atoms/Pattern.stories.mdx

add dot patterns to Pattern component

feat(Pattern): add dot patterns

---

.vscode/extensions.json

* Adds eslint, prettier, and updates mdx extension recommendations

chore: Update recommended VScode extensions

---

packages/gamut/src/Interstitial/index.tsx
packages/styleguide/stories/Molecules/Interstitial.stories.mdx

Adds JSDoc comments to clarify props and updates storybook documentation.

docs(Interstitial): update Interstitial documentation

---

packages/gamut-labs/src/landingPage/Feature.tsx

Dev says it looks good and fixes the spacing issues brought up in QA today, so 🎉 
Made the change for both `ul` and `ol`

fix: remove indentation from lists in Feature descriptions

---

packages/gamut-labs/src/landingPage/Description.tsx
packages/gamut-labs/src/landingPage/Title.tsx
packages/gamut-labs/src/landingPage/variants.tsx

Consuming changes from https://github.com/Codecademy/client-modules/pull/1362 before I forget to do so! Future dark mode components should be pretty much drag + drop.

fix: use light variant by default

---

packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
packages/gamut/src/Video/styles/index.module.scss

style(Video): improved video focus outline

---

packages/gamut-labs/src/landingPage/PageFeatures.tsx

I took out the `xs` gaps because they never actually got applied as far as I could tell (it would switch to the single-column view at the same time). Dev says this is "perfect" 🙃

fix: increase feature column gaps

---

packages/gamut/src/AccordionButton/styles.module.scss

Reverts Codecademy/client-modules#1383

revert: fix(AccordionButton) bump specificity of accordion button styles

---

packages/styleguide/stories/Atoms/RadialProgress.stories.mdx

A PR that will merge into https://github.com/Codecademy/client-modules/pull/1351 with changes to the RadialProgress docs on Storybook.

Update animation example section

---

packages/variance/package.json
packages/variance/src/variance/__tests__/variance-test.ts
packages/variance/src/variance/core.ts

Adds CSS and Variants

---

packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
packages/gamut/src/ToolTip/__tests__/ToolTip-test.tsx
packages/gamut/src/ToolTip/index.tsx
packages/gamut/src/ToolTip/styles.module.scss
packages/styleguide/stories/Atoms/ToolTip.stories.mdx
packages/styleguide/stories/Atoms/TooltipArea.tsx

Reverted Emotion-ification of Tooltip. It needs more work.

chore: revert "converted ToolTip to Emotion"

---

packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx

add Projects link to GlobalHeader Resources dropdown menu

fix(GlobalHeader): add Projects link to Resources dropdown

---

packages/gamut-labs/src/experimental/Popover/index.tsx

- fixed bug pertaining to the popover pattern

fix: popover pattern expands to the size of its container

---

jest.config.js
packages/styleguide/.storybook/main.ts

Adds `gamut-illustrations` to the test/styleguide alias configs

test: add gamut-illustrations to test/styleguide alias configs

---

packages/gamut/src/NotificationListNew/index.tsx

NotificationListNew touch-ups.
Fixes for monolith PR: https://github.com/codecademy-engineering/Codecademy/pull/22305
1. Add horizontal padding on the dotted borders
2. Addresses the "each child does not have a unique key prop" error

fix(NotificationListNew): Key and spacing issues

---

packages/gamut-labs/src/experimental/Popover/index.tsx
packages/gamut/src/NotificationListNew/EmptyNotification/index.tsx
packages/styleguide/stories/Labs/Experimental/Molecules/Popover/Popover.examples.tsx
packages/styleguide/stories/Labs/Experimental/Molecules/Popover/index.stories.mdx

- Popover: add fallbackFocus option to focus trap (this is to prevent a default error that will be thrown if the focus trap contains no elements in its tab order)
Note: we were seeing this error in the monolith once we updated the notification dropdown with show all/clear all functionalities. since the empty notification did not have any focusable element anymore, it throws an error. With this option you can specify a fallback element to programmatically receive focus if no other tabbable elements are found. See more [here](https://github.com/focus-trap/focus-trap).
In the existing notifications list (that we will soon deprecate), the empty notifications text lives in a button (w/ no action). I presume this is to avoid that focus trap error. …

fix(popover): provide fallbackFocus

---

packages/styleguide/.storybook/components/PropsTable/constants.ts

* Adds the new export to the destructure

fix(Styleguide): Fixes destructuring for argtype enhances

---

packages/tracking/src/types.ts

not sure if a typescript edit is called style but couldn't figure out which one it should be
we need to add a new page event for marketing, so gotta update the types...
see https://github.com/codecademy-engineering/Codecademy/pull/22633

style(tracking): expand page event tracking type

---

packages/gamut-styles/babel.config.js

fix(styles): Run emotion plugin

---

packages/gamut-labs/src/experimental/HubCard/index.tsx
packages/gamut-labs/src/experimental/index.ts
packages/styleguide/stories/Brand/Atoms/HubCard.stories.mdx

Added a new Card component for HubPages
ScreenShots!

feat(HubCard): Created a new hub page card component

---

README.md

Added instructions for using `npm-link-better` instead of `yarn link`

chore(docs): add instructions for npm-link-better

---

README.md

docs: update readme to include gamut-kit version

---

packages/gamut/src/Modal/index.tsx

add an optional aria-label prop to the Modal component

fix(Modal): add aria-label prop

---

packages/gamut-labs/src/landingPage/PageHero.tsx
packages/gamut-labs/src/landingPage/PageHeroMedia.tsx

as a parting gift to us, Dev redesigned the video hero to address accessibility concerns. The video is no longer hidden on xs screens and instead just wraps to the next line
I also refactored slightly so that column sizes for the left and right hero columns are defined in the same file

feat(PageHero): don't hide video on xs screens

---

packages/styleguide/stories/Meta/FAQs.stories.mdx

@kipprice noted this might be misleading. Oof.

docs: corrected FAQ phrasing around external contributors

---

packages/gamut/src/Form/styles/FormGroupDescription.module.scss

Deleted one line of css to have FormDescriptions default to navy.

feat(FormDescription): it is now navy

---

.circleci/config.yml
codecov.yml

updates required builds for codecov to match CircleCI parallelism for tests (whoops!)
Also adds a goal % for the gamut package to at least keep it where it is now (89% ish)

ci: fix PR coverage issues due to parallelism

---

README.md

* Adds kit installation guide and peerDependency note

docs: add kit installation explanation and guide

---

packages/gamut/src/Pattern/index.tsx

Adds `aria-hidden='true'` to prevent patterns from being picked up by screenreaders.

fix: pattern should have aria-hidden

---

package.json
packages/gamut-styles/src/utilities/__tests__/themed-test.ts
packages/gamut-styles/src/utilities/index.ts
packages/gamut-styles/src/utilities/themed.ts
packages/gamut/package.json
packages/gamut/src/Form/FormGroup.tsx
packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx
packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
packages/variance/package.json
yarn.lock

Monolith PR: https://github.com/codecademy-engineering/Codecademy/pull/23364
Most actual changes are in the monolith change set. 
* Adds lodash like higher order function for looking up theme values in `styled` tagged templates.
* Gives us a simple way to ensure that code will always have values from the current context.
* Updates typescript to `4.2.3` to ensure number interpolation in paths.  We will need these for spacing and fontsizes to work.
* Updates `react-hook-form` to `6.8.5` for typescript compatibility.
* Updates some types and tests in GridForm to correctly update after the package bump.
* Updates some unit tests that might have more asynchronous behavior to RTL to ensure that internal RHF hooks fire correctly.
```tsx
import { themed } from '@codecademy/gamut-styles';
const …
```

chore(Dependencies):  Upgrade TS / RHF to enable `themed` function [WEB-1370] [WEB-1371] [GM-191]

---

packages/variance/package.json
packages/variance/src/__tests__/variance-test.ts
packages/variance/src/core.ts
packages/variance/src/transforms/parseSize.ts
packages/variance/src/types/config.ts
packages/variance/src/types/props.ts
packages/variance/src/utils/__tests__/propNames-test.ts
packages/variance/src/utils/propNames.ts

Adds static style methods to variance.  These eventually will support pseudo selectors but do not currently.
Creates `css` and `variant` functions that are typed and locked to the specific configuration.
```tsx
const config = { m: { property: 'margin' }, p: { property: 'padding' } } as const
const varianceInstance = variance.withTheme(theme);
const variant = varianceInstance.createVariant(config);
const css = varianceInstance.createCss(config);
```
A standalone theme aware method that accepts and object of system props and returns the correct style object. Is cached after being called with theme once, preventing more expensive calculations.
**Usage**
```tsx
const CoolStuff = styled.a(css({ 
margin: [16, 24],
}))
```
Built on top of `css` function but with our old variant API syntax …

feat(Variance): Static CSS Methods `css` and `variant`  [WEB-1116]

---

packages/variance/package.json

chore(deps): Don't update emotion version

---

packages/gamut/src/NotificationListNew/index.tsx

Tuba pointed out that the top pattern line was actually supposed to be static and below the title

fix(NotificationListNew): remove top pattern

---

packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CompanyLinks.tsx

We haven't set up the /shop redirect yet so it's a 404.

fix: corrected GlobalFooter shop link

---

packages/gamut-labs/src/index.ts

fix(labs): Fix missing exported type

---

packages/gamut-labs/src/Popover/__tests__/Popover-test.tsx
packages/gamut/src/Dialog/index.tsx
packages/gamut/src/NotificationList/NotificationItem.tsx
packages/gamut/src/Pattern/defs.tsx
packages/gamut/src/Pattern/index.tsx
packages/styleguide/stories/Atoms/Pattern.stories.mdx
packages/styleguide/stories/Molecules/Coachmark/index.stories.mdx
packages/styleguide/stories/Molecules/Popover/Popover.examples.tsx

add new dotLoose pattern and rename old dots patterns to checker
separating this change out from #1646 so that it is not a blocker for the goal settings project
(adding the rest of the new patterns is less urgent, so for this PR we will just add the new dot pattern that we need for the goal settings project)
here is the follow-up pr in the monolith to update all the places where the dots pattern is used https://github.com/codecademy-engineering/Codecademy/pull/23833

feat!: add new dot Pattern and rename old dots to checker

---

packages/tracking/src/types.ts

Adds additional properties (`goal_setting` and `longterm_goal`) to user click data for goal setting.
See tracking doc for reference: https://docs.google.com/spreadsheets/d/1lWs2B2k3uFwvdnoRdyqsw4c2sK_-XZBl1Mdj_6P7mn0/edit#gid=0
See related monolith PR: https://github.com/codecademy-engineering/Codecademy/pull/23826
- add additional properties (`goal_setting` and `longterm_goal`) to user click data for goal setting

refactor: add additional properties to userclickdata

---

packages/gamut-styles/src/cache/index.ts

* Fixes hot reloading issues with constructed stylesheets, this change ensures that unregistered styles will persist through reloads regardless of cache instance.

chore: Turn off constructed stylesheets in dev

---

packages/gamut-styles/src/cache/index.ts

* Re added constants that were lost.

fix: cache constants missing

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx

Add link to Codecademy Affiliate Program to Global Footer

feat(Global Footer): add affiliate program link

---

packages/gamut/src/Button/ButtonOutline.tsx
packages/gamut/src/Button/CTAButton.tsx
packages/gamut/src/Button/FillButton.tsx
packages/gamut/src/Button/IconButton.tsx
packages/gamut/src/Button/StrokeButton.tsx
packages/gamut/src/Button/TextButton.tsx
packages/gamut/src/Button/shared.ts

* Fixes circular dependency that would cause colors to be undefined occasionally.

fix: Circular dependency on ButtonOutline Broke focus states

---

packages/gamut-labs/src/GlobalPage/index.tsx
packages/gamut-styles/src/Background.tsx
packages/gamut-styles/src/ColorMode.tsx
packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
packages/gamut/src/AppWrapper/index.tsx

* Use Pagewrapper with a restricted background for GlobalPage that extends AppWrapper.

feat(PageWrapper): Extend stacking context reset element for pages with a background color

---

packages/eslint-config/index.js
packages/gamut-labs/src/ErrorContents/__tests__/ErrorContents-test.tsx
packages/gamut-labs/src/ErrorContents/index.tsx
packages/gamut-labs/src/index.ts
packages/styleguide/stories/Molecules/ErrorContents.stories.mdx

Takes in roughly the same `ErrorContents` from the monolith so we can use it in portal-app.

feat: added error page contents for 500 errors

---

packages/gamut/src/Form/SelectDropdown.tsx
packages/gamut/src/Form/styles/shared.tsx

OG designs unintentionally showed a pointer for our Input components, I've switched them back to the default behavior

fix(Input): cursor weirdness

---

packages/gamut/src/Form/utils.tsx

fix(Select): add labels back 

---

packages/gamut-labs/src/CurriculumCard/index.tsx

Capitalize text prop in CurriculumCard with CSS instead of having to manipulate the string

style(CurriculumCard): Capitalize text prop

---

packages/gamut/src/Form/utils.tsx

Reverts Codecademy/client-modules#1744

Revert "fix(Select): add labels back "

---

packages/gamut/src/Form/__tests__/__snapshots__/utils-test.tsx.snap
packages/gamut/src/Form/__tests__/utils-test.tsx

* adds simple snapshot to validate our parse function returns correct label / value stuff.

test: Add deterministic snapshot to option formatting

---

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
packages/gamut-labs/src/GlobalHeader/types.tsx
packages/styleguide/stories/Organisms/GlobalHeader.stories.mdx

This leverages the checkout url both for trial and non-trial upsells in the header (tryProForFree and upgradeToPro) instead of routing upgradeToPro to the pro membership landing page
integration branches: https://github.com/codecademy-engineering/Codecademy/pull/24432, https://github.com/codecademy-engineering/static-sites/pull/776, https://github.com/codecademy-engineering/portal-app/pull/40

feat(Header)!: reroute header upsell for upgrade

---

packages/gamut/src/Form/Input.tsx

this PR makes sure our hidden fields don't create empty space inside of the gridform. I have some screenshots of the issue in the ticket below.

fix(Input): fixed hidden field empty spaces

---

packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/__tests__/GridFormRadioGroupInput-test.tsx
packages/gamut/src/GridForm/types.ts
packages/styleguide/stories/Atoms/FormInputs/Radio.stories.mdx
packages/styleguide/stories/Organisms/GridForm.stories.mdx

Change type of label for Radio item in GridForm from string to ReactNode.
Outcome of pairing with @dreamwasp !
Closing #1785 to go with this implementation instead.
To see the reason for this change, check the Edit Profile page in the preview environment in https://github.com/codecademy-engineering/Codecademy/pull/24825:
`https://pr-24825.dev-eks.codecademy.com/profiles/\<your-username\>/edit`
There you'll see a tooltip on the Only me name privacy radio option.

feat(GridForm): Allow ReactNode for GridForm Radio label

---

packages/gamut/src/SkipToContent/index.tsx

fix: SkipToContent z :( 

---

packages/gamut/src/SkipToContent/index.tsx

This fails most axe checks as it is not part of the header currently.  Ostensibly it could be in the future but currently we need to have a specified landmark for this content. 
https://www.w3.org/TR/wai-aria-practices/examples/landmarks/region.html
This uses the aria-labelledby strategy for role="region".
* This ensures that we have a descriptive landmark for skip-to-content.

fix: Set region and label on STC

---

packages/variance/integration/__tests__/component-test.tsx
packages/variance/src/core.ts

Some how I figured out a way to throw all those object mutability lessons out the window and Object.assign theme to a a nested of object literal reference :).  This meant the theme would be added to the previous static object and returned as CSS even if the parser ignored it. 
Normally this wouldn't be an issue if you called `system.css` with an object literal as the response would be cached from the first call - preventing the mutability issue: 
```tsx
system.css({
m: 4,
'&:hover': {
bg: 'blue',
}
})
```
However if you used the object between multiple `css` functions the select configuration would be mutated by the first call the create the cache and causing the second css function to attempt to include theme as styles:
```tsx
const hoverStyles = {
'&:hover': {
bg: 'blue',
}
}. as const; …
```

fix(variance): Fix static css mutability for `css` [GM-235]

---

packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
packages/gamut/src/GridForm/__tests__/stubs.ts
packages/gamut/src/GridForm/types.ts
packages/styleguide/stories/Organisms/GridForm.stories.mdx

Adds `rowspan` prop to GridFormFields for layout customization

feat(GridForm): rowspan fields 

---

packages/gamut-icons/icon-template.js
packages/gamut-icons/src/props.ts

* Implements should forward prop for the svg tag manually to avoid HTML issues.

fix: Filter non forwardable props on icons

---

packages/gamut/src/Button/ButtonInner.tsx

* Adds width 100% to ButtonInner to make buttons resizable.

fix: ButtonContainer should grow to fit its parent [GM-238]

---

packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
packages/styleguide/stories/Organisms/GridForm.stories.mdx

return custom-group with a `Column` wrapper

fix: custom-group 

---

.eslintrc.js
packages/gamut-labs/src/SocialMediaSharing/SocialShareIconLink.tsx
packages/gamut-labs/src/SocialMediaSharing/__tests__/SocialMediaSharing-test.tsx
packages/gamut-labs/src/SocialMediaSharing/index.tsx
packages/gamut-labs/src/index.ts
packages/styleguide/stories/Molecules/SocialMediaSharing.stories.mdx

Ports the [SocialMediaSharing](https://github.com/codecademy-engineering/Codecademy/tree/develop/webpack/assets/portal/components/SocialMediaSharing) component over from the monolith. Offloads tracking to the consumer via an `action` prop, similar to [GlobalHeader](https://github.com/Codecademy/client-modules/blob/main/packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx#L32)
Notes:
- The `small` label text size is 14 instead of 12 since the latter is no longer valid per our styleguide, but I found no usages that had both a `small` and a `label` prop
- Per conversation with Li I have dropped the hover styles for the `white` version of the component as
- it used the [deprecated](https://gamut.codecademy.com/storybook/?path=/docs/foundations-colors--page#deprecated-col …

feat: add SocialMediaSharing component

---

packages/styleguide/.storybook/components/Docs/DocsContainer.tsx
packages/styleguide/.storybook/components/Docs/DocsPage.tsx
packages/styleguide/.storybook/components/Navigation/BreadCrumbs.tsx

* Fixes the smooth scrolling for story links across story pages
* Fixes breadcrumb spacing (types are borked here)
No Padding

fix: Fix story link scrolling and breadcrumbs spacing

---

packages/styleguide/stories/Organisms/GridForm.stories.mdx

de-dupe names + ids of our GridForm fields in docs to clean up the console output

docs(GridForm): dedupe ids + names

---

packages/gamut/src/Form/styles/shared-system-props.tsx
packages/styleguide/stories/Atoms/FormInputs/Radio.stories.mdx

fixes this oops (thankfully only visible to admins):

fix(Radio): fix background color

---

packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx

* Refactors LayoutMenu to use Anchor instead of Accordion button.
https://user-images.githubusercontent.com/52927224/122478595-b2b2b680-cf97-11eb-964e-4a5f853ecd6b.mov
Before: 
After:

fix(LayoutMenu): Emotion Only GM-258

---

packages/tracking/src/events/types.ts

There is a need to sometimes know which repo a tracking event is being fired from. This PR adds that key to the type.
[Reference](https://codecademy.slack.com/archives/C8XDQUD8A/p1624290067106500)

feat(tracking): Added repo-tracking to user events

---

packages/gamut/src/Form/FormGroupLabel.tsx
packages/styleguide/stories/Atoms/ToolTip.stories.mdx

fix: ToolTip icons can't be aria-hidden

---

packages/gamut-icons/icon-template.js
packages/gamut-icons/src/props.ts
packages/gamut/src/Form/FormGroupLabel.tsx
packages/styleguide/stories/Atoms/ToolTip.stories.mdx

Bugs caused by `aria-labelledby=""` and unexpect prop ordering.  Will have a PR for the ordering fix (size should be below width / height).
* Fixes default empty string for titleId
* Switches to defaulting width / height as prop sorting is not behaving correctly.

fix: Icon titleId and Size Defaults

---

packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
packages/gamut-labs/src/GlobalHeader/types.tsx

Added more specific typing to the AppHeader.props.onLinkAction item param

feat(GlobalHeader): Added the better type for the link handler

---

packages/tracking/src/events/types.ts

This PR aims to add types for [two existing custom events](https://github.com/codecademy-engineering/business-reporting/blob/develop/src/util/eventTracking/index.tsx#L104-L110) that are in the business_reporitng and now looking to be in `event_definitions`. So this PR goes hand in hand with ➡️ https://github.com/codecademy-engineering/Codecademy/pull/25679

feat(event type): adding business reporting types

---

packages/tracking/src/events/types.ts

Merged PR earlier but some typos.
https://github.com/Codecademy/client-modules/pull/1893

fix: business reporting event types

---

packages/gamut/src/ProgressBar/index.tsx
packages/styleguide/stories/Atoms/ProgressBar/constants.tsx
packages/styleguide/stories/Atoms/ProgressBar/index.stories.mdx

The ProgressBar component has a `large` size that's entirely too big for new designs. The only place this size is used is in the Syllabus, which is currently being replaced. This PR updates the `large` size to meet the new size requirements for the progress bar, while still supporting the bigger size as `xl`
**[Here's the discussion in slack](https://codecademy.slack.com/archives/CTVEHH2PP/p1623437989075900) **
- Halves size of `large` variant
- Creates `xl` variant with old giant size to support old syllabus design
- Storybook:
- Adjusts ProgressBar layout to show new variant (4th column), and adjust to smaller screen sizes
- Adds variants as headings in the size display (feel free to tell me to remove these 😄 )
- Reduces size of ProgressBar's `large` variant
- Adds `xl` variant to …

feat(progress bar)!: reduces size of large variant, creates xl for old size

---

packages/tracking/src/events/types.ts

This PR updates the business tracking event name. Follow up to https://github.com/Codecademy/client-modules/pull/1893.

feat(tracking): Update business event name

---

packages/gamut/src/ProgressBar/index.tsx

Sets `ProgressBar` pattern background to transparent
Before:
After:
Note: this will currently only work where pattern svg's use currentColor, and don't have a background fill color set

feat(progress bar): overrides bg color to transparent when pattern is defined

---

packages/gamut/src/Form/Checkbox.tsx
packages/gamut/src/Form/__tests__/Checkbox-test.tsx
packages/gamut/src/Form/styles/shared-system-props.tsx
packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx
packages/styleguide/stories/Atoms/FormInputs/Checkbox.stories.mdx
packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
packages/styleguide/stories/Atoms/FormInputs/examples.tsx
packages/styleguide/stories/Foundations/ColorMode/examples.tsx

refactoring Checkboxes to be controlled components + related documentation. [monolith integration PR](https://github.com/codecademy-engineering/Codecademy/pull/25850)

feat!: Controlled Checkboxes 

---

packages/gamut/src/Form/styles/shared-system-props.tsx

fix(colors): hover + focus form states GM-281

---

packages/styleguide/stories/Layouts/Box/index.stories.mdx

* Removes unnecessary html from Box docs page - as this was breaking after 6.3 update.

fix: Fix box stories

---

packages/gamut/src/Form/Form.tsx
packages/gamut/src/Form/FormWrapper.tsx
packages/gamut/src/Form/SelectDropdown.tsx

Adds system props to Form + FormWrapper

feat: add system props to form + formwrapper

---

packages/gamut-styles/src/ColorMode.tsx
packages/gamut/src/Card/index.tsx

Oops (I don't think anything uses it without a shadow though)
* Fixes default border.

fix: Default Card Border

---

packages/gamut/src/Menu/MenuItem.tsx

Updated the Icon size for the Condensed variant of MenuItem

fix: Updated icon sizes for condensed MenuItems

---

packages/gamut/src/GridForm/GridFormButtons/index.tsx
packages/styleguide/stories/Organisms/GridForm.stories.mdx

Removed deprecated business button from GridForm submit options 
Will add corresponding monolith PR momentarily 😎

refactor(GridForm)!: remove business button

---

packages/variance/integration/__tests__/variance-test.ts
packages/variance/src/core.ts
packages/variance/src/scales/createScaleLookup.ts

* Array scales didn't trigger transformation flow for values.  This explicitly adds a check explicitly for arrays and adds a test to validate the behavior.
* Improves logic for looking up scalar values with a hof that returns the appropriate logic (computations were unnecessarily checking the types of scales)
* Splits out helpers to a separate file.

fix(variance): Ensure array scales always qualify for transformation

---

packages/styleguide/.storybook/components/Markdown/Elements.tsx
packages/styleguide/.storybook/components/Navigation/NavigationProvider.tsx
packages/styleguide/.storybook/components/Navigation/types.ts
packages/styleguide/.storybook/components/Navigation/utils.ts
packages/styleguide/.storybook/getStories.ts
packages/styleguide/stories/Layouts/Box/GridBox.stories.mdx
packages/styleguide/stories/Layouts/Box/index.stories.mdx

* Let's you specify `component="Box"` et al on our custom storybook internal link which sends you to our best guess story.  This may not work for components that are not directly specified as a `component={X}` on a stories' meta configuration.
Usage:
```tsx
<LinkTo component="Box">Box</LinkTo>
```

feat(styleguide): Allow component level links

---

packages/gamut-styles/src/themes/admin.ts
packages/gamut-styles/src/variance/utils.ts

VSCode strikes again
* Fixes bad import path

fix: Import path 

---

packages/gamut-labs/src/GlobalFooter/FooterLinks.tsx
packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/lib/resourcesList/index.ts

adds cc docs links to resources list in footer and header
Header
Footer

feat(footer): add link to docs resources footer and header

---

packages/styleguide/stories/Molecules/Modals/Dialog.stories.mdx
packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx

Updated documentation and Figma links to the `Modal` and `Dialog` stories

docs: Updated Modal documentation and Figma links

---

packages/gamut/src/Form/SelectDropdown.tsx

add react-select onInputChange to our SelectDropdown, will add documentation + tests on a follow-up PR as this is blocking

feat(SelectDropdown): onInputChange

---

packages/gamut/src/Form/__tests__/SelectDropdown-test.tsx
packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx

Adds docs and test to SelectDropdown for onInputChange

docs(SelectDropdown): onInputChange

---

package.json
packages/gamut-system/src/core/system/index.ts
packages/markdown-overrides/src/MathBlock/index.tsx
yarn.lock

* Updates TS to 4.4.2
* Fixes breaking union in gamut system
* `catch` errors now treated as `unknown` rather than `any`

chore: Typescript Bump

---

packages/gamut-labs/src/Avatar/__tests__/avatar-test.tsx
packages/gamut-labs/src/Avatar/index.tsx

Add a `size` prop to the `Avatar` component

feat(Avatar): add size prop

---

packages/gamut/src/Form/Checkbox.tsx
packages/styleguide/stories/Atoms/FormInputs/examples.tsx

Ran into a couple automated axe failures and implemented a better cross-browser solution.

fix(Checkbox): Safari + Firefox accessibility but better this time 

---

packages/gamut/src/Card/index.tsx
packages/styleguide/stories/Atoms/Card.stories.mdx

- feat: adds color mode to card
- adds color mode to cards which applies dynamic wrapper that uses color mode.
https://www.figma.com/proto/enGqhyq9xlbkCkJLArNWeR/Refine?node-id=423%3A920&scaling=min-zoom&page-id=417%3A550&starting-point-node-id=420%3A759

feat(Card)!: Add color mode to card

---

packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx
packages/gamut-labs/src/lib/resourcesList/index.ts

Temporarily removing cc-docs from header and footer

refactor(header): remove cc-docs from header and footer

---

packages/gamut/src/GridForm/GridFormInputGroup/__tests__/GridFormInputGroup-test.tsx
packages/gamut/src/GridForm/GridFormInputGroup/index.tsx

Inadvertently broke this - I have fixed + added tests.

fix(GridForm): custom errors

---

packages/gamut-labs/src/LandingPage/PageHero.tsx
packages/gamut-labs/src/LandingPage/__tests__/Hero-test.tsx
packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx

Adds optional eyebrow text to the `PageHero` component used in the landing page builder

feat(PageHero): add optional eyebrow text

---

packages/gamut-labs/src/GlobalHeader/types.tsx

feat: adding `isBusinessAdmin` field to User type

---

README.md

Clarifies where to find new module versions in the README.md notes.

docs: clarified version number mention in README.md

---

packages/gamut/src/BodyPortal/index.tsx

* Fixes inset getting mangled on firefox.

fix: F firefox

---

packages/gamut/src/Markdown/styles/_mixins.scss

Fixes color for markdown bullets in dark mode.

fix(Markdown): fix bulletpoint color

---

packages/styleguide/stories/Atoms/Markdown/index.stories.mdx

Changes default `spacing` prop in `Markdown` story

docs(markdown): Update markdown story

---

packages/gamut/src/Form/FormGroupLabel.tsx

Need to export this type in order to style with emotion or gamut-styles, oops.

fix(FormGroup): export interface from FormGroup

---

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/styles.module.scss
packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/SharedStyles.tsx
packages/gamut-labs/src/AppHeader/Search/SearchPane.tsx
packages/gamut-labs/src/AppHeader/index.tsx
packages/gamut-labs/src/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/MobileSearchBar.tsx
packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
packages/gamut-labs/src/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
packages/gamut-labs/src/AppHeaderMobile/AppHeaderSubMenuTarget/index.tsx
packages/gamut-labs/src/AppHeaderMobile/index.tsx
packages/gamut-labs/src/GlobalHeader/index.tsx
packages/gamut-labs/src/Popover/index.tsx
packages/styleguide/stories/Organisms/GlobalHeader.stories.mdx

Adding Dark Mode to GlobalHeader ahead of schedule for Voniel and CfB

feat(GlobalHeader): [GM-399] Adding dark mode to GlobalHeader and all child components

---

packages/gamut/src/DataList/Controls/FilterControl.tsx
packages/gamut/src/DataList/Controls/SelectControl.tsx
packages/gamut/src/DataList/DataList.tsx
packages/gamut/src/List/List.tsx
packages/gamut/src/List/__tests__/List-test.tsx
packages/gamut/src/List/elements.tsx
packages/gamut/src/List/types.ts
packages/styleguide/stories/Organisms/Lists & Tables/DataTable.stories.mdx
packages/styleguide/stories/Organisms/Lists & Tables/List/index.stories.mdx
packages/styleguide/stories/Organisms/Lists & Tables/examples.tsx

accessibility tweaks + variant naming changes for Lists + Tables

Lists & Tables: edits

---

packages/gamut-labs/package.json
packages/gamut-labs/src/Drawer/index.tsx
packages/gamut/package.json
packages/gamut/src/Motion/FadeInSlideOut.tsx
yarn.lock

Bumped `framer-motion` to v4.
Corresponding monolith PR: https://github.com/codecademy-engineering/Codecademy/pull/27137

chore!: bumped framer-motion to v4

---

packages/gamut/src/DataList/DataGrid.tsx

adds a loading state for when the DataGrid has no rows[] (yet)

feat(DataGrid): default empty loading state

---

README.md

Replace a broken link in the README.
New link found here https://github.com/lerna/lerna

docs(readme): fix lerna link

---

.circleci/config.yml
.eslintignore
.github/workflows/push.yml
packages/gamut-labs/package.json

Uses GitHub Actions instead of CircleCI for some simpler push jobs.
- ~[ ] Related to JIRA ticket: ABC-123~ _(there were a few heh)_

chore: used GitHub Actions for simpler CI push jobs

---

packages/gamut/src/List/types.ts

fix(List): add block type to private list prop type

---

.github/CODEOWNERS

chore: clean up codeowners file

---

packages/gamut/src/List/ListRow.tsx

- add aria-label to expanded row as landmark should have unique label

fix(ListRow): add expandedRowAriaLabel prop to ListRow

---

packages/gamut/src/DataList/Rows/Row.tsx

fixes justify prop for row text

fix(DataGrid/DataTable): text align bug

---

packages/gamut/src/NotificationList/NotificationItem.tsx
packages/styleguide/stories/Molecules/NotificationList.stories.mdx

- add new image type for cohort notifications

feat(NotificationItem): add notification image for cohorts

---

packages/gamut-labs/src/lib/resourcesList/index.tsx

Add 'New' badge to videos in the header resources list.
Related to the gamut feature to add the 'New' label: https://github.com/Codecademy/gamut/pull/2181

refactor(header): add new flag to videos in header resources

---

packages/gamut/src/DataList/DataGrid.tsx
packages/gamut/src/DataList/types.ts

Just adding a few comments to help future devs figure out things that were not immediately clear from the component API.
Added in-line comments for data table components to help future us's.

feat(DataTable): prop comments

---

packages/styleguide/stories/Atoms/Button/index.stories.mdx
packages/styleguide/stories/Atoms/ToolTip.stories.mdx
packages/styleguide/stories/Molecules/Alert/index.stories.mdx

Fixed the "Writing Tips" links in Storybook, linking components to their proper guidance pages.

docs: Fixed "Writing Tips" links in Storybook

---

packages/styleguide/.storybook/components/Navigation/utils.ts

I left this in while debugging this code with stephen, oops.

fix:  Docs: remove console.log from getKinds

---

packages/gamut-labs/src/InfoCard/index.tsx

- Adds titleHeadingLevel as prop
- Replaces deprecated Truncate component

refactor(InfoCard): use text truncate; add titleHeadingLevel as prop

---

README.md

chore: add more context to turborepo in readme

---

packages/gamut/src/Pagination/PaginationButton.tsx

Adds aria-hidden to `hidden` pagination buttons
Fixes axe failures on disco PR [here](https://github.com/codecademy-engineering/Codecademy/pull/29639), ty @j10sanders for catching this!

fix(Pagination): aria-hidden added for hidden buttons

---

packages/gamut/src/Menu/MenuItem.tsx

Adds rel to MenuItem anchor type
Relevant to [this work](https://github.com/codecademy-engineering/Codecademy/pull/29822/files) on LE dropdowns + menus

feat(MenuItem): add rel to MenuItem anchor type

---

packages/gamut/src/Markdown/__tests__/Markdown-test.tsx
packages/gamut/src/Markdown/libs/overrides/MarkdownAnchor/index.tsx

Prevent links with no href in Markdown from crashing the component

fix: Allow links with no href in Markdown

---

packages/gamut-labs/src/CurriculumCard/index.tsx

One line fix to make this check less brittle

fix(CurriculumCard): made career goal checking less brittle

---

packages/gamut-labs/src/DropdownButton/__tests__/DropdownButton-test.tsx
packages/gamut-labs/src/DropdownButton/index.tsx

- Add horizontalKebab button type

feat(DropdownButton): add horizontal kebab

---

packages/gamut/src/List/List.tsx

- Adds `overflowHidden` prop to List to conditionally set overflow to 'hidden' if this prop is true

feat(List): add overflowHidden prop to List

---

packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx
packages/gamut-labs/src/lib/resourcesList/index.tsx
packages/styleguide/stories/Organisms/GlobalHeader.stories.mdx

If a user is in the new Catalog dropdown feature flag test (useNewCatalogDropdown is true), they should not see “Challenges” and “Projects” in the Resources dropdown because we will have these items in the new Catalog dropdown.
control experience:
variant experience:

feat(AppHeader): hide projects and challenges in nav variant

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
packages/gamut-labs/src/GlobalFooter/__tests__/GlobalFooter-test.tsx
packages/gamut-labs/src/GlobalFooter/index.tsx
packages/gamut-labs/src/GlobalPage/__tests__/GlobalPage-test.tsx
packages/gamut-labs/src/LogoFromSkillsoft/index.tsx
packages/styleguide/stories/Atoms/LogoFromSkillsoft/LogoFromSkillsoft.stories.mdx
packages/styleguide/stories/Molecules/GlobalFooter.stories.mdx

Cleans up footer feature flag things + adds story for new FromSkillsoftLogo

refactor(Footer + FromSkillsoftLogo): clean up + add story

---

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx

This is purely meant as a hot-fix for CI failures -- this catalog dropdown will be fully navigable by keyboard with an upcoming disco ticket 
monolith [here](https://github.com/codecademy-engineering/Codecademy/pull/30373)
portal [here](https://github.com/codecademy-engineering/portal-app/pull/1847)

fix(AppHeaderCatalogSection): hot fix for CI failures

---

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/types.tsx

Adding a check to hide the account + billing for all Business SSO users including all Skillsoft users. This is because users that are SSO'd don't need the other account options besides Goal settings.
PR related to this change: https://github.com/codecademy-engineering/Codecademy/pull/30354

feat(GlobalHeaderItems): Business Sso check for profile

---

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
packages/gamut-labs/src/lib/catalogList/__tests__/index-test.tsx
packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx

Tests for AppHeaderCatalogDropdown and Resources

test(AppHeaderCatalogDropdown): add unit tests for resources and catalog dropdown items

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx

Creating an anchor for use by our Refer-A-Friend program

feat(GlobalFooter): Add Extole marketing anchor

---

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/__tests__/AppHeaderCatalogDropdown-test.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx

Adds keyboard functionality to the new catalog header dropdown, utilizing some previously written code and changing somethings about the approach so it can function with our new catalog dropdown.
you can test this by going to the catalog variant
`?path=/docs/organisms-globalheader--free-user-in-catalog-dropdown-variant`
and keyboarding around using the arrow keys

feat(AppHeaderCatalogDropdown): adding keyboard functionality

---

.github/pull_request_template.md

Proposed changes to PR template - should be able to ✂️  after mono-repo work 🔥 
| Portal       | [Portal PR](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another PR](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

docs: proposed changes to PR templates

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx

fix(CompanyLinks): Wrap extole zone in a footer item

---

.github/workflows/announce-release.yml

things to look at:
- [slack release bot action](https://github.com/homeday-de/slack-release-bot-action)

feat(release notes): test slack bot notifs

---

.github/workflows/announce-release.yml
packages/gamut/src/Pagination/index.tsx

basically, wanna cut down on the noise of the package updates while keeping gamut-kit versions notifications (since they are perpetually relevant) 
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ …

feat(automated releases): add version bump only filter

---

.github/workflows/automerge.yml
packages/styleguide/stories/Atoms/Button/index.stories.mdx

I **_think_** my changelog descriptions haven't been picked up by the regex because of newline characters. This *should* work with or without newline characters.  I tested it [here](https://regex101.com/r/2am3md/1) + it seems to work 🤷 
Adds optional newline character to automerge commit regex and a tiny docs change.
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | …

ci: tweak automerge regex

---

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/__tests__/AppHeaderCatalogDropdown-test.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx

Axe Bug 1: 
[A] Screen Reader: Headings in Catalog menu are not marked up semantically as such
http://codecademy.test.io/products/9763/test_cycles/98728/bugs/1945138
Axe Bug 2:
[A] Screen reader:The title of the first section is missed and not announced
http://codecademy.test.io/products/9763/test_cycles/98728/bugs/1944593
Axe Bug 3: 
[A] Screen Reader: Related links are not grouped in a list
http://codecademy.test.io/products/9763/test_cycles/98728/bugs/1945160
Test that each of these issues have been remedied. 
| Monolith …

fix(AppHeaderCatalogDropdown): axe fixes

---

packages/gamut-labs/src/HorizontalScrollMenu/index.tsx

Fixes an issue (of my own creation) where if two scroll menus are on the same page only one of them will display contents since we're querying document rather than within our ref. 
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | …

fix(HorizontalScrollMenu): fixing multiple root observer query issue

---

packages/gamut/src/Tabs/Tab.tsx
packages/gamut/src/Tabs/TabButton.tsx
packages/gamut/src/Tabs/TabList.tsx
packages/gamut/src/Tabs/TabNav.tsx
packages/gamut/src/Tabs/TabNavLink.tsx
packages/gamut/src/Tabs/TabProvider.tsx
packages/gamut/src/Tabs/Tabs.tsx
packages/gamut/src/Tabs/styles.tsx
packages/styleguide/stories/Molecules/Tabs/Tabs.examples.tsx
packages/styleguide/stories/Molecules/Tabs/index.stories.mdx

Adds new variant of Tabs, to be used in the LE
monolith PR: https://github.com/codecademy-engineering/Codecademy/pull/30638
and specific places where tabs are currently used (should have no changes vs prod):
https://pr-30638-monolith.dev-eks.codecademy.com/learn/learn-java
https://pr-30638-monolith.dev-eks.codecademy.com/search?query=Python
See new changes here:
https://627568cbae4bd524c881807f--gamut-preview.netlify.app/?path=/docs/molecules-tabs--tabs (scroll down to LE Variant section)

feat(Tab): add block variant

---

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
packages/gamut-labs/src/GlobalHeader/types.tsx
packages/styleguide/stories/Brand Labs/Organisms/GlobalHeader.stories.mdx

| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/30642 '#30642')  | [Monolith Env](https://pr-30642-monolith.dev-eks.codecademy.com/ 'Monolith PR Env') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/1948)  | [Portal Env](http://www.google.fr/ 'Named link title')   |

feat: Add pricing link option to global header

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/styleguide/stories/Brand Labs/Organisms/GlobalFooter.stories.mdx

renames chat nav link to "discord", adds discord link to footer, adds spacing between footer sections
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/30818)  | [Monolith Env](https://pr-30818-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal PR](https://github.com/codecademy-engineering/portal-app/pull/1993)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1993)   |

feat(GlobalHeader): Rename Chat to Discord

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx

[DISC-643](https://codecademy.atlassian.net/browse/DISC-643): 
Change "Pro pricing" in the top navigation to be "Pricing". This includes the dropdown and the link that also says "Pro Pricing" for users in India. 
[DISC-644](https://codecademy.atlassian.net/browse/DISC-644): 
Add "For Teams" to the pricing dropdown. Acceptance criteria:
- Link should be placed last, after “individuals” and “students”
- Section should link to: https://www.codecademy.com/business#section-pricing-table
- Tracking = `topnav_pricing_business`
- Change existing "For Business" next to "Pricing" to be "Business Solutions" (in footer as well). …

refactor(GlobalHeader): pricing dropdown updates

---

packages/gamut-labs/src/AppHeader/Search/SearchPane.tsx

Test io Link: http://codecademy.test.io/products/9763/test_cycles/68776/bugs/1434395
1. With VoiceOver, go to https://www.codecademy.com/catalog
2. Tab to search press Enter
3. Tab to "Data science"
4. The "popular searches" should now be read as links and not buttons. 
_Initially I thought to do this with an `Anchor` but that altered the styling and messed with the `onClick` logic. Using `role` seems like the best solution for this._
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31 …

fix(AppHeader/SearchPane):  Axe - Popular Searches link are identified as button

---

packages/gamut-labs/src/CurriculumCard/Difficulty/types.ts
packages/styleguide/stories/Molecules/Popover/Popover.examples.tsx
packages/styleguide/stories/Molecules/Popover/index.stories.mdx

Popover story broke, this should fix it.

fix(Popover): Fix Popover story

---

packages/gamut/src/Modals/Modal.tsx

- adding aria-live polite on Modal Container to announce content change inside modal
Updated! ~~(will update with link when alpha package is published)~~
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31197 'Named link title')  | [Monolith Env](https://pr-31197-monolith.dev-eks.codecademy.com/ 'Named link title') | …

fix(Modal): add aria-live polite

---

packages/gamut-labs/src/LandingPage/Feature.tsx
packages/gamut-labs/src/LandingPage/PageSingleFeature.tsx
packages/gamut-labs/src/LandingPage/__tests__/SingleFeature-test.tsx
packages/styleguide/stories/Brand Labs/Organisms/PageSingleFeature.stories.mdx

Updating the image component the ``PageSingleFeature`` to act as a a link if provided with a url.
1. Visit https://tengu.codecademy.com/api/portal/preview?path=pages/business&PR_ENV=portal-app-pr-2236
2. scroll to the "Close the gaps" gap section and click on the image
3. ensure that it navigate you to https://trial.codecademy.com/en-us/motleyfoolcasestudy?source=blp
4. Visit https://tengu.codecademy.com/pages/career-center?PR_ENV=portal-app-pr-2236
5. scroll to the "Do it all with Codecademy Pro" and ensure that you can't click on the image …

feat(PageSingleFeature): Allow image to act as a link

---

README.md
packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx

This PR adds the "Business Solutions" header link for Pro and Trial users to the `GlobalHeader`. Prior to this PR the link only appears for free users but not Pro or Trial.
1. Follow each step as a Pro, Trial and Free user
2. visit the catalog page on the portal app env, and the dashboard page on the monolith env
3. Notice the "Business Solutions" link in the header.
4. Click it make sure it takes you where it should.
5. ...
6. Profit!
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/3 …

fix(GlobalHeader): add `business solutions` for Trial / Pro learners

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx

Update the global footer link for the Pro Membership page to point to the new marketing page at "/pages/pro" instead of the old "/pro/membership"
1. Visit preview environment for monolith + portal app
2. Scroll down to footer
3. Click on Pro Membership
4. Note that the pages goes directly to pages/pro and doesn't first try pro/membership then redirects
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31637)  | [Monolith …

refactor(GlobalFooter): update pro membership footer link

---

packages/gamut/src/Badge/index.tsx
packages/styleguide/stories/Atoms/Badge.stories.mdx

Add navy stroke option. This is specifically for the new pricing page design where the available gray stroke option does not meet accessible contrast standards against pale yellow and yellow backgrounds.
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link …

feat(Badge): add navy stroke variant

---

packages/gamut-labs/src/AppHeader/index.tsx

Links and dropdowns were not aligned in the GlobalHeader. Links were slightly lower than the dropdowns.
**Before**
**After**
Visit https://62eabcdb5abaff12ad10dbb6--gamut-preview.netlify.app/?path=/docs/brand-labs-organisms-globalheader--global-header and see that there is alignment in all the different variants. 
You can also see the alignment on the PR envs linked below. 
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/31909)  | [Monolith …

style(GlobalHeader): Fix misalignment of links and dropdowns

---

.github/CODEKNOWERS
.github/CODEOWNERS
.github/workflows/auto-request-reviews.yml

Updates our automatic review assignment stuff to not make the gamut team required on lockfile-only changes (ie: dependabot) and assigns them to the @Codecademy/dependencies team for triage. 
Remove mandatory CODEOWNERS from yarn.lock and gamut-labs
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | …

chore: Remove mandatory CODEOWNERS from yarn.lock and gamut-labs

---

packages/gamut-styles/src/variables/deprecated-colors.ts
packages/gamut-styles/utils/variables/_colors.scss

update $color-editor-red
as part of this [hackathon project](https://github.com/codecademy-engineering/Codecademy/pull/30492) to add line highlighting in markdown code blocks, we want to make $color-editor-red slightly lighter so that it maintains a 4.5:1 contrast ratio to the background of the highlighted lines
so the new contrast ratio is [4.52:1](https://webaim.org/resources/contrastchecker/?fcolor=EA6C8B&bcolor=2B2D40)
got the 👌  from stephen on this!
an example code block with the new red text color and highlighted lines: …

style(Colors): update color-editor-red

---

packages/gamut-illustrations/src/Announcement.tsx
packages/gamut-illustrations/src/index.ts

feat(Illustration): add AnnouncementIllustration

---

packages/gamut-labs/src/GlobalHeader/index.tsx

Just a small DRYing up of two functions that have similar return types.
Make sure to delete cookies (for exp assignment) and view https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2426 as an anonymous user.  Can also add youself to the experiment for the logged in version https://app.optimizely.com/v2/projects/21056540090/experiments/22003060387/whitelist. Everything should just work, there is no visible change - just a refactor.
https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2426

refactor(GlobalHeader): DRY up HeaderItems

---

packages/gamut/src/ToolTip/ToolTip.tsx

We are using a lot of floating tooltips in a new portal app page, but SSR nextjs throws a lot of warnings having to do with the use of `useLayoutEffect` inside FloatingTooltip.
> ⚠️ Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer’s output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
- This PR is a small update to prevent FloatingTooltip to render in SSR. Followed React's suggestions to lazily show the component. Which in our case works pretty well since we can fallback to the non-floating tooltip on SSR.
The …

fix(Tooltip): fix useLayoutEffect ssr warning

---

packages/gamut-labs/package.json
packages/gamut/package.json
packages/monaco/package.json

Update build:watch tasks to work with NX

chore: fix build:watch tasks

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
packages/gamut-labs/src/GlobalFooter/FooterNavLinks/__tests__/CompanyLinks.test.tsx
packages/gamut-labs/src/GlobalFooter/FooterNavLinks/index.tsx
packages/gamut-labs/src/GlobalFooter/__tests__/GlobalFooter.test.tsx
packages/gamut-labs/src/GlobalFooter/index.tsx
packages/gamut-labs/src/GlobalPage/__tests__/GlobalPage.test.tsx
packages/styleguide/stories/Brand Labs/Organisms/GlobalFooter.stories.mdx
packages/styleguide/stories/Brand Labs/Organisms/GlobalPage.stories.mdx

Remove link to shop from footer
Verify that the shop link does not appear in the footer
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32257)  | [Monolith Env](https://pr-32257-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal PR](https://github.com/codecademy-engineering/portal-app/pull/2490)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2490)   |

feat(Footer): remove shop link from footer

---

packages/gamut/src/Modals/Modal.tsx
packages/gamut/src/Modals/types.ts
packages/gamut/src/Overlay/index.tsx

This change:
- Modifies the Overlay's shroud prop to have color `shadow-black-heavy` as specified in the mocks (shown in the pic above)
- Stephen mentioned that we want all overlays to have this opacity
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link …

feat(Modal): change overlay shroud opacity and make modals use dark by default 

---

packages/gamut/src/ConnectedForm/__tests__/useDebouncedField.test.tsx
packages/gamut/src/ConnectedForm/utils.tsx

1. Fixes `useGetInitialFormValue` to better keep the behavior of useField by setting string fields without a initialValue to `""` by default instead of `undefined`
2. Fixes `useMakeSetFormDirty` logic so that the form can be re-dirtied after a submission. 
3. Updates unit tests
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32299)  | [Monolith Env](https://pr-32299-monolith.dev-eks.codecademy.com/ 'Named link title') |
| …

fix(useDebouncedField): fixing helpers logic

---

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader.test.tsx
packages/gamut-labs/src/lib/resourcesList/index.tsx

**Style**
Switch the course and career sections, so that popular course topics appear first.
Iterate the UI of the “See full catalog” CTA 
Introduce a new section for beginners
Include the user_click event: - Context: global_nav - Target: sorting_quiz
**Copy**
Update section titles and descriptions. 
The subdescription for "popular course topics" and "Docs" sections also need updating. Should be:
Popular course topics --> Explore free or paid courses in topics that interest you.
Docs (in resources menu) --> Find definitions, code syntax, and more -- or contribute your own code documentation.
Interact with the catalog dropdown menu noting the design matches figma (approved by Mark and Tamar) and there is no weird behavior on any screen size. 
The easiest way to test is on …

style(GlobalHeader): Catalog Dropdown V3 updates

---

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/types.tsx

We want to feature flag the `Business Account Management` profile menu item for skillsoft users. This PR adds two fields, one to check for a skillsoft user and the other to check if the feature flag to show the BAM in the menu is on or off.
To test just need to confirm that the `GlobalHeader` has the two new fields (`isSkillsoftUser` and `skillsoftBamProfileFeatureFlag`) under `user`:
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32255)  | [Monolith Env](http://www.google.fr/ …

feat(GlobalHeader): Add business logic for Skillsoft users for BAM profile menu item

---

packages/gamut-illustrations/src/Syllabus.tsx
packages/gamut-illustrations/src/index.ts

Add new syllabus illustration to gamut-illustrations
Storybook preview: https://6310c33e7d610305e2b67d62--gamut-preview.netlify.app/?path=/docs/atoms-illustrations--editable-illustration
| Portal App     | [Portal App PR](https://github.com/codecademy-engineering/portal-app/pull/2507)  | [Portal App Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-2507) |
[EGG-2769]: https://codecademy.atlassian.net/browse/EGG-2769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

feat(SyllabusIllustration): add new illustration

---

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/types.tsx

fix(GlobalHeader): BAM profile menu changes Revert

---

packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx

As is, most of the modal sections crash if you click on them directly (i.e., [Scrollable](https://gamut.codecademy.com/?path=/docs/molecules-modals-modal--scrollable)). There is nothing wrong with the code, but this seems to be a bug with storybook mdx not rendering children correctly. 
If I wrap the modal around the necessary child props, it works. This does not change anything regarding the usage, simply how we are rendering the story. 
It also gets rid of the deprecated `showCloseButton` wherever I noticed it. 
Click all of the following sections under the modal and make sure they work and do not crash.

fix(modals): fixing children in modals

---

packages/gamut/src/AccordionArea/index.tsx
packages/gamut/src/List/ListRow.tsx

Fixes e2e failures on monorepo e2e tests re: [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#rows) 
Remove aria-expanded from div
| Another Repo | …

fix(AccordionRow, ListRow): remove incorrect aria-expanded

---

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/types.tsx

This PR adds logic to check `hideBusinessAccount` which is a feature flag to show/hide the BAM for skillsoft users.
Check the monolith and pull down the branch to test it locally with the instructions in the monolith PR.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32255)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull …

feat(GlobalHeader): Update business logic for BAM profile menu

---

packages/gamut-labs/src/DropdownButton/DropdownList.tsx

Outcome of pairing with @dreamwasp and @mstykmshy.
Accessibility fix: add focus to dropdown list items.
This is a stopgap solution until [WEB-1769](https://codecademy.atlassian.net/browse/WEB-1769) is picked up and dropdown interactions from the global header can be split out and shared with `DropdownButton`.
Two PRs have been opened in the monolith and portal-app using the alpha package - please check the testing instructions in both of these PRs to ensure the behavior is correct in the places we are using the dropdown button. …

fix(DropdownList): Make dropdown list items focusable

---

.github/CODEOWNERS

removes stephen from codeowners file
Gamut team should still be auto-added to this PR

chore(CODEOWNERS): rm stephen from codeowners file

---

packages/gamut-labs/src/DropdownButton/index.tsx

Co-authored-by: Saj <sking@codecademy.com>
Adds aria-expanded to DropdownButton.
Check both monolith and portal-app PRs to ensure that your screenreader is narrating the expanded/collapsed state of the dropdown menus.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32690)  | [Monolith Env](https://pr-32690-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/207)  | [Portal …

fix(DropdownButton): Add aria-expanded to dropdown buttons

---

packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderResourcesDropdown/index.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderResourcesSection/index.tsx
packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
packages/gamut-labs/src/AppHeader/index.tsx
packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
packages/gamut-labs/src/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
packages/gamut-labs/src/AppHeaderMobile/index.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader.test.tsx
packages/gamut-labs/src/GlobalHeader/types.tsx
packages/gamut-labs/src/lib/resourcesList/__tests__/index.test.tsx
packages/gamut-labs/src/lib/resourcesList/index.tsx
packages/styleguide/stories/Brand Labs/Organisms/GlobalHeader.stories.mdx

V3 experiment is complete and we are confident in moving forward with the variant, let's remove the useNewCatalogDropdown and default to the new Catalog and Resources dropdowns.
Check out the PR envs and make sure you see the new dropdowns for Catalog and Resources.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32742)  | [Monolith Env](https://pr-32742-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal …

refactor(GlobalHeader): Clean up experiment in favor of variant

---

packages/gamut-labs/src/lib/catalogList/index.tsx

capitalize S in JavaScript in catalog dropdown
before (screenshot from prod):
after (storybook)
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another …

fix(GlobalHeader): capitalize S in JavaScript in catalog dropdown

---

packages/gamut/src/Toggle/index.tsx
packages/gamut/src/Toggle/utils.tsx

We have a toggle button inside of a connected form, which is causing issues because the toggle button submits the form. Setting the toggle as `type='button'` fixes it. …

feat(Toggle): Set toggle as type button when set as button

---

packages/gamut-labs/src/HorizontalScrollMenu/index.tsx

In `HorizontalScrollMenu` component, cards were vanishing when swiping too quickly. 
Removed the css logic that would hide the element from view if its `ariaHidden` label was set to true. 
Bug is only happening on iOS devices. 
In an **_iOS_** mobile device or simulator:
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33084)  | [Monolith Env](https://pr-33084-monolith.dev-eks.codecademy.com/) |
| Monorepo      | [Mono Link](https://github.com/codecademy-engineering/mono/pull/411)  | …

fix(HorizontalScrollMenu): Do not visibly hide cards when their ariaHidden is true

---

packages/gamut/src/Toggle/__tests__/Toggle.test.tsx
packages/gamut/src/Toggle/index.tsx
packages/gamut/src/Toggle/types.tsx
packages/gamut/src/Toggle/utils.tsx
packages/styleguide/stories/Atoms/Toggle.stories.mdx

Update the label prop type to accept ReactNode.
Open Storybook preview, go to Toggle section, observe the new example using `<Text>` for label
| Portal       | [Portal](https://github.com/codecademy-engineering/mono/pull/499)  | [PR Env](https://tengu.codecademy.com/checkout?PR_ENV=portal-app-pr-499)  |
| Monolith       | [Monolith](https://github.com/codecademy-engineering/Codecademy/pull/33300)  | [PR Env](https://pr-33300-monolith.dev-eks.codecademy.com/)  |

feat(Toggle): allow react node for labels

---

packages/gamut/src/Card/index.tsx
packages/styleguide/stories/Atoms/Card.stories.mdx

1. Visit https://63728851ba286c0a4370716f--gamut-preview.netlify.app/?path=/docs/atoms-card--card
2. Confirm there is a beige variant shown with the other color variants
3. Confirm there is a box shadow variant and that the shadow itself inherits the base card's color
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/33482)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal …

feat(Card): Have outline shadow variant to inherit variant color

---

packages/gamut/src/Markdown/__tests__/Markdown.test.tsx
packages/gamut/src/Markdown/libs/overrides/Checkbox/index.tsx

Updates the markdown component tests to stop using enzyme.
Because of the nature of the tests, they can't be easily replicated with the standard RTL API. A lot of the tests involve testing for specific tags and html formatting which isn't recommended with RTL but is the correct thing to test with this component. I recreated those tests by using native DOM operations like `document.querySelector` and used RTL selectors when I could.
| Monolith     | [Monolith …

chore: Remove Enzyme from Markdown component tests

---

.circleci/config.yml
lerna.json

Adds the `--exact` option when publishing to pin dependent versions instead of making them semver compatible with `^`
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | …

chore!: Use exact mode with Lerna to prevent unintentional upgrades

---

packages/gamut-labs/package.json
packages/gamut/package.json
yarn.lock

Revert upgrades to auto-id and react-use

revert: upgrades to auto-id and react-use

---

packages/gamut-labs/package.json
yarn.lock

Hard to test, but I'm confirming that it's working by:
1. Viewing that it's able to read the type correctly in the Score Summary component, the one component that is using tracking for types. 
2. Testing it out in storybook locally
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal …

chore(deps): bump tracking from 0.26.0 to 1.0.1

---

packages/gamut-labs/src/RatingsBar/index.tsx

Adds stroke between yellow bar and white background
1. Bring up storybook locally.
2. Visit http://localhost:6006/?path=/docs/brand-labs-atoms-ratingsbar--ratings-bar
3. Confirm you see a stroke between the yellow bar and white background
[REACH-2264]: https://codecademy.atlassian.net/browse/REACH-2264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(RatingsBar): Adds stroke between yellow bar and white background

---

packages/gamut-labs/src/ScoreSummary/index.tsx
packages/styleguide/stories/Brand Labs/Organisms/ScoreSummary.stories.mdx

add optional description prop to ScoreSummary component …

refactor(ScoreSummary): add optional description text

---

packages/gamut-labs/src/RatingsBar/index.tsx

Fixes the focus on the RatingsBar wrapper
1. Visit http://localhost:6006/?path=/docs/brand-labs-atoms-ratingsbar--ratings-bar
2. Turn VoiceOver on. Navigate to the ratings bar component.
3. Confirm the focus outline surrounds the entire ratings bar and VO announces the %, ratings bar, and level indicator (which is the meter role).
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/708)  | [Portal …

fix(RatingsBar): fixes the focus on the wrapper

---

.vscode/extensions.json
packages/gamut-labs/src/index.ts
packages/styleguide/stories/Brand Labs/Organisms/LayoutMenuVariant.stories.mdx

add exports for LayoutMenuVariant components

chore: export LayoutMenuVariant

---

packages/styleguide/.storybook/main.ts
packages/styleguide/package.json
packages/styleguide/tsconfig.json
yarn.lock

chore: fix gamut website JSX transform

---

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx

In preparation for the plan rename, update these CTAs to be plan name agnostic!
Update Global Header CTAs
Visit https://638e6415fc1d981175570a3e--gamut-preview.netlify.app/?path=/docs/brand-labs-organisms-globalheader--global-header and check out the 'Free User' variants
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link …

feat(global header): update copy for plan rename

---

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader.test.tsx
packages/gamut-labs/src/GlobalHeader/types.tsx
packages/styleguide/stories/Brand Labs/Organisms/GlobalHeader.stories.mdx

This reverts commit 18b35ba009ae1443afac4c56f55c0678169debb5.
Reverts the change to add a pricing link to the global header that shows up instead of the pricing dropdown in India
| Another Repo | …

revert: "feat: Add pricing link option to global header"

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx

Global Footer: rename Pro Membership -> Paid Memberships in preparation for Plan Rename.
Visit https://6390c693f35ef8489c171899--gamut-preview.netlify.app/?path=/docs/brand-labs-organisms-globalfooter--global-footer and see that the link reads 'Paid Memberships'
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title') …

feat(Footer): rename Pro Membership link

---

packages/gamut-labs/src/QuizScore/index.tsx
packages/gamut-labs/src/ScoreSummary/index.tsx

- Make `trackSlug` optional and refactor Review Concepts link to only show if `trackSlug` is present
- Make tracking optional in ScoreSummary since it's only used for Review Concepts link which is now optional
- Use `Math.round()` for QuizSummaryscore calculation instead of `Math.floor()`
Test in storybook. Optionally you can also test in [this portal-app preview environment](https://tengu.codecademy.com/career-journey/full-stack-engineer?PR_ENV=portal-app-pr-788) where the changes will be used.
- Test that score rounding is working right in storybook by setting the `totalCorrect` and `totalQuestions` props to something that would have a different result from `Math.floor()` and `Math.round()`. For example,`totalCorrect=2` and `totalQuestions=3` should result in a score of `67`, not `66`. …

refactor(ScoreSummary): make trackSlug and tracking optional in ScoreSummary

---

packages/gamut-labs/src/PageAlerts/PageAlerts.tsx

Update width of PageAlert component to match ContentContainer breakpoints
1. Visit https://63989c9b101e36571979499c--gamut-preview.netlify.app/?path=/docs/brand-labs-organisms-pagealerts--page-alerts
2. Use the test buttons to add alerts to the page
3. Ensure the new styling looks good
4. You can also check out how it looks in portal app by following the instructions in the PR linked below
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/851)  | [Portal …

fix: update width of page alert to match page contents

---

packages/gamut-labs/src/QuizScore/index.tsx
packages/gamut-labs/src/ScoreSummary/index.tsx
packages/styleguide/stories/Brand Labs/Organisms/ScoreSummary.stories.mdx

make ScoreSummary component responsive
- below medium breakpoint, row layout ScoreSummary becomes a column layout
- add a noMaxWidth prop for use on the career journey syllabus page, so that the ScoreSummary expands to the full width of the container
1. Look at the ScoreSummary component in the storybook
2. Check that the row layout ScoreSummary component becomes a column layout below the medium breakpoint
3. Profit!
| Monolith     | [Monolith …

refactor(ScoreSummary): make ScoreSummary responsive

---

packages/gamut/src/Drawer/index.tsx
packages/styleguide/stories/Molecules/Flyout.stories.mdx

Currently, if flyout overflows, the background color only extends to the bottom of the screen and on scroll is transparent. This fixes that.
Look at the new Flyout story for with overflow and confirm the background color stays on scroll
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34039)  | [Monolith Env](https://pr-34039-monolith.dev-eks.codecademy.com) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/912)  | [Portal …

fix(Flyout): move background color to fix overflow

---

packages/gamut-labs/src/lib/resourcesList/index.tsx

Update links to blog in resource list.
- `yarn start`
- Go to http://localhost:6006/?path=/docs/brand-labs-organisms-globalheader--global-header
- Click "Resources" on the header
- Verify that the "Career advice" link goes to `/resources/blog/category/career/` and the "Learning tips" link goes to `/resources/blog/category/learning-tips/`
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34303)  | [~Monolith …

feat(resourcesList): update blog links in global header

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx

Go to https://63d058fa4a9e5547a63ca9a7--gamut-preview.netlify.app/?path=/docs/brand-labs-organisms-globalfooter--global-footer and check that the `Paid Memberships` link now has a URL of `/pages/paid-plans` …

feat(GlobalFooter): Change 'Paid Memberships' URL to '/pages/paid-plans'

---

packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CatalogLinks.tsx

The career related landing pages are now live so this PR adds in the links to them
Visit the preview environments, scroll down to the footer and ensure the new career related links are present and clickable.
The 3 new links are to:
https://codecademy.com/pages/career-services
https://codecademy.com/pages/interview-prep
https://codecademy.com/pages/pro-certifications
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34503) …

fix(GlobalFooter): show new career building links in footer

---

packages/gamut/__tests__/__snapshots__/gamut.test.ts.snap
packages/gamut/package.json
packages/gamut/src/Video/index.tsx
packages/gamut/src/utils/index.ts
packages/gamut/src/utils/useIsMounted.ts

React player causes hydration errors in React 18. It barely actually server-rendered anything before, so our solution is to prevent it from rendering server-side. Because of how we do the styles, the spaces where the videos will go still has the correct width/height, so this doesn't cause any unnecessary layout shifts. 
Prevent react-player from rendering server-side for React 18 compatibility
1. Open the Portal PR preview, go to https://tengu.codecademy.com/pages/pro?PR_ENV=portal-app-pr-1224
2. Note that there are no warnings in the console for unminified react errors
(for now you may need to test this locally by pulling down the [portal branch](https://github.com/codecademy-engineering/mono/pull/1224))
| Repository   | PR Link                                                  | PR Env …

fix: React 18 react-player compatibility

---

packages/gamut/src/Form/SelectDropdown/SelectDropdown.tsx
packages/gamut/src/Markdown/index.tsx

* Suppress hydration warnings on the markdown component (we'll work on a permanent fix)
* Supply a default id to `react-select` to avoid SSR id mismatches based on their internal id generation 
| …

fix: React 18 updates for hydration warnings

---

packages/gamut-labs/src/CareerPathCard/index.tsx
packages/gamut-labs/src/ContentGroupBaseCard/index.tsx
packages/gamut-labs/src/CourseCard/index.tsx
packages/gamut-labs/src/SkillPathCard/index.tsx

Remove `minWidth` and `minHeight` (card should adapt to whatever container it is in).
1. Mono branch: Check that the catalog, hub pages, and full catalog page look the same as production on desktop, tablet, and mobile screen sizes.
2. Monolith: Check that the homepage goals cards look the same as production on desktop, tablet, and mobile screen sizes.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34760)  | [Monolith Env](https://pr-34760-monolith.dev-eks.codecademy.com/) |
| Mono …

refactor(ContentGroupBaseCard): Sizing 

---

.vscode/settings.json

MDX [supports intellisense now](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx) -- this enables that setting. 
Intellisense should be enabled in .mdx files ✨

style: enable mdx intellisense

---

packages/gamut-labs/src/AppHeader/index.tsx
packages/gamut-labs/src/AppHeaderMobile/index.tsx
packages/gamut-labs/src/HeaderHeightArea/index.tsx

In storybook, inspect the AppHeader and see that it has an `aria-label` instead of a `title` attribute.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34774)  |   |
| Portal       | [Portal PR](https://github.com/codecademy-engineering/mono/pull/1321)  |  |
[REACH-2506]: https://codecademy.atlassian.net/browse/REACH-2506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(AppHeader): Change title to aria-label

---

packages/gamut-labs/src/ContentGroupBaseCard/index.tsx

1. Open storybook and go to ContentGroupBase card where you will now see space between the description and metadata 
2. Mono: Visit catalog and hub pages to make sure cards look the same as prod
3. Monolith: Visit homepage, dashboard, and onboarding quiz to make sure cards look the same as prod
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/34826)  | [Monolith Env](https://pr-34826-monolith.dev-eks.codecademy.com/) |
| Mono       | [Mono …

refactor(ContentGroupBaseCard): Add margin between description and metadata on small cards

---

packages/gamut/src/ButtonDeprecated/styles/mixins.scss

For color-brightness function, sum all rgb values before dividing by 1000 (to convert from 0-1000 to 0-1 scale)
This function is used in legacy buttons to determine whether a background is light or dark so that we know if we should use black or white text for contrast. Since blue was already given a small weight, this fix does not make a significant functional difference. If we had edge color cases for the deprecated button, then we would see fixes, but we do not have any such cases.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35201) …

fix: order of operations for color-brightness function

---

packages/gamut-labs/src/GlobalPage/__tests__/GlobalPage.test.tsx

I'm an idiot and forgot to push up the commit for tests from https://github.com/Codecademy/gamut/pull/2698
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another …

test(GlobalPage): add tests for optional footer

---

packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader.test.tsx

Changes 'My Percipio' to 'Home' in enterprise header variant
Visit https://64276f11a6d9130f65ddb3a0--gamut-preview.netlify.app/?path=/docs/brand-labs-organisms-globalheader-enterprise--enterprise and confirm the text says "Home" on desktop and mobile view
| …

feat(GlobalHeader): Update enterprise home text

---

packages/gamut-labs/src/QuizScore/index.tsx

Fixes a visual bug on Safari in the ScoreSummary component.
Before:
After:
1. Test that the bug has been fixed in the Storybook preview for Chrome, Firefox, and Safari
2. Test that the bug has been fixed in the monolith (cumulative assessment + section exam summaries in the LE, career path syllabus pages)
3. Test that the bug has been fixed in the monorepo (career journey syllabus pages)
| Monolith     | [Monolith …

fix(ScoreSummary): Fix Safari ScoreSummary border bug

---

package.json
packages/styleguide/package.json
yarn.lock

bump webpack-config package in order to use dart sass
(no gamut kit alpha package generated)

feat(webpack-config): bump in order to use dart sass

---

packages/gamut-labs/src/PlanCard/PlanFeature.tsx

The previous color (gray-600) was too light and failed accessible contrast requirements. This darker color (text-secondary/navy-600) passes.
| Another Repo | [Another Link](http://www.google.fr/ …

fix(PlanCard): use darker color for crossed-out features

---

packages/gamut-labs/src/PageAlerts/types.ts
packages/gamut-styles/src/Background.tsx
packages/gamut-styles/src/ColorMode.tsx
packages/gamut/src/Alert/Alert.tsx
packages/gamut/src/Alert/variants.tsx
packages/styleguide/stories/Molecules/Alert/constants.tsx
packages/styleguide/stories/Molecules/Alert/index.stories.mdx

1. Go to the author PR env, see the subtle alert on an enterprise module page, under the linked content tab if you are apart of the staging optimizely feature flag : `author_percipio_gating`
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35209)  | [Monolith Env](https://pr-35209-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/1567)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-1567) …

feat(Alert): Add subtle light and dark variants to inline alerts

---

packages/gamut-labs/src/ScoreSummary/index.tsx

- Unhides checkmark and x icons in ScoreSummary with the `colorfulIcons` prop and gives them an aria label
Instructions in monolith PR:
1. Complete a cj exam (for example `/exams/journeys/full-stack-engineer/paths/fscj-22-interview-prep/parts/1`) and move to the results screen
2. Navigate the results using VoiceOver and ensure labels are announced for the checkmark or x icons next to each unit
The icons in the list of units tested should be announced, since they communicate information (whether you got 70% of the questions in that unit right). The icons in the section above next to the "X correct/ X to work on" section shouldn't be announced since they don't add any information that isn't communicated by the text.
| Repository …

fix(ScoreSummary): Add labels to informative icons

---

packages/styleguide/.storybook/components/ChatWindow/components/Chat.tsx
packages/styleguide/.storybook/components/ChatWindow/components/ChatBox.tsx
packages/styleguide/.storybook/components/ChatWindow/components/elements.tsx
packages/styleguide/.storybook/components/ChatWindow/index.tsx

chat message styling 🔥 

---

packages/styleguide/.storybook/components/ChatWindow/components/Chat.tsx
packages/styleguide/.storybook/components/ChatWindow/components/ChatBox.tsx
packages/styleguide/.storybook/components/ChatWindow/components/elements.tsx
packages/styleguide/.storybook/components/ChatWindow/index.tsx

styling and animations

---

packages/gamut/src/ProgressBar/index.tsx
packages/styleguide/stories/Atoms/ProgressBar/index.stories.mdx

Adds a border to yellow variant for accessibility color contrast and consolidates light and dark variants into one default variant using color mode.
View https://6452b42fd441bc14765a4d3a--gamut-preview.netlify.app/?path=/docs/atoms-progressbar--progress-bar and confirm all progress bars have an outline
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35568)  | [Monolith Env](https://pr-35568-monolith.dev-eks.codecademy.com) |
| Portal       | [Portal …

feat(ProgressBar)!: add border to yellow variant and use color mode

---

packages/gamut-icons/src/svg/regular/person-filled-icon.svg

Adds PersonFilledIcon to gamut-icons
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/2034)  | [Portal Env](https://tengu.codecademy.com/resources/docs/markdown/code-blocks?PR_ENV=portal-app-pr-2034)   |
[REACH-2678]: https://codecademy.atlassian.net/browse/REACH-2678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(Icon): add PersonFilledIcon

---

packages/gamut-labs/package.json
yarn.lock

Bumping @codecademy/tracking to 1.0.9
The [monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35670) should pass all linting errors and not complain about the new tracking Event type, `submission_recommendation`.
Both PR envs should produce no errors when navigating `/welcome/find-a-course`
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35670)  | [WAITING FOR Monolith Env](http://www.google.fr/ 'Named …

fix: tracking bump to ver 1.0.9

---

packages/gamut/src/Modals/Modal.tsx

Fixes breaking type change to ModalViews
Check out CI in the two PRs below and see that the tests are now passing. 
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/35678)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](https://github.com/codecademy-engineering/mono/pull/2085)   |

fix(ModalView): fix onRequestClose type

---

packages/gamut-icons/src/svg/mini/mini-circle-icon.svg

Adds MiniCircleIcon to gamut-icons
As an admin user, visit https://tayra.codecademy.com/code-challenges/web-dev-foundations-sectional-assessments?PR_ENV=le-pr-2041 to see the icon in use.
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/2041/files)  | [Portal Env](https://tayra.codecademy.com/code-challenges/web-dev-foundations-sectional-assessments?PR_ENV=le-pr-2041)   |

feat(Icon): add mini circle icon

---

packages/gamut-illustrations/src/PracticeTarget.tsx
packages/gamut-illustrations/src/index.ts

Adding the practice target illustration for use in the `StartInterstitialComponent` in the learning environment for Smart Practice interstitial design updates
- Visit Storybook and [go to Illustrations](https://64779e51438af3052f087506--gamut-preview.netlify.app/?path=/docs/atoms-illustrations--editable-illustration)
- See the PracticeTarget illustration
On navy background it looks like this:
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') …

feat(Illustration): add PracticeTarget illustration

---

packages/gamut-labs/package.json
yarn.lock

Bumps tracking in gamut-labs so there is not a package version mismatch in the monolith following a deploy to brand in mono.
| Another Repo | [Another Link](http://www.google.fr/ 'Named link …

feat: bump tracking in labs

---

packages/gamut-labs/src/ScoreSummary/types.tsx

Adds code challenge narrative as a layout type to the LayoutComponent type. This will resolve the type error in [this PR ](https://github.com/codecademy-engineering/mono/pull/2079/files#diff-d9ac76edec1e9f4f82ace89a1aacd00a0aa635b456b26945b1142ec9c67193edR23)
1. Build the package locally and install in in your local monorepo dev environment after building this branch locally https://github.com/codecademy-engineering/mono/pull/2195.
2. Install the package locally in the monorepo, and make sure that http://localhost:4200/exams/journeys/full-stack-engineer/paths/fscj-22-web-development-foundations/parts/2 load correctly with no issues. …

chore(labs): add code challenge narrative type to LayoutComponent

---

packages/gamut/src/Popover/Popover.tsx
packages/gamut/src/Popover/types.tsx

No user-facing change. Convert type of `popoverContainerRef` to allow passing in a `RefCallback` (needed for upcoming DropdownButton bugfix), and remove a `nullRef` that is not needed.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/36000)  |
| Monorepo       | [Monorepo PR](https://github.com/codecademy-engineering/mono/pull/2632)  |
[REACH-2522]: https://codecademy.atlassian.net/browse/REACH-2522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(Popover): Change popoverContainerRef type and remove null ref

---

packages/gamut/src/Loading/Shimmer.tsx

Refactor Shimmer styles so that `%` is not used in strings nested within other emotion style declarations, which was causing an `illegal escape sequence` error to be thrown when SWC is enabled in portal-app.
This error appears in portal-app on the catalog when SWC is enabled by removing `babel.config.js`
It is confirmed that the error goes away when consuming the gamut alpha package from this PR. (although it does not resolve all errors related to SWC)
1. Run Storybook
1. Search for the shimmer
1. Verify that the shimmer animation still works properly
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/3 …

fix: Refactor Shimmer styles for SWC compatibility

---

.github/workflows/pr-title.yml

The pr title job seems to be failing for everyone, this seems to fix it!
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link …

chore(ci): upgrade pr title action

---

packages/gamut/package.json
packages/gamut/src/Markdown/index.tsx
packages/gamut/src/Markdown/libs/overrides/index.tsx
packages/gamut/src/typings/html-to-react.d.ts
packages/styleguide/stories/Organisms/Markdown/index.stories.mdx
yarn.lock

[Storybook Example](https://64f78f72ca11ce28fc7830c5--gamut-preview.netlify.app/?path=/docs/organisms-markdown--link-overrides)
* Allow overrides in Markdown without passing skipDefaultOverrides
* Upgrade html-to-react to latest
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/36428)  | See PR |
| Monorepo       | [Monorepo Link](https://github.com/codecademy-engineering/mono/pull/3433)  |  See PR |

feat(Markdown): Allow overrides in Markdown without passing skipDefaultOverrides

---

.lintstagedrc.mjs
package.json
packages/eslint-plugin-gamut/package.json
packages/gamut-icons/package.json
packages/gamut-illustrations/package.json
packages/gamut-kit/package.json
packages/gamut-patterns/package.json
packages/gamut-styles/package.json
packages/gamut-tests/package.json
packages/gamut/package.json
packages/macros/package.json
packages/styleguide/package.json
packages/variance/package.json

Enable formatting & sorting for package.json files

chore: format/sort package.json files

---

packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx
packages/gamut/src/GridForm/GridFormInputGroup/__fixtures__/assertions.tsx
packages/gamut/src/GridForm/GridFormInputGroup/__tests__/GridFormInputs.test.tsx
packages/gamut/src/GridForm/types.ts
packages/styleguide/stories/Organisms/GridForm.stories.mdx

Add the rows prop to GridFormTextArea
* View the larger TextArea in the "With tooltip" section of the GridForm story
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/36478)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/3578)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-3578)   |

feat(GridFormTextArea): add rows to text-area field

---

.github/CODEOWNERS

I think our CODEOWNERS file was only requiring us on PRs that change styleguide. Now we are required on everything. 
I have a test branch against this one [here](https://github.com/Codecademy/gamut/pull/2786) that is working as intended.
| Another Repo | …

fix(codeowners): fix codeowners

---

packages/gamut/src/Form/styles/Radio-styles.ts
packages/styleguide/stories/Layouts/Elements/index.tsx

chore: versioning

---

packages/styleguide/.storybook/preview.ts
packages/styleguide/stories/Meta/Best Practices.stories.mdx
packages/styleguide/stories/Meta/Contributing.stories.mdx

Migrate our best practices to from Notion to storybook and made it more generalized
Check out the new styleguide page [here](https://651c4c12021841740ead5789--gamut-preview.netlify.app/?path=/docs/meta-best-practices--page)

docs(styleguide): migrate best practices to gamut

---

packages/gamut-illustrations/src/SevenDayTrial.tsx
packages/gamut-illustrations/src/index.ts

adds illustration for seven day trials
1. run storybook
2. navigate to [Illustrations](http://localhost:6006/?path=/docs/atoms-illustrations--editable-illustration)
3. validate the new illustration is available …

feat(Illustration): add seven day trial illustration

---

packages/styleguide/stories/Foundations/System/Props.stories.mdx

Another day in the life
Fixes a bug that has been stopping publishes
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link …

fix: gamut failing prettier check

---

packages/gamut/src/Button/shared.ts
packages/gamut/src/Button/variants.ts
packages/styleguide/stories/Atoms/Button/examples.tsx
packages/styleguide/stories/Atoms/Button/index.stories.mdx

- adds a larger button size to buttons
1. run storybook, navigate to http://localhost:6006/?path=/docs/atoms-button--fill-button
2. validate that buttons that show the size prop now include `large`
| Portal | [Portal Link](https://github.com/codecademy-engineering/mono/pull/3985 'Named link title')  |  [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-3985 'Named link title')  |
| Monolith | [PR Link](https://github.com/codecademy-engineering/Codecademy/pull/36702) | …

feat(Button): add large size

---

.github/dependabot.yml

Updates dependabot to eliminate open PRs that aren't security issues.
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link …

ci: set dependabot to issue only security fixes

---

packages/gamut/src/Alert/Alert.tsx

fixes Alert types for href
No type errors [here](https://github.com/codecademy-engineering/mono/pull/4445)

fix(Alert): href error

---

packages/gamut/src/Form/SelectDropdown/SelectDropdown.tsx
packages/gamut/src/Form/SelectDropdown/elements.tsx
packages/gamut/src/Form/SelectDropdown/types.tsx
packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
packages/styleguide/stories/Atoms/FormInputs/examples.tsx

Add checkmark to selected SelectDropdown options. Als fixed some centering stuff with the optional leading icons.
* Go to the SelectDropdown page
* Choose an item from the SelectDropdown options
* See the checkmark next to the selected option
* See icons are more visually aligned
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/6065)  | [Portal Env](http://www.google.fr/ 'Named link title')   |

feat(SelectDropdown): Add checkmark to selected option

---

.github/workflows/pr-title.yml

Replaces [conventional-pr-title-action](https://github.com/aslafy-z/conventional-pr-title-action?tab=readme-ov-file) with [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request).
1. See CI is passing
2. If you'd like to test failure state - make a branch off of this one with a failing PR title name and see this error in CI
N/A

ci: update pr-title GHA

---

packages/gamut-illustrations/src/ProjectReview.tsx

Updating the illustration to new one.

feat(illustration): AI Project Review illustration

---

.github/workflows/push.yml
package.json
yarn.lock

ci: fix nx cache issue with run-on-yarn update

---

dist/static/robots.txt

Noticed this was what was blocking Stacey from using google's NotebookLM tool.
I don't really remember why we disallowed bots in the first place? …

chore: allow bots/scrapers

---

.circleci/config.yml
packages/gamut/src/AccordionButtonDeprecated/ButtonDeprecated/index.tsx
packages/gamut/src/AccordionButtonDeprecated/ButtonDeprecatedBase/index.tsx

Updates the prod release command + updates a couple of failing compile runs from mono/monolith
I really don't know how to test this, I'm gonna ask @jakemhiller lol. i do have test packages up here - 
* https://github.com/codecademy-engineering/mono/pull/8629
* https://github.com/codecademy-engineering/Codecademy/pull/38880

update production deploy

---

packages/gamut/src/Overlay/index.tsx

Hot fix for overlay's shroud to be a static color instead of colormode compliant. 
1. Check the Overlay story in light and dark mode — the background should be slightly gray regardless of light/dark mode (this is the same for both Modal + Dialog as well) 
2. Check the Modal story in light and dark mode
3. Check the Dialog story in light and dark mode 
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/39197)  | [Monolith Env](https://pr-39197-monolith.dev-eks.codecademy.com/) |
| Portal …

fix(Overlay): updating shroud to be a static color

---

packages/gamut/src/Anchor/index.tsx
packages/gamut/src/Button/shared/InlineIconButton.tsx
packages/styleguide/src/lib/Atoms/Buttons/Button/Button.stories.tsx

Updates trailing icons for Anchor from 12 to 16 and normal + large sized buttons from 12 to 16. 
Small sized buttons remain size 12.
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/39211)  | [Monolith Env](https://pr-39211-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/9446)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-9446)   |
[GM-932]: …

style(Anchor + Button): update icons sizes

---

packages/styleguide/src/lib/Molecules/Video/Video.mdx
packages/styleguide/src/lib/Molecules/Video/Video.stories.tsx

Adding a new story for video that includes HLS and new video player features.
1. Go to the Video story (it's in Molecules), check the new story for HLS video with new features (captions / thumbnails / poster) and see if it makes sense.
2. Profit!

docs: update video story

---

packages/gamut/src/Video/index.tsx
packages/styleguide/src/lib/Molecules/Video/Video.mdx
packages/styleguide/src/lib/Molecules/Video/Video.stories.tsx

default video to react-player for the time being
* you can see the YT autogen captions in the video page 
* 

fix: default to react-player

---

packages/gamut/src/FeatureShimmer/index.tsx

Sometimes the shimmer slightly stays in view on certain screen sizes. This fades out the shimmer so in case that happens it's not visible.
1. View FeatureShimmer story
2. Make the screen small and in dark mode
3. See the shimmer move across screen and then fade out
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/9579)  | [Portal Env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-9579)   |
[GM-903]: https://skillsoftdev.atlassian.net/browse/GM-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …

fix(FeatureShimmer): Fade out shimmer

---

packages/gamut/src/Anchor/index.tsx
packages/styleguide/src/lib/Typography/Anchor/Anchor.examples.tsx
packages/styleguide/src/lib/Typography/Anchor/Anchor.mdx

Adds a new standard-secondary variant to Anchor
1. View the Anchor story
2. Confirm you see the new variant and confirm it matches the figma
3. Hover/tab over the new variant and confirm it matches the figma
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/39225)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/9591)  | [Portal Env](http://www.google.fr/ 'Named link title')   |
[GM-906]: …

feat(Anchor): New standard-secondary variant

---

packages/gamut/src/Tip/shared/styles.tsx

Fix: Inline Tooltip Beak border color to primary  
1. Open [storybook](https://67ec4d6d467b368a5b588a45--gamut-preview.netlify.app/?path=/docs/molecules-tips-tooltip--docs) and navigate to Tip
2. Ensure beak color is same as Tipbody border (i.e border-primary)
3. Profit
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link …

fix(Tip): Update InlineTooltip beak border color

---

packages/gamut/src/Form/styles/shared-system-props.ts

Updates the border color for `SelectDropdown` and `Select` to be `border-primary` instead of `border-disabled` since it is used when enabled
1. Visit SelectDropdown story
2. Confirm border color is border-primary
3. Visit Select story
4. Confirm border color is border-primary
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/39338)  | [Monolith Env](https://pr-39338-monolith.dev-eks.codecademy.com/) |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/mono/pull/975 …

feat(SelectDropdown): Update border color

---

packages/gamut/src/DataList/Controls/SortControl.tsx

Updates the sort control color and hover color used in DataList and DataTable so that it is not an accessibility issue and also adheres to color mode
1. Visit DataTable story
2. See that the sort controls are darker
3. Hover over the sort controls and see it is darker
4. Sort a column and see that the active sort is darker than hover/default sort
5. Change to dark mode
6. Repeat 2-4 but they should each be lighter
7. Visit DataList story
8. Repeat 2-6
| Monolith     | [Monolith …

feat(DataList): Update sort control color

---

packages/gamut/src/Form/SelectDropdown/elements.tsx
packages/gamut/src/Form/SelectDropdown/styles.ts

The "Tags" in SelectDropdown's multiple select are now aligned with the styling of the `selection` variant of the Tag component. 
1. Go to the SelectDropdown story and [Multiple Selection section](https://68111f49f2840df394155a3d--gamut-preview.netlify.app/?path=/story/atoms-forminputs-selectdropdown--multiple-select&globals=viewport:responsive)
2. Select some options and check against the [selection variant of Tag](https://68111f49f2840df394155a3d--gamut-preview.netlify.app/?path=/docs/atoms-tag--docs&globals=viewport:responsive#selection), these stylings should now be aligned.
3. Check in dark mode too 
4. ...
5. Profit!  …

fix(SelectDropdown): align styling of multi selection tags with Tag component

---

packages/styleguide/src/lib/Atoms/Badge/Badge.mdx
packages/styleguide/src/lib/Atoms/InternalFloatingCard/InternalFloatingCard.mdx
packages/styleguide/src/lib/Meta/Contributing.mdx
packages/styleguide/src/lib/Molecules/AccordionButtonDeprecated/AccordionButtonDeprecated.mdx
packages/styleguide/src/lib/Molecules/AccordionDeprecated/AccordionDeprecated.mdx
packages/styleguide/src/lib/Molecules/Disclosure/Disclosure.mdx

Callouts don't support markdown, but by writing raw HTML/JSX, their contents can be rendered as intended. 
Check out the following pages and their callouts:
1. [Contributing](https://6815279c2a4274248948ee89--gamut-preview.netlify.app/?path=/docs/meta-contributing--docs#pull-requests) 
2. [Badge](https://6815279c2a4274248948ee89--gamut-preview.netlify.app/?path=/docs/atoms-badge--docs#accent)
3. [InternalFloatingCard](https://6815279c2a4274248948ee89--gamut-preview.netlify.app/?path=/docs/atoms-internalfloatingcard--docs)
4. [AccordionDeprecated](https://6815279c2a4274248948ee89--gamut-preview.netlify.app/?path=/docs/molecules-accordiondeprecated--docs)
5. [AccordionButtonDeprecated](https://6815279c2a4274248948ee89--gamut-preview.netlify.app/?path=/docs/molecules-accordionbuttondeprecated …

docs: update callout instances to proper formatting

---

packages/styleguide/src/lib/Atoms/Icons/constants.tsx

Moved the `PaypalLogoIcon` from the Interface category to the Vendor category. 
- <del> [ ] This PR includes unit tests for the code change </del>
- <del> [ ] This PR includes testing instructions tests for the code change </del>
- <del> [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories </del>
1. Go to regular Icons story X
2. Scroll down to the Vendor section
3. Notice that the paypallogo is now there instead of the interface section
4. ...
5. Finish and do a celebratory dance
N/A only documentation changes
[GM-1062]: https://skillsoftdev.atlassian.net/browse/GM-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(Icon): Moved paypallogo to vendor category

---

packages/styleguide/src/lib/Organisms/Lists & Tables/DataList/DataList.stories.tsx

Fixes expanded DataList story to actually show expanded. Note: the extra row gap in the expanded story is being fixed separately by @dreamwasp 
1. Go to DataList story
2. See the expanded story shows an expanded row
3. Finish and do a celebratory dance
N/A
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')
| Mono       | [Mono PR](http://www.google.fr/ 'Named link title')
[GM-1140]: https://skillsoftdev.atlassian.net/browse/GM-1140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(DataList): Fixes expanded list story

---

packages/gamut-icons/src/svg/regular/git-icon.svg
packages/gamut-icons/src/svg/regular/markdown-icon.svg
packages/gamut-icons/src/svg/regular/typescript-icon.svg
packages/styleguide/src/lib/Atoms/Icons/constants.tsx

adds GitIcon, MarkdownIcon, TypescriptIcon
1. Go to icons in storybook preview
2. Look for GitIcon, MarkdownIcon, TypescriptIcon
and/or
1. go to tengu pr env
2. open up resources dropdown
4. validate git, markdown, and typescript tiles
| Monolith     | n/a |
| Mono       | [Mono PR env](https://tengu.codecademy.com/catalog?PR_ENV=portal-app-pr-10941)
[DOT-1102]: https://skillsoftdev.atlassian.net/browse/DOT-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(Icons): add git, markdown, typescript icons

---

packages/gamut-styles/src/GamutProvider.tsx

Add nonce property to GamutProvider, passes through to the emotion cache
```
import { GamutProvider, createEmotionCache } from '@codecademy/gamut-styles';
const emotionCache = createEmotionCache({
nonce: window.myNonce
});
const MyApp = () => {
return (
<GamutProvider cache={emotionCache}>
<MyComponent />
</GamutProvider>
)
}
```
```
import { GamutProvider } from '@codecademy/gamut-styles';
const MyApp = () => {
return (
<GamutProvider nonce={window.myNonce}>
<MyComponent />
</GamutProvider>
)
}
```
1. Go to story X
2. Do something
3. Do that something in dark mode
4. Check it with VO
5. Finish and do a celebratory dance …

feat: add nonce property to GamutProvider [FCORE-5007]
